### ISSUE TITLE
Create org for Rhai

### ISSUE THREAD

**Issue by jonathandturner** [rhaiscript/rhai#195]
@schungx (and other contributors)

It's been a long while since I was actively involved with Rhai. It's been great to see it continue to bloom under your care.

I was wondering if we should consider finding a good home for this repo. While it's fine with me to continue to have it live here, I don't think it reflects the current maturity or authorship of Rhai today. 

Thoughts?

**Comment by schungx** [comment]
I'm also glad to see that there are now quite some people actively contributing to this repo.

I totally support the creating of an org that'll start pooling together all the different pieces.

However, it depends on _when_ it would be a good time to do it...  there are multiple links outside pointing to this repo, and I'm not sure if it warrants moving to a new location as yet, especially when we still only have... like... one library, and one WASM playground.  There doesn't seem to be enough assets to move to an independent org...

Welcome thoughts from others!

**Comment by jonathandturner** [comment]
Luckily, if we use the github system to move it, all the old links *should* redirect automatically. I've done this with a few repos in the past and it was relatively smooth.

Happy to keep it here, also, if that makes more sense.

**Comment by schungx** [comment]
My person suggestion is to keep it here, until we have more assets that make sense to start up an org...

**Comment by jonathandturner** [comment]
Sounds good. Will close this issue for now.

**Comment by schungx** [comment]
Reopening this...  now may be getting close to the time...

**Comment by jonathandturner** [comment]
@schungx - you want to create one? I can give ownership over to it.

**Comment by schungx** [comment]
@jonathandturner  planning on it, as it seems we are gathering more stuff on the way...

Will this URL link be automatically redirected to the org URL?  Not good for all of them to break...

**Comment by jonathandturner** [comment]
I *think* I can give ownership of this repo to the new org, and all the links will redirect

**Comment by schungx** [comment]
Look like it also: https://github.blog/2013-05-16-repository-redirects-are-here/

You being the original author, maybe you'd do the honors of creating the org?  :-D

**Comment by jonathandturner** [comment]
Done and moved!

https://github.com/rhaiscript/rhai

**Comment by schungx** [comment]
BTW, can you give me Ownership right?  I'll need to start moving stuff in there...  Thanks!

**Comment by jonathandturner** [comment]
@schungx done!
