### ISSUE TITLE
Support functions with Dynamic arguments

### ISSUE THREAD

**Issue by SuperCuber** [rhaiscript/rhai#243]
Self explanatory title.
Since strings have `.index_of(char | string)` I think arrays should be `index_of(dynamic)` which behaves similarly,
and `string.split(char | string)` would be useful enough that I think it should be builtin as well.

**Comment by schungx** [comment]
>  Since strings have `.index_of(char | string)` I think arrays should be `index_of(dynamic)` which behaves similarly,

The Dynamic type may not be comparable...  That is, the data contained inside may not have an implementation of `==`.

So it is not possible to have a blanket implementation of `index_of` for all types.

I'll think about `string.split()`...

**Comment by SuperCuber** [comment]
If `dynamic in array` is possible I don't think `index_of(dynamic)` should be impossible, unless the `in` operator is a very special case

**Comment by schungx** [comment]
Yes it is.  It actually checks whether `==` is registered and, if so, uses it.  If it is not registered, then the compare is considered `false`.

Possible as a built in predicate but not as a registered function.

**Comment by SuperCuber** [comment]
I see. Can't `index_of` be the same? If `==` is registered, compare, otherwise return `-1`?

**Comment by schungx** [comment]
Not as easily... it is hard to detect the existence of another function in a registered function...

`in` is a built-in operator that is treated specially as a primitive operation, not a function call.

Actually I'm thinking about this.  In fact, a more pressing one is to implement `print` and `debug` and the string concat functions based on calling `to_string()` on any type to avoid needing to manually register all those functions.

**Comment by SuperCuber** [comment]
Honestly given how `push (array, T)` isn't defined I found it surprising actually that `T in array` worked, but I think "`T in array` works because magic but nothing else works" is not a great state to be in.

If I was to make a decision, either
1) `T in array` would return an error `no function == (T, T2)` for whatever element it fails to compare, or
2) `T in array` and `index_of` would both work for the same reason that by default `== (T, T2)` is blanket implemented to return `false`

And I think that it's already implemented with `==` since looks like `1 == Fn("...")` returns false and I doubt you defined each pair of builtin types (I just tried in the online playground so didn't check with a custom type)

So I guess the issue is that this "fallback implementation" is only easily available in Rhai and not in the engine's code?

And yeah the string blanket implementations would be nice as well.

**Comment by schungx** [comment]
> "`T in array` works because magic but nothing else works"

You're right... that's the current state right now...  Not ideal, I admit.

> And I think that it's already implemented with `==` since looks like `1 == Fn("...")` returns false and I doubt you defined each pair of builtin types (I just tried in the online playground so didn't check with a custom type)

Comparison operators default to `false` when not implemented (`!=` defaults to `true`).  This is to be consistent with other dynamic languages.

> So I guess the issue is that this "fallback implementation" is only easily available in Rhai and not in the engine's code?

You can used the advanced API to register a raw function that defaults to something when the argument types are not supported...

**Comment by SuperCuber** [comment]
> You can used the advanced API to register a raw function that defaults to something when the argument types are not supported...

I mean calling the function, since you said

> it is hard to detect the existence of another function in a registered function...

**Comment by schungx** [comment]
Defaulting to `false` is readily doable within a registered function.

Finding whether the `==` function for a custom type exists is not.

**Comment by SuperCuber** [comment]
>Defaulting to false is readily doable within a registered function.
Finding whether the == function for a custom type exists is not.

maybe there should be a method from Engine that allows to "dynamically" call a function or its fallback?
Unless there is and it's not enough?

> And, never forget, a script can freely override the definition of == for any type!

According to the documentation [here](https://schungx.github.io/rhai/rust/operators.html), scripts cannot override operators...
Is it different in 0.19?

Oh and regarding adding blanket `print` implementation, `print(array)` currently doesn't support custom types very well - even if they have their own `print` it looks like it just prints the rust type's name (not even the registered type name returned by `type_of`).
I wonder if that's a bug or if I'm just not implementing something that I should be.

**Comment by schungx** [comment]
> According to the documentation [here](https://schungx.github.io/rhai/rust/operators.html), scripts cannot override operators...

HHhhmmm... you're correct!

> Oh and regarding adding blanket `print` implementation, `print(array)` currently doesn't support custom types very well - even if they have their own `print` it looks like it just prints the rust type's name (not even the registered type name returned by `type_of`).

That's right.  Rhai really isn't very good at print formatting.  The `print` function is a hack.  It is registered for every type.  However, array doesn't use `print` or `to_string` to format its elements for printing, so it defaults to just printing its type.  And the type name mappings are in `Engine`, so when the array is being printed, it doesn't know how to map those type names.

So, all-in-all, the whole thing with printing and converting to string is sub-optimal.  Luckily, Rhai is usually used as an embedded scripting environment, so printing is mostly for diagnostics...

**Comment by schungx** [comment]
I have given it some more thought, and blanket implementations are still not very possible right now.

Unless _all_ parameters are generic, we can easily define a function that looks like a script (i.e. all parameters are dynamic) but implemented in Rust.

However, for most useful functions, we'll need at least one parameter of a particular type.

For example, if we implement `array.push()` blanket-ly, then that `push` function not only applies to arrays, it applies to _any other type_.  Obviously that makes it sub-optimal.

**Comment by SuperCuber** [comment]
Yeah, seems like this could be more complicated than I initially thought.

**Comment by schungx** [comment]
This has now officially landed in `master`.  Closing now.
