### ISSUE TITLE
Add lifetime to Engine

### ISSUE THREAD

**Issue by Kaiser1989** [rhaiscript/rhai#306]
Maybe consider, giving Engine struct a lifetime. Currently "register_fn" expects a `static` lifetime function. It would be enough, if the function outlives the Engine's lifetime.

Assume a function with a lookup from a reference:

```
let s = some_ref;
{
    let mut engine = Engine::new();
    engine.register_fn("test_func", move |id: ImmutableString| s.get(id).do_something());

    // do stuff with engine
}
```

This way we hide the "s" from the user, it can only be used through our function.

Same yields for Scope. We are not able to `scope.push_constant`, even if the reference would outlive Engine's lifetime.

**Comment by schungx** [comment]
Yes, I once tried adding a lifetime to `Engine`, but then it ends up changing 30 million lines...  so I rolled it back!

**Comment by Kaiser1989** [comment]
I know this, ... it bubbles so fast

**Comment by schungx** [comment]
Yes, and I figured, it would be a relatively restricted usage where the `Engine` lasts longer than all these functions and objects.  The standard mode of operators for Rhai is to spawn light-weight engines whenever necessary.

Therefore I didn't bother in the end.

**Comment by schungx** [comment]
Closing this for now as there hasn't been much call for life-time constraint `Engine` instances so far.

**Comment by sasq64** [comment]
I still would like an alternative to the `Rc<RefCell>` + muiltiple clones pattern.

Would it be possible to do something like
```rust
let exec_env = rhai_engine.new_exec_env();
exec_env.register_fn(...);
exec_env.run();
```

Where this register_fn arguments lifetime was the same as the exec_env?

**Comment by schungx** [comment]
Not easily. Functions are registered into the engine, not individual execution context. 

So the engine itself must carry a lifetime.
