### ISSUE TITLE
rhai_repl: add readline support.

### ISSUE THREAD

**Issue by stustd** [rhaiscript/rhai#323]
I miss readline support in the REPL: scrolling through statement history is very convenient.

**Comment by schungx** [comment]
What do you mean?  Something like `!123` to recall certain lines?

Right now can you use the arrow keys to scroll through past lines?  I can do this with Windows, not very sure with bash...

**Comment by schungx** [comment]
Alright, I tried it with `bash` on Linux and it doesn't seem to recognize the arrow keys.  Not sure how I can add this feature, because I'm just reading from `stdin`...  any pointers?

**Comment by stustd** [comment]
[This](https://lib.rs/crates/rustyline) probably will do it.

**Comment by schungx** [comment]
`rhai-repl` is intended to be an example only for tutorial purposes.  Right now it is not constructed as a stand-alone tool.

In the future, `rhai-repl` and `rhai-run` may be promoted to full-blown tools, and they'll probably need to handle options etc.

In the meantime, I believe you can easily add `rustyline` to `repl` yourself...

**Comment by stustd** [comment]
That's true, I "can [..and might] easily add rustyline to repl" myself, but since they're in the master's `src/bin` directory I guessed they'd be promoted sooner than later.

**Comment by schungx** [comment]
I would hesitate to pull in another crate just for this tool... Maybe add new `[[bin]]` sections to `Cargo.toml` and put `rustyline` under the `rhai-repl` bin...

Would you be nice enough to revise these two tools to make them proper?  *hint*  *hint*  *hint*  *wink* *wink* *knudge* *knudge* say no more...

**Comment by stustd** [comment]
> I would hesitate to pull in another crate just for this tool... Maybe add new `[[bin]]` sections to `Cargo.toml` and put `rustyline` under the `rhai-repl` bin...

That would be the way.
> 
> Would you be nice enough to revise these two tools to make them proper? _hint_ _hint_ _hint_ _wink_ _wink_ _knudge_ _knudge_ say no more...

If I had the time I would... (sorry to disappoint you...). However, I'm pretty familiar with `clap` (options parsing) and can quickly put this functionality together if I you can provide me with input what a rhai repl needs.

That said, at the moment my `rhai` work is focused on getting imported scripts compiled in a `rhai` top-level script;  [I followed your advise](https://discord.com/channels/767611025456889857/767611025456889860/796119258865729556) and it works. Is there a way to walk the AST so that I can retrieve all imports in a top-level script (this would avoid a separate `imports.rhai` script).

**Comment by schungx** [comment]
> That said, at the moment my `rhai` work is focused on getting imported scripts compiled in a `rhai` top-level script; [I followed your advise](https://discord.com/channels/767611025456889857/767611025456889860/796119258865729556) and it works. Is there a way to walk the AST so that I can retrieve all imports in a top-level script (this would avoid a separate `imports.rhai` script).

Not easily.. remember the `import` statements form part of your main script.  You really need to evaluate the script in full, and then look at what modules are left behind.

Turn on the `internals` feature if you want to walk the `AST` (you'll be able to).  Since you're only restricting yourself to `import` statements at the global (top) level, it is very easy... just do `ast.statements()` and it returns `&[Stmt]` which is a list of statements.  Find if any of them is `Stmt::Import`.

**Comment by schungx** [comment]
Closing this for now since it doesn't seem possible to selectively add `rustyline` to `repl` as a `bin` tool without adding it to the entire lib.
