### ISSUE TITLE
Inserting into array

### ISSUE THREAD

**Issue by ThiNei2l** [rhaiscript/rhai#337]
Hello,
i think that there may be an indexing problem when inserting something into an array.
Consider the following example:
```rust
for i in range(0, 5) {
    let a = [1, 2, 3, 4];
    a.insert(i, 99);
    print(a);
}
```

I would expect the output
```
[99, 1, 2, 3, 4]
[1, 99, 2, 3, 4]
[1, 2, 99, 3, 4]
[1, 2, 3, 99, 4]
[1, 2, 3, 4, 99]
```

But instead i get
```
[99, 1, 2, 3, 4]
[1, 99, 2, 3, 4]
[1, 2, 99, 3, 4]
[1, 2, 3, 4, 99]
[1, 2, 3, 4, 99]
```

PS: in the book (https://rhaiscript.github.io/book/language/arrays.html) the order of the two arguments of `insert` seems to be swapped.

PPS: this is probably fixed by replacing line 32 in src/packages/array_basic.rs:
`} else if (position as usize) >= list.len() - 1 {`
->
`} else if (position as usize) >= list.len() {`

**Comment by schungx** [comment]
Oops!  Off by one errors...  the best kind!

Thanks for catching this!

Will be fixed in the next version.  You can also pull from master, which I'll push a fix soon.

**Comment by schungx** [comment]
@ThiNei2l   the fix has landed in master.

**Comment by ThiNei2l** [comment]
Thanks for the fast reply.
Works now.
