### ISSUE TITLE
Unreachable code should panic?

### ISSUE THREAD

**Issue by adautopaulazup** [rhaiscript/rhai#340]
Hi Guys, 

First of all, I wanna say thank you for the incredible work, Rhai is amazing.

Assume a script with the following syntax error:

```
let my_obj = #{
   "movie-names" : ["Matrix","Star Wars"]
};

my_obj["movie-names"].().to_string();
```

Running this will lead the application to panic...even the playground could not recover after executing such a script, you have to reload the page to run any other script there. So, my question is: Why no return an EvalAltResult instead?

**Comment by schungx** [comment]
Good catch.  All panics are considered bugs.  Rhai is designed to not bring down the host system.

**Comment by schungx** [comment]
A fix has been pushed to the latest master.  Please pull from here to check if it is now ok.  Thanks!

**Comment by adautopaulazup** [comment]
I ran a few tests here and it's fixed. Thanks!

**Comment by schungx** [comment]
Thanks for catching this bug!
