### ISSUE TITLE
Parser and execution will halt if statement is ended with extra semicolon

### ISSUE THREAD

**Issue by hkazu** [rhaiscript/rhai#344]
If a statement line ends with a ;; a script execution will freeze.
No further error is reported. 
Can be tried in the playground.

For example the first print statement  ends with double semicolon:
`fn run(a) {`
`    let b = a + 1;`
`    print("Hello world! a = " + a);;`
`    print("Hello world! a = " + a);`
`}`
`run(10);`

Thank-you,

**Comment by Kezii** [comment]
I just indipendently discovered this bug, this was hogging a cpu core and causing a DoS when executing untrusted scripts, I bisected the breaking change to this commit: 
https://github.com/rhaiscript/rhai/commit/eca8212f389d788cadd6c287135cfd14fafabb8a

**Comment by schungx** [comment]
Thanks for catching this. I'll fix asap.

**Comment by schungx** [comment]
Yes this is a bug and is now fixed.  Thanks for pointing it out.  I'll push to master in a bit.

**Comment by schungx** [comment]
The fix has landed in master: https://github.com/rhaiscript/rhai/pull/346
