### ISSUE TITLE
Cannot break a loop from try block

### ISSUE THREAD

**Issue by hkazu** [rhaiscript/rhai#345]
I have a question, why is not possible to break a loop (for or while) with a break statement inside a try...catch block?

Example:
```
fn run(a) {
    let b = a + 1;
    while b > 0 {
        print("Hello world! a = " + a);
        b = b - 1;
        try {
            break;
            throw;
        } catch {
            
        }
    }
}
run(10);
```

**Comment by schungx** [comment]
Will check it out.

**Comment by schungx** [comment]
In Rhai, any panic (unless calling a public function with a marked panic condition) is a bug.  So this is a bug.

Thanks for flushing it out.

I've already fixed it and will push to master soon.

**Comment by schungx** [comment]
The fix has landed in master: https://github.com/rhaiscript/rhai/pull/346
