### ISSUE TITLE
How could I expose a reader to rhai?

### ISSUE THREAD

**Issue by martinlindhe** [rhaiscript/rhai#359]
Hi, new to rhai and still trying to figure things out.
I would like to use rhai to make a script working on a data stream but cant seem to figure out how I could do it.
I cannot keep a BufReader<File> in a struct exposed in rhai because it don't implement Clone.

Maybe I am thinking about it wrong?

**Comment by schungx** [comment]
There are two options:

1) Use interior mutability, aka `RefCell` etc.  Then it is Clone.  In this case, your BufReader is a _command object_ and there is a usage pattern on this scenario.

2) Keep BufReader outside of Rhai.  Read data then feed into the scripting engine for processing.

**Comment by schungx** [comment]
Is your problem resolved?  Can this be closed?

**Comment by schungx** [comment]
Closing this for now.  Feel free to reopen if your issue is not resolved.
