### ISSUE TITLE
Global imports unavailable in call_fn

### ISSUE THREAD

**Issue by SWW13** [rhaiscript/rhai#362]
I think this is a bug as the book states that global imports are the intended way:

> They can appear anywhere a normal statement can be, but in the vast majority of cases import statements are group at the beginning of a script. It is not advised to deviate from this common practice unless there is a Very Good Reason™.

`main.rs`:
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let engine = rhai::Engine::new();

    let ast = engine.compile_file("foo.rhai".into())?;
    let mut scope = rhai::Scope::new();
    engine.call_fn(&mut scope, &ast, "foo", ())?;

    Ok(())
}
```

`foo.rhai`:
```rhai
// doens't work
import "bar" as bar;

fn foo() {
    // works
    // import "bar" as bar;
    print("foo");
    bar::bar();
}
```

`bar.rhai`:
```rhai
fn bar() {
    print("bar");
}
```

Output:
```
foo
Error: ErrorInFunctionCall("foo", "", ErrorModuleNotFound("bar", 8:5), 0:0)
```

**Comment by schungx** [comment]
This is intended.  Sorry the documentation probably didn't make it clear.

Functions in Rhai are mostly _pure_ and they form their own small closed worlds.  Nothing from the outside gets in.  For example, if you define a global constant, you can't refer to it in a function.  Same as imports.

You have to import it inside the function itself.  Most built-in module resolvers are smart enough to share module instances so importing is cheap.

There are many benefits to keeping functions pure:

1) There is no need for a "scope chain"
2) Functions can be separated and remixed, even from other scripts
3) Functions can form building blocks of larger systems without too much worry about the external environment.

**Comment by SWW13** [comment]
But other functions in the same file are accessible. I don't see how the global import impacts the pureness of functions while other functions don't.

Shouldn't it be possible to do the import during the AST compile step and have them accessible from within functions as long as they aren't moved out of this "context"?
I image the import should logically (not technically) work like a C preprocess `#include "bar.h"`, so it's like a copy&paste with added namespace from a developers perspective.

**Comment by schungx** [comment]
Hhmmm....  you raised a good question.  I tried it and it seems to work...  what I described was the behavior in _previous_ versions.  The recent versions allow you to refer to global imported modules.

For example, I tried the following in `repl` and it works:

```rust
import "hello" as h;

fn foo() {
    h::action();
}

foo();
```

`hello.rhai` is an external file with the `action` function.

**Comment by schungx** [comment]
Ah, I see now you're using `Engine::call_fn`.

This is an API that is only intended for you to call individual functions.  It does _NOT_ encapsulate the entire running environment -- because it _doesn't_ run the script when you call the function; it only runs that single function.  Therefore, your global `import` statement is never run.

**Comment by schungx** [comment]
You may want to do: `engine.eval_ast_with_scope(&scope, &ast, "foo()")?` instead.

**Comment by SWW13** [comment]
> This is an API that is only intended for you to call individual functions. It does NOT encapsulate the entire running environment -- because it doesn't run the script when you call the function; it only runs that single function. Therefore, your global import statement is never run.

Ah i see, so the global import is technically an statement that needs to be executed.

> You may want to do: `engine.eval_ast_with_scope(&scope, &ast, "foo()")?` instead.

While this works, I it's more a workaround.
I think there should be an `eval_ast` function which returns some kind of context where I then can use `call_fn`.

---

Maybe a bit more background helps in case I'm missing something that's already there:
I want to provide optional hooks for my application. My current implementation allows loading of an arbitrary count of scripts where each one can implement logic for any combination of available hooks.

Let's say there are the hooks `on_start` and `on_end`.
So a script `hook_a.rhai` could only implement `on_start`:
```rhai
fn on_start(arg0) { print("a: arg0 = " + arg0); }
```
While a script `hook_b.rhai` could implement `on_end`:
```rhai
fn print_arg1(arg1) { print("arg1 = " + arg1); } }
fn on_end(arg1) { print_arg1(arg1); }
```

Now some script may want to share some logic, e.g. `hook_c.rhai` want's to reuse `print_arg1`. This could be done either by importing `hook_b.rhai` or moving `print_arg1` into a "library" and importing that library.
The imported library could be used in many hook functions, so a global import is definitely wanted.
But on the other hand I want to only call the associated function for each hook, with the lowest possible overhead. So an eval of the complete AST for each hook invocation feels wrong.

**Comment by schungx** [comment]
>  I think there should be an `eval_ast` function which returns some kind of context where I then can use `call_fn`.

I see you point.  You want to be able to use `call_fn` on something that first evaluates the `AST` and then call the function.  Let me see what I can do...

**Comment by schungx** [comment]
OK, what I'll do is to add a boolean parameter to `Engine::call_fn_dynamic` (which is the low-level version of `call_fn`).  That allows you to run the AST before calling the function, and your imported modules should Just Work.

I'll push to master in a bit for you to test out.

**Comment by schungx** [comment]
PR https://github.com/rhaiscript/rhai/pull/363 landed.

**Comment by SWW13** [comment]
Works like a charm, thanks :)

Probably needs a example in the documentation as this could be a semi-common use case.

**Comment by schungx** [comment]
Wonderful!

**Comment by schungx** [comment]
Closing this for now.  Feel free to reopen if you find any problems.
