### ISSUE TITLE
How to run a rhai script from another rhai script ?

### ISSUE THREAD

**Issue by patrickelectric** [rhaiscript/rhai#377]
I would like to call a rhai script from another rhai script in runtime. is it possible ?
Something like:
```
print("Running: " + child_script)
run(child_script)
```
And, having all modules in function of the root script accessible by the child script ?

**Comment by schungx** [comment]
How about wrapping `child_script` into a module?

`import "child_script";` will run `child_script` without creating an alias.

Or you can wrap the code you want into an `init` function, then you can:

```rust
import "child_script" as c;
c::init();
```

**Comment by patrickelectric** [comment]
Thanks, I'll investigate it

**Comment by patrickelectric** [comment]
My initial thought was to execute different modules in runtime, download the necessary rhai from a github repository or a url and using it directly somehow inside the main rhai script

**Comment by schungx** [comment]
In that case, you'd want to write a custom module resolver that resolves Rhai modules from Github, preferably caching it locally via git...

**Comment by schungx** [comment]
@patrickelectric  do you have any more issues with this?

**Comment by patrickelectric** [comment]
In the end I just created a function for the engine that register itself as a function to be used inside the rhai script, thanks!
