### ISSUE TITLE
Add shebang support for rhai script

### ISSUE THREAD

**Issue by patrickelectric** [rhaiscript/rhai#378]
Right now it's not possible to run rhai scripts with shebangs, it's necessary to do a crazy hack with:
`///bin/true; bunch of shell script here to call a program`

**Comment by schungx** [comment]
I wonder why it fails.  Can you post an error log?

**Comment by schungx** [comment]
Ah I get it.  Rhai is choking on the shebang because it is not recognized.

No problem.  I can add it so any shebangs are skipped as comments.

**Comment by patrickelectric** [comment]
Yes, that's the main problem, thanks!

**Comment by schungx** [comment]
I've added shebangs support to the latest master.  Try pulling it to check if you still have problems.

**Comment by patrickelectric** [comment]
works like a charm, thank you very much!

**Comment by patrickelectric** [comment]
Just a quick question, I'm working in an generic rhai script runner with a bunch of function to run in my machine, such as:
```
network::download(file);
system::architecture();
system::running_as_root();
system::free_disk_space();
system::operating_system();
helper::run_command(shell command);
...
```
Is there any project like that around ?
My idea is to use rhai to replace python and others scripts in my personal use for system configuration and setup for my machines, (tmux, git and etc).

**Comment by schungx** [comment]
Not really, but the plumbing is already there.  The plugins system is designed exactly for easy creating of system API's.

In fact, the author of the plugins system originally envisioned a full set of system modules just like what you described, but he no longer has any free time right now.

It gets very clumsy and tedious to register functions one by one when you want to create an entire set of API.

**Comment by schungx** [comment]
Several things to keep in mind when you design you API:

1) Rhai supports overloading, so usually several Rust library functions map to a single function in Rhai.

2) Rhai is dynamic, so sometimes several library functions also map to a single function in Rhai.

3) Rhai does not support async calls.  Therefore, avoid creating async API's.  I/O functions such as file or network will need to be blocking.

**Comment by schungx** [comment]
My suggestion is to create one module per API, then load them into a `StaticFileResolver`.  Then you can simply `import` the modules you need.

**Comment by patrickelectric** [comment]
cool, right now I'm using `register_static_module`, it makes everything much easier.
I'm aiming to provide everything statically to make it portable between my computers, so no external dependency, but I'll take a better look over your tips, thanks for putting this together!
