### ISSUE TITLE
Support to literal string

### ISSUE THREAD

**Issue by patrickelectric** [rhaiscript/rhai#380]
I'm writing shell scripts to be executed inside rhai and missing literal strings make it a bit harder when dealing with double quotes and etc.

**Comment by schungx** [comment]
What is the preferred syntax for literal strings?

For example, Rust has `r#...#" xxxxx "#...#`

Some languages have back-ticks, some have `@" xxxx "`,  some double-up `""` and `''` to be literals within strings.

Some have `""" xxxx """` as multi-line literal strings.

Not difficult to implement, but the trick is to find a good syntax.

**Comment by schungx** [comment]
I have a version that I've put together with:

* Normal strings: `" ... "`
* Normal strings with continuation: `" ... \
                                                            ..."`
* Multi-line literal strings: `\` ... \``

**Comment by patrickelectric** [comment]
Looks perfect!

**Comment by schungx** [comment]
OK, pull from the latest master to check it out.

**Comment by schungx** [comment]
@patrickelectric you may also look at #121 which is an outstanding issue on string interpolation...

**Comment by patrickelectric** [comment]
I just put my 2 cents there, I just tested the master branch here and the backstick is working like a charm for multstring literals, thanks!
