### ISSUE TITLE
Assignment ops and setters

### ISSUE THREAD

**Issue by ThiNei2l** [rhaiscript/rhai#386]
Hello,
i believe i found a bug with assignment operators on custom types.

Initially i expected the assignment operators to be shortcuts, e.g. `a += 2` would mean `a = a + 2`.
But this is obviously not the case. After fiddling around a bit it seems like they just call a setter if the lhs is a custom type.

Consider this toy program
```rust
use rhai::{Engine, Scope};

#[derive(Clone, Debug)]
struct Num(i64);

impl Num {
    fn get(&mut self) -> i64 {
        println!("get {}", self.0);
        self.0
    }
    fn set(&mut self, x: i64) {
        println!("set to {}", x);
        self.0 = x;
    }
}

fn main() {
    let mut engine = Engine::new();
    engine
        .register_type::<Num>()
        .register_get_set("v", Num::get, Num::set);

    let mut scope = Scope::new();
    scope.push("a", Num(10));
    let a = engine.eval_with_scope::<Num>(&mut scope, "a.v = a.v + 2; a");
    println!("{:?}", a);
    let a = engine.eval_with_scope::<Num>(&mut scope, "a.v += 2; a");
    println!("{:?}", a);
}
```

The output is
```
get 10
set to 12
Ok(Num(12))
set to 2
Ok(Num(2))
```

From this it seems like the first eval behaves like one would expect.
The second one only calls a setter, producing the wrong number.

Also:
If the `+=` is not a shortcut but instead derived differently it would be great if this could be documented.
If the custom types are more complex it's not always obvious what functions you need to register for this to work.
(Sorry if i missed it, but i couldn't find this anywhere)

**Comment by schungx** [comment]
Good find.  Let me check it out.

The implementation for op-assignments are a bit tricky, as I was looking for max flexibility.  It first tries `+=`, and if that operator is not defined, it tries using `+` and `=`.  Obviously the fallback is not working for custom types...

**Comment by schungx** [comment]
The bug is found.  Thanks for catching this.

I conveniently omitted the run the op-assignment when applied to a custom type with setters!  LOL!

**Comment by schungx** [comment]
The fix has landed in master.  Please test to see if it works fine for you.

**Comment by ThiNei2l** [comment]
Yes, works now!
Thanks for the fast response.
