### ISSUE TITLE
scripts/README.md needs a little attention

### ISSUE THREAD

**Issue by adsick** [rhaiscript/rhai#396]
### fix instructions
it says:

How to Run
----------

Compile the `rhai-run` example:

```bash
cargo build --example rhai-run
```
but there is no such an example as 'rhai-run', it is a binary in fact. that wouldn't work.
```bash
cargo build --bin rhai-run
```
works as expected

**Comment by schungx** [comment]
Thanks.  I'll fix it.

**Comment by adsick** [comment]
also maybe leave a note about installing the tool like this:
```shell
cargo install --path . --bin rhai-run
```
this allows for quickly accessing rhai-run from the console

**Comment by schungx** [comment]
> also maybe leave a note about installing the tool like this:

Done!
