### ISSUE TITLE
Inserting into arrays

### ISSUE THREAD

**Issue by ThiNei2l** [rhaiscript/rhai#401]
Hello,

i have trouble inserting an element at the start of an array.

```rust
use rhai::Engine;

fn main() { 
    let engine = Engine::new();

    engine.eval::<()>("
        for i in range(-1, 5) {
            let a = [ 1, 2, 3, 4 ];
            a.insert(i, 0);
            print(\"insert at \" + i);
            print(a);
        }
    ").unwrap();
}
```

will yield
```
insert at -1
[1, 2, 3, 0, 4]
insert at 0
[1, 2, 3, 4, 0]
insert at 1
[1, 0, 2, 3, 4]
insert at 2
[1, 2, 0, 3, 4]
insert at 3
[1, 2, 3, 0, 4]
insert at 4
[1, 2, 3, 4, 0]
```

I'm not completely sure what the intended behaviour is, but i'd say probably 0 = start of array and -1 = last position?

**Comment by schungx** [comment]
Yes, zero should be beginning. So it is a bug. I'll fix it.

**Comment by schungx** [comment]
This should now be fixed in the latest master drop.

**Comment by ThiNei2l** [comment]
Thanks for the reply.
An argument of 0 now inserts correctly at the start of the array.
However -1 is not the last position, so we have a jump of two positions between indices 0 and -1:
```
insert at -1
[1, 2, 3, 0, 4]
insert at 0
[0, 1, 2, 3, 4]
insert at 1
[1, 0, 2, 3, 4]
insert at 2
[1, 2, 0, 3, 4]
insert at 3
[1, 2, 3, 0, 4]
insert at 4
[1, 2, 3, 4, 0]
```

**Comment by schungx** [comment]
>  However -1 is not the last position, so we have a jump of two positions between indices 0 and -1:

This is intended.  `-1` always refers to the `last` character, not the `end position`.

`-1` always means `index = length - 1`.

If you want to insert an item to the end, simply do a `push` or `+=`.  Or use insert with a large positive number (above the length of the array).

**Comment by schungx** [comment]
You may also user string interpolation to simplify your code to:

```rust
use rhai::Engine;

fn main() { 
    let engine = Engine::new();

    engine.eval::<()>("
        for i in range(-1, 5) {
            let a = [ 1, 2, 3, 4 ];
            a.insert(i, 0);
            print(`insert at ${i}: ${a}`);
        }
    ").unwrap();
}
```

**Comment by ThiNei2l** [comment]
Ah, ok. Thanks for clearing that up :)
Then everything is ok now.
