### ISSUE TITLE
scripts/function_decl3.rhai error

### ISSUE THREAD

**Issue by adsick** [rhaiscript/rhai#402]
```
11: print(f(100, 5, 2, 9, 6, 32));
          ^ Variable not found: KEY (line 6, position 29) in call to function f @ '\\?\C:\Users\vadim\Desktop\Rust\rhai\scripts\function_decl3.rhai'
```

**Comment by adsick** [comment]
what does line 14 of scripts/loop.rhai
```
export x as foo;
```
does? commenting it makes no difference

**Comment by adsick** [comment]
ah, I get it, this is used in 'module.rhai'

**Comment by adsick** [comment]
scripts/primes.rhai
line 24: i += p;
this does nothing (commenting it changes nothing), looks like values from for loops are well... values, not mutable references

**Comment by schungx** [comment]
> scripts/primes.rhai
> line 24: i += p;
> this does nothing (commenting it changes nothing), looks like values from for loops are well... values, not mutable references

Ah yes.`for` variables are values. You're right this line has no use. It was a left over from the previous version where there was no stepped range and this was a while loop.

Now the stepping is done in the `range` iterator itself

**Comment by schungx** [comment]
> ```
> 11: print(f(100, 5, 2, 9, 6, 32));
>           ^ Variable not found: KEY (line 6, position 29) in call to function f @ '\\?\C:\Users\vadim\Desktop\Rust\rhai\scripts\function_decl3.rhai'
> ```

I can't get this error... Which version are you using? I see it should be the master since there is an automatic global module.

**Comment by adsick** [comment]
Oh, you are right, I am sorry. I had like a couple days old git repo, started exploring its scripts and finding kid-mistakes (like misplaced ``) I reported some of them here, but then I've thought "wait, nobody really didn't fix this before?" checked the repo again and saw, that errors were fixed, but the reported part remained in the issue.

**Comment by adsick** [comment]
I'll continue testing now with the latest version, but I was kinda dissapointed of looking how the scripts from the source repo contain obvious errors (even they get fixed later) why they were uploaded without testing?

**Comment by schungx** [comment]
Just not having enough test coverage, I think that's the reason.  Rhai's standard library has a large number of functions and methods, and it takes a long time to write complete tests for every single one of them...

Notice that I said test coverage, not tests.  There is a test with `insert`, just not with zero position.  This is a perfect case of not adequate test coverage - the tests do not cover all possible inputs groups.

Fixing this probably requires a systematic revision of all the tests - right now they are quite ad hoc.

**Comment by adsick** [comment]
oh, wait, scripts/function_decl3.rhai still does not work error is:
```
11: print(f(100, 5, 2, 9, 6, 32));
          ^ Module not found: 'global' (line 6, position 29) in call to function f @ '\\?\C:\Users\vadim\Desktop\Rust\rhai\scripts\function_decl3.rhai'
```

**Comment by schungx** [comment]
Strange...I get no such error...

Did you use `rhai-run` to run the script?

**Comment by adsick** [comment]
I use ```rhai-run```

yep, that's strange.
I think that I'm using the latest one.

do our scripts are the same? mine has that
```
global::
```
thing in it.

**Comment by adsick** [comment]
Double check: if I just pull a repo with
```shell
git clone [repo_addr.git]
```
(and then ```git pull``` to update it when new things merged)
do I get the 'latest'?
or I need to explicitly mention the branch?

**Comment by schungx** [comment]
> do our scripts are the same? mine has that

Yes, it is the latest addition.  It is called an "automatic global module".  Essentially it captures all the constants declared at root level into a module called `global`.

So you can refer to global constants within functions.

But the error message you got indicates that the `global` module is not recognized, and that indicates probably an older version.

**Comment by schungx** [comment]
Just `git clone` should automatically get you the latest.

`git pull` will update you to the latest.

Are you running via `cargo run --bin rhai-run` or just running the installed version (which may be an older version)?

**Comment by adsick** [comment]
Ok, I get it now, I will update things and check once again. (this issue probably will be closed)

**Comment by adsick** [comment]
after update it works.
