### ISSUE TITLE
multiline statements in repl

### ISSUE THREAD

**Issue by adsick** [rhaiscript/rhai#405]
when trying smth. like
```rhai
rhai-repl> if 4 == 3{ **push enter here**
```
everything just stops and I consider this a wrong behavior. yep, I know, that it wants me to use backward slash, but it at least should not freeze (there may be some important  data in scope)

the same exact happens with for and while statements.

why is this important

when you try to copy a script into your repl, everything works fine **until** it stops on any of _if_, _for_, _while_ statements

**Comment by adsick** [comment]
also just noticed that freeze occurs when doing like so:
```rhai
rhai-repl> if 4 == 3{\
> print("impossible"); **push enter here**
... stops forever ...
```
again this is not desirable

**Comment by schungx** [comment]
Yes, this is yet another bug.  Go, you super bug-smasher!

**Comment by schungx** [comment]
This is now fixed:

https://github.com/rhaiscript/rhai/pull/406

**Comment by adsick** [comment]
error message is better, but simple newline until the block is closed would be even better (imo)

**Comment by schungx** [comment]
This is already supported via literal strings: `` ` ... ` `` where you can put newlines inside.

But in the REPL, you need to terminate with a `\` in order to continue to the next line, so there is one extra `\` that you need to type.
