### ISSUE TITLE
Unable to build dependencies

### ISSUE THREAD

**Issue by undefinedbuddy** [rhaiscript/rhai#409]
Hi, I tried adding Rhai to my `Cargo.toml` and under both versions set to `0.2` and `*`. However, I encounter the following error:

```
error[E0658]: unions with non-`Copy` fields are unstable
   --> C:\Users\x-x-x\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-1.6.1\src\lib.rs:353:1
    |
353 | / union SmallVecData<A: Array> {
354 | |     inline: core::mem::ManuallyDrop<MaybeUninit<A>>,
355 | |     heap: (*mut A::Item, usize),
356 | | }
    | |_^
    |
    = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information
    = help: add `#![feature(untagged_unions)]` to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `smallvec`.
```

It seems to be originating from the `smallvec` crate. This error occurs without any API being consumed, i.e., just a `cargo run` and it throws. I'm running on `nightly-x86_64-pc-windows-msvc (default)`, if that helps.

**Comment by schungx** [comment]
The minimum compiler version is `1.49`.  Make sure you have an updated compiler version.

**Comment by undefinedbuddy** [comment]
That was the exact issue. Thanks!
