### ISSUE TITLE
error[E0658]: unions with non-`Copy` fields are unstable

### ISSUE THREAD

**Issue by ArunGust** [rhaiscript/rhai#410]
Hi Dears, 

I got below error, 

    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
   Compiling smallvec v1.6.1
   Compiling getrandom v0.2.2
   Compiling num-traits v0.2.14
error[E0658]: unions with non-`Copy` fields are unstable
   --> C:\Users\devuser\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-1.6.1\src\lib.rs:353:1
    |
353 | / union SmallVecData<A: Array> {
354 | |     inline: core::mem::ManuallyDrop<MaybeUninit<A>>,
355 | |     heap: (*mut A::Item, usize),
356 | | }
    | |_^
    |
    = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information

   Compiling ahash v0.7.2
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `smallvec`

To learn more, run the command again with --verbose.
warning: build failed,

**Comment by schungx** [comment]
The minimum version of Rust is `1.49` for this version of Rhai.  You need to upgrade Rust.

**Comment by ArunGust** [comment]
thanks, will check

**Comment by schungx** [comment]
Is it working for you OK?

**Comment by schungx** [comment]
Closing this for now.  Feel free to open another issue if you still have prob.
