### ISSUE TITLE
`DynamicWriteLock` used but not exposed in public API

### ISSUE THREAD

**Issue by CJKay** [rhaiscript/rhai#412]
When creating a dynamic shared between the script and external environment, it's often convenient to create wrapper APIs for functions that do some of the heavy-lifted cast magic:

```rust
struct Context {
    value: rhai::Dynamic,
}

impl Context {
    fn value(&self) -> rhai::INT {
        self.value.as_int().unwrap()
    }

    fn cooldown_mut(&self) -> rhai::dynamic::DynamicWriteLock<rhai::INT> {
        self.value.write_lock::<rhai::INT>().unwrap()
    }
}
```

However, `DynamicWriteLock` is not accessible, despite its use in the public API:

```
error[E0603]: module `dynamic` is private
```

**Comment by schungx** [comment]
I can expose `DynamicReadLock` and `DynamicWriteLock` under the `internals` feature.  Will that work for you?

**Comment by CJKay** [comment]
I feel like this should be part of the standard API, no? As I understand it this is the only way to allow independent mutation of a value both inside and outside of the script, and it does seem a bit strange that this type - returned directly by the standard public API - only be accessible with a feature flag that would otherwise be unnecessary.

The problem I have is not that I cannot lock this value, it's that I cannot move it into its own function because of the accessibility of the return type.

**Comment by schungx** [comment]
True, but so far there is rarely much need to refer to these types...

But you brought in good points.

**Comment by CJKay** [comment]
Perhaps I'm approaching this the wrong way then.

My use-case is that I want to maintain a shared mutable object, as such:

```
struct Game {
    ticks: Arc<RwLock<INT>>,
}

impl Game {
    fn ticks(&self) -> INT {
        self.value.read().unwrap()
    }

    fn ticks_mut(&mut self) -> RwLockWriteGuard<'_, INT> {
        self.value.write().unwrap()
    }
}
```

This `ticks` value is cloned and added to multiple scopes. `Arc<RwLock<T>>`, however, doesn't inherit the operators of `T` in Rhai, so I cannot do `game.ticks += 5` from within my script - I have to use `Dynamic` and allow that to manage the `Arc<RwLock<T>>`, and then do the casting to/from `INT` in getters/setters:

```
struct Game {
    ticks: Dynamic,
}

impl Game {
    fn ticks(&self) -> INT {
        self.value.as_int().unwrap()
    }

    fn ticks_mut(&mut self) -> DynamicWriteLock<INT> {
        self.value.write_lock::<INT>().unwrap()
    }
}
```

Is there a better way?

**Comment by schungx** [comment]
I'm wonder... would this work:

```rust
    fn ticks_mut(&mut self) -> impl Deref_Mut {
        self.value.write_lock::<INT>().unwrap()
    }
```

**Comment by CJKay** [comment]
Ah, yes, I think I've got that going now. One problem I'm having, though, is the lifetime of parameters to `Engine::call_fn`:

```
    {
        let x = 5;

        let _: () = engine.call_fn(scope, ast, "activate", (&x,))
            .with_context(|| format!("couldn't activate ability `{}`", name))?;
    }
```

```
error[E0597]: `x` does not live long enough
   --> src/simulator.rs:158:65
    |
158 |             let _: () = engine.call_fn(scope, ast, "activate", (&x,))
    |                         ----------------------------------------^^---
    |                         |                                       |
    |                         |                                       borrowed value does not live long enough
    |                         argument requires that `x` is borrowed for `'static`
159 |                 .with_context(|| format!("couldn't activate ability `{}`", name))?;
160 |         }
    |         - `x` dropped here while still borrowed
```

Where are these weird lifetime requirements coming from?

**Comment by schungx** [comment]
Rhai doesn't support referenced arguments.  Your `&x` won't live long enough, as the error message says.

You need to clone `x` or use a shared value.

**Comment by schungx** [comment]
> Rhai doesn't understand `Arc<RwLock<T>>`

No it doesn't _by default_, but you can always teach it to understand:

```rust
engine
    .register_type_with_name::<Arc<RwLock<INT>>>("SharedInt"),
    .register_get_set("value",
                |x: &mut Arc<RwLock<INT>>| x.read().unwrap(),
                |x: &mut Arc<RwLock<INT>>, value: INT| *x.write().unwrap() = value
    );
```

**Comment by CJKay** [comment]
I'm using `#[rhai_fn(get = "...")]` today in that snippet above:

```rust
    #[rhai_fn(get = "cooldown", pure)]
    pub fn get_cooldown(this: &mut Ability) -> INT {
        this.cooldown()
    }

    #[rhai_fn(set = "cooldown")]
    pub fn set_cooldown(this: &mut Ability, cooldown: INT) {
        *this.cooldown_mut() = cooldown;
    }
```

The trouble comes when I need to wrap `Ability` in a shared reference and pass it into the script; I have to effectively reimplement the getter/setters for the shared reference type because (unless the `Rc` is inside a shared `Dynamic`) the engine will not forward those calls to the underlying value:

```rust
engine
    .register_type::<Arc<RwLock<global::Ability>>>()
    .register_get_set(
        "cooldown",
        shared_get(global::Ability::cooldown),
        shared_set(global::Ability::cooldown_mut),
    );
```

**Comment by schungx** [comment]
Ah yes.  Sorry for the typo.

Usually this is what people do:

```rust
pub struct Ability {
    a: INT,
    b: bool
}

pub type SharedAbility = Arc<RwLock<Ability>>;

engine.register_type_with_name::<SharedAbility>("Ability");

#[export_mod]
pub mod ability_functions {
    #[rhai_fn(get = "a", pure)]
    pub fn get_a(ability: &mut SharedAbility) -> INT {
        *ability.read().unwrap().a
    }
    #[rhai_fn(set = "a")]
    pub fn set_a(ability: &mut SharedAbility, new_a: INT) {
        *ability.write().unwrap().a = new_a;
    }
    #[rhai_fn(get = "b", pure)]
    pub fn get_a(ability: &mut SharedAbility) -> bool {
        *ability.read().unwrap().b
    }
    #[rhai_fn(set = "b")]
    pub fn set_a(ability: &mut SharedAbility, new_b: bool) {
        *ability.write().unwrap().b = new_b;
    }
}
```

The main variable is named `ability` because it generates the best documentation when you export metadata.

**Comment by CJKay** [comment]
Ah, that seems to work! In any case, I think it'd really cut down on the boilerplate if we could create a shared `Dynamic` directly from the `Shared<_>` value - it'd save on these sorts of workarounds.

**Comment by schungx** [comment]
> I think it'd really cut down on the boilerplate if we could create a shared `Dynamic` directly from the `Shared<_>` value - it'd save on these sorts of workarounds.

Yes it would, but not easily.  There is a variant in the `Dynamic` enum, and it holds a shared `Dynamic`. It would require another variant, like a `Shared<Locked<dyn Variant + Clone>>`.

**Comment by schungx** [comment]
Your use case is probably similar to this usage pattern: https://rhai.rs/book/patterns/singleton.html

**Comment by CJKay** [comment]
Hmm... I just gave this pattern a shot and it looks like what I need, but the example doesn't seem to be totally in sync with what's possible. It suggests pushing the object into the scope as a constant:

```rust
let bunny: SharedBunny = Rc::new(RefCell::(EnergizerBunny::new()));

let mut scope = Scope::new();

// Add the command object into a custom Scope.
scope.push_constant("Bunny", bunny.clone());

engine.consume_with_scope(&mut scope, script)?;
```

But actually, if you try to use a setter on it as it suggests, it complains that constants cannot be modified:

```
thread 'simulator::tests::test' panicked at 'called `Result::unwrap()` on an `Err` value: couldn't activate ability `slice`

Caused by:
    Cannot modify constant ability (line 1, position 1)', src/simulator.rs:242:42
```

I've created a setter here:

```rust
    #[rhai_fn(set = "cooldown")]
    pub fn set_cooldown(this: &mut Shared<Ability>, cooldown: INT) {
        this.write().unwrap().cooldown = cooldown;
    }
```

Which is analogous to the example:

```rust
    #[rhai_fn(set = "power")]
    pub fn set_power(bunny: &mut SharedBunny, on: bool) {
        if on {
            if bunny.borrow().is_going() {
                println!("Still going...");
            } else {
                bunny.borrow_mut().go();
            }
        } else {
            if bunny.borrow().is_going() {
                bunny.borrow_mut().stop();
            } else {
                println!("Already out of battery!");
            }
        }
    }
```

**Comment by schungx** [comment]
Ah.  That's a good find.  This example is old, and I never revised it.  Newer Rhai versions checks against calling a mutating method on a constant.

I'll have to think of a way to get around this...

**Comment by schungx** [comment]
I've fixed the example.  Thanks for spotting this.

It must be called using a pure method instead of a setter: `Bunny.set_speed(50);` instead of `Bunny.speed = 50;`

**Comment by CJKay** [comment]
I think I tried that with no luck, but I'll give it another shot at some point.

**Comment by schungx** [comment]
> I think I tried that with no luck, but I'll give it another shot at some point.

For a method, you can't have `set = "name"` because that would make it a property setter that you cannot call like a method.

**Comment by CJKay** [comment]
Ah, I see. Are there any consequences to just pushing the value as a variable instead of a constant in order to allow that?

**Comment by schungx** [comment]
Not really, except that the scripts are free to _overwrite_ those variables.  If they don't care, I guess you shouldn't need to care.

If you don't push constants, you can keep the setters are property setters and the property assignment style will work fine.  The downside is, as above, your users can overwrite that variable.

**Comment by CJKay** [comment]
Good point. Are there any plans to permit pure setters on constants?

**Comment by schungx** [comment]
> Good point. Are there any plans to permit pure setters on constants?

I'm looking into it.  It was originally forbidden just to make the code easier.  In other words, I cheated.

**Comment by schungx** [comment]
It is not as simple as it looks.  And here is an explanation why:

In Rhai, indexing and dotting form a _chain_.  For example, `a[x][y][z]` refers to a particular memory location within the array `a`.  `m.x.y.z` refers to a particular memory location within the object map `m`.  It does not, for instance, refer to `((m.x).y).z` with intermediaries.  Essentially, a dot/index chain forms an _address_ that indexes into the root object.

If the root object is constant, theoretically no mutations should be allowed all the way down the chain -- because, as I mentioned, the chain is nothing more than an _address_ into the root object.

Then we may have indexers and property getters.  If they are allowed to be `pure`, that means that when these external functions are called, we must always check whether the root object is constant.  And that means carrying the constancy information all the way deep into the chain and into every function call.

And it also means that we cannot simply register a pure function by checking for read-only status of the parameters, because those parameters are simply parts of the root object.  It is entirely possible for the root object to be constant while containing non-constant values.  Therefore, in order to check whether a non-pure function is applied to a constant, we have to pass the root object into every non-pure function call.

This is entirely possible to do, but extremely tedious and frankly speaking of dubious value.  Therefore, it is much simpler to just disallowing assignments to a constant value via a scope chain.

Therefore, you may not realize, but if you do the following right now, it will choke:

```rust
// a1, a2 and a3 are all SharedAbility
const Abilities = [ a1, a2, a3 ];

a1.set_cooldown(42);    // OK!
Abilities[1].set_cooldown(42);   // Not OK! Cannot assign to constant
```

**Comment by schungx** [comment]
Well, what do we know.  Again, using the trick to do constancy checking in the `Dynamic` value solve all the above hairy problems!

Now you can have pure setters and do `ability.cooldown = 42;` without any problem.

**Comment by schungx** [comment]
> Hmm... is `return_raw` not applicable to setters? I have a fallible setter here, but it doesn't seem to be permissible:

You're correct.  This is an oversight.  It has already been fixed and will show up in the next version.

If you can't wait, I've just published `0.3.6` of `rhai_codegen` and you can update your `Cargo.lock` and pull that version.  It should allow fallible setters.

**Comment by CJKay** [comment]
Awesome! I think I've got a relatively clean architecture at this point that seems to work. Thanks for your help!

**Comment by schungx** [comment]
Anything outstanding with this issue?

**Comment by CJKay** [comment]
@schungx Nothing else - I don't need this anymore but I'll leave it up to you to decide whether this is still a good idea.

**Comment by schungx** [comment]
Well, I'm exposing it under `internals` for now, unless there is more call for exposing it publicly in the future.

Close this for now.
