### ISSUE TITLE
Excluding `now` from the WASM buid?

### ISSUE THREAD

**Issue by rckprtr** [rhaiscript/rhai#426]
My WASM hosting container does not allow the import `now` from `env`.  Is there a way to disable `now` completely as it wont be something I will use or not allow Rhai to have that `import` in my wasm?

`(import "env" "now" (func $now (type $t15)))`

The build command Im using is `cargo build --target wasm32-unknown-unknown`

**Comment by chaosprint** [comment]
Hello, how do you solve this issue? Thanks.
