### ISSUE TITLE
implementing From for Dynamic<serde_json::Value>?

### ISSUE THREAD

**Issue by jasongoodwin** [rhaiscript/rhai#428]
Hello, 

I see that serde_json is a dependency under certain conditions - I'm wondering if you might be open to me implementing From for Dynamic<T: Value> if serde_json is enabled? This allows for the Union enum to interop with the serde_json::Value container. It might allow some better encapsulation if people don't want to couple their code to the Dynamic type too heavily - can use the serde_json Value and flip them `into()` Dynamics.

Let me know what you think - just an idea I'm having as I have some code in my codebase to deal with this but it would be really nice if From was implementing this right in Rhai. I can make a PR if you think it's a good idea but understand if it's not.

**Comment by schungx** [comment]
Appreciate a PR!

**Comment by jasongoodwin** [comment]
Okay thanks - I'll think about it a bit and when I have a nice clean solution I'll contribute it back. 
Thanks for the insights.

**Comment by schungx** [comment]
@jasongoodwin   any progress on this?

**Comment by jasongoodwin** [comment]
Hello! I'm definitely going to get to this, the project we're working on is focusing on some other areas currently, but I'll be returning here shortly and will nail this down.

**Comment by schungx** [comment]
As a matter of fact, it seems like it is already possible to deserialize a `Dynamic` into `serde_json::Value`:

```rust
let value = json!({ "a": "b" });
println!("value: {value:?}");

let result: Dynamic = serde_json::from_value(value).unwrap();
println!("result: {result:?}");

let value2 = serde_json::to_value(&result).unwrap();
println!("value2: {value2:?}");
```

**Comment by schungx** [comment]
OK, closing this for now.

**Comment by jasongoodwin** [comment]
Hey sorry, just saw notifications from this. I had a bit of an unexpected pivot and haven't been on github much until more recently. Thanks for looking at this!

**Comment by schungx** [comment]
Feel free to reopen if you find that it doesn't do what you intend.
