### ISSUE TITLE
map indexing

### ISSUE THREAD

**Issue by fatbrain** [rhaiscript/rhai#429]
Hi,

Ran into this problem today:

```
let k = #{ name: "foo" };
let m = #{};
let key = k.name;
m[k.name] = 123;
```

Produces an error: `Data type is incorrect: map (expecting string)`.

If I change the indexer from `k.name` to `key` it works as expected.

**Comment by schungx** [comment]
Thanks for catching this.  This is a bug.

Strange thing is that, I remember fixing this a while back.  Must have regressed.

And I'll check why it wasn't picked up by the tests.

**Comment by schungx** [comment]
This is fixed.

Please pull from https://github.com/rhaiscript/rhai to test.

**Comment by fatbrain** [comment]
Worked like a charm, thanks for the quick fix.

Cheers

**Comment by schungx** [comment]
I'll push out a `1.0.1` in a bit with this fix.
