### ISSUE TITLE
add `_with_scope` for custom syntax

### ISSUE THREAD

**Issue by fatbrain** [rhaiscript/rhai#431]
I have a situation where I'm using custom syntax, `grab "foo.ext" as m { print(m); };` where I want to "expose" m when evaluation the `$block$`, today there's only a `eval_expression_tree`, would be useful if there was also a `eval_expression_tree_with_scope` so I can expose the `m` variable within the `$block$`.

**Comment by schungx** [comment]
You don't have to.

You can `context.scope_mut().push("m", ...);` to add a variable to the current scope, `eval_expression_tree`, then `context.scope_mut().rewind(old_size)` to remove the variable.

`let old_size = context.scope().len()` to get the size of the scope to rewind to.

**Comment by fatbrain** [comment]
Lovely, thanks.
