### ISSUE TITLE
Scope keeps unused values

### ISSUE THREAD

**Issue by inferrna** [rhaiscript/rhai#432]
This code
```rust
    let mut engine = Engine::new();
    let mut scope: Scope = Scope::new();
    engine.eval_with_scope::<()>(&mut scope,r#"
        let x = 1;
    "#
    ).unwrap();
    engine.eval_with_scope::<()>(&mut scope,r#"
        let x = 2;
    "#
    ).unwrap();
    engine.eval_with_scope::<()>(&mut scope,r#"
        let x = 3;
    "#
    ).unwrap();
    scope.iter().for_each(|s| println!("{:?}", s));
```
produces
```
("x", false, 1)
("x", false, 2)
("x", false, 3)
```
I.e. scope keep each value assignment that might lead to memory leakage especially in case with periodic script run (which is actually my case).

**Comment by schungx** [comment]
This is intended. Rhai takes from Rust. New variables of the same name will _shadow_ existing variables of the same name.

Therefore you can always `pop` a variable off and you get the previous, shadowed variable.

To set the value of an existing variable, omit the `let`.

**Comment by schungx** [comment]
Come to think of it... maybe it would be nice to add a `var` declaration which means: if variable doesn't exist, crate it, otherwise set the existing variable.

Similar to the differences between `var` and `let` in JavaScript...

**Comment by schungx** [comment]
An example will be added to The Book on enabling the `var` statement via a custom syntax.
