### ISSUE TITLE
Cannot use the `[]` operator immediately after calling a member function

### ISSUE THREAD

**Issue by koute** [rhaiscript/rhai#435]
This works:

```rust
let array = [1].map(|x| x + 1);
print(array[0]);
```

This doesn't work:

```rust
print([1].map(|x| x + 1)[0]);
```

```
EXCEPTION: Function not found: map (array, Fn) (line 4, position 11)
```

**Comment by schungx** [comment]
Hhhmmm.... strange. `map(array, Fn)` should exist.  Let me check it out.

**Comment by schungx** [comment]
Hhhmmm.... strange. `map(array, Fn)` should exist.  Let me check it out.

**Comment by schungx** [comment]
Yes, this is a bug.  It triggers whenever you have a method call followed by an indexing.

Good catch.

**Comment by schungx** [comment]
Version `1.0.2` is now out with a fix to this bug.

**Comment by koute** [comment]
Thanks!
