### ISSUE TITLE
How to implement custom type namespacing?

### ISSUE THREAD

**Issue by plasticartsshow** [rhaiscript/rhai#438]
When implementing a custom type, it's possible to give it a custom pretty-print name:
```
engine.register_type_with_name::<A::B>("B_Alias");
```

Is it possible to use a namespaced name to prevent global namespace pollution?

```
engine.register_type_with_name::<A::B>("A::B_Alias");
engine.register_type_with_name::<C::B>("C::B_Alias");
```

### Why:
A proc macro generates similar modules based on user specifications. Each module must contain structs having predetermined type names. 

It may be useful to have structs from two generated modules marshalled into `rhai` at once. Right now, the solution is to instantiate different engines for each - the module generation also creates a `get_engine` function to do this. 

Thanks for your hard work.

**Comment by schungx** [comment]
Yes, `register_type_with_name` simply takes any string as name, so you can put anything there.

**Comment by plasticartsshow** [comment]
Ok. Thank you.
