### ISSUE TITLE
try .. catch (err) compilation fails inside anonymous functions

### ISSUE THREAD

**Issue by tgascoigne** [rhaiscript/rhai#441]
Hello,

I've noticed that when attempting to use `try .. catch (err)` inside an anonymous function, I get an error whilst compiling the AST:
```
Variable not found: err
```

Here's a minimal reproduction which fails to compile on the playground:
```
// Works fine
fn foo() {
    try {
        print(42/0); 
    } catch (err) {
        print(err);
    }
}

// Variable not found: err
let bar = || {
    try {
        print(42/0); 
    } catch (err) {
        print(err);
    }
};

foo();
bar.call();
```

Manually declaring `err` inside of the function seems to work around the issue:
```
// Works fine
let bar = || {
    let err = "";
    try {
        print(42/0); 
    } catch (err) {
        print(err);
    }
};
```

But i've also noticed some wierd behavior with variable lookups producing incorrect values, I'm unsure whether this is a related issue or not but I was unable to reproduce outside of functions with try/catch:
```
fn foo(x) {
    let err = "";
    let y = "test2";
    print(err); // ""
    try {
        print(42/0); 
    } catch (err) {
        print(err); // "test2"
    }
};

foo("test1");
```

Version: `rhai = { version = "1.0.2", features = ["sync"] }`

**Comment by schungx** [comment]
Good catch!

**Comment by schungx** [comment]
A new release is out that fixes this bug.

**Comment by tgascoigne** [comment]
That was fast! Thank you :)
