### ISSUE TITLE
Passing a trait object to Rhai-registered function

### ISSUE THREAD

**Issue by curldivergence** [rhaiscript/rhai#444]
Hello, I'm trying to make something resembling `Singleton Command` pattern from the Rhai book, but I actually have multiple Rust-allocated objects, and want to manipulate them from a Rhai script.
One of the parts of my setup is a trait FooTrait and multiple structs Foo1, Foo2, etc. that implement it. Also I have Rhai functions defined in Rust as follows:
```
rhai_engine.register_fn("make_foo1", move |name: String| {
    Rc::new(RefCell::new(Foo1 { name }))
});
rhai_engine.register_fn("make_foo2", move |name: String| {
    Rc::new(RefCell::new(Foo2 { name }))
});
```
so that I can produce FooTrait trait objects from a script.
And the difficult part is that I also have a Rust type Bar, which needs to store a vector of FooTrait trait objects, and this vector has to be filled using Rhai method `.add_foo(...)` that would add a FooTrait object created by one of the `make_foo*` functions to that vector.
I've implemented this method along the lines of
```
rhai_engine.register_fn(
            "add_foo",
            move |bar: Rc<RefCell<Bar>>,
                  foo: Rc<RefCell<dyn FooTrait>>| {
                  bar.borrow_mut().add_foo(foo)
            },
        );
```
but unfortunately when I try to call this method, the script fails to be executed due to the error
```
ErrorFunctionNotFound("add_foo (alloc::rc::Rc<core::cell::RefCell<Bar>>, alloc::rc::Rc<core::cell::RefCell<Foo1>>)
```
Unfortunately I have no idea where to go from here, so could you help me with this, please? :)

Thank you!

**Comment by schungx** [comment]
`RefCell<Foo1>` is not the same type as `RefCell<dyn FooTrait>`.  This aspect of Rust is easy to mess up.  Rust does _not_ have polymorphism as per OOP style.

```rust
trait Foo: Clone {    // Notice it must be Clone to use with Rhai
    ...
}

type BarObject = Rc<RefCell<Bar>>;
type FooTraitObject = Rc<RefCell<dyn Foo>>;

engine.register_type_with_name::<FooTraitObject>("FooObject")
      .register_type_with_name::<BarObject>("BarObject")
      .register_fn("make_foo1", |name: &str| Rc::new(RefCell::new(Foo1 { name: String::from(name) } as dyn Foo)))
      .register_fn("make_foo2", |name: &str| Rc::new(RefCell::new(Foo2 { name: String::from(name) } as dyn Foo)))
      .register_fn("add_foo", |bar: BarObject, foo: FooTraitObject| ...);
```

**Comment by curldivergence** [comment]
Hi @schungx, thanks a lot for your reply :) And yep, I understand that `RefCell<Foo1>` cannot be casted to `RefCell<dyn FooTrait>` since `RefCell` doesn't provide an indirection, just a borrow counter.
But in my case those refcells are behind `Rc`'s, so I believe that trait object coercion should work, like in the example below (which basically sums up what I'm trying to achieve using Rhai): https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7172975b8f346c29ef03017702854feb

Thank you!

**Comment by schungx** [comment]
Unfortunately it won't work the way you want it, because for Rust, `RefCell<Foo1>` and `RefCell<dyn FooTrait>` are different types.

Rust's `impl Trait` syntax allows you to monomorphize different _versions_ of the same overloaded function based on its actual argument type (meaning that `add_foo(foo1)` and `add_foo(foo2)` compiles to two separate copies of the function `add_foo`.

Rhai, due to its dynamic nature, has no such feature.  You must overload by specifying these monomorphized versions separately.  

Meaning that you must have both `add_foo(Foo1)` as well as `add_foo(Foo2)`.  In the backend they may map to the same generic function, which is how it is commonly done with Rhai:

```rust
fn add_foo<T: FooTrait>(bar: &mut Bar, foo: T) { ... }

engine.register_fn("add_foo", add_foo::<Foo1>)
      .register_fn("add_foo", add_foo::<Foo2>)
      .register_fn("add_foo", add_foo::<dyn FooTrait>);
```

Also see: https://rhai.rs/book/rust/generic.html

**Comment by curldivergence** [comment]
Thank you for your help, but I believe we're still on different pages :) Since you're talking about monomorphization I believe you're referring to static dispatch, and I'm interested in dynamic dispatch via vtables and `dyn Trait` (which I demonstrated in the first playground example) - I believe that since I'm receiving not just `RefCell<T>`, but `Rc<RefCell<T>>`, I should get the indirection that is required for dynamic type resolution.

Thanks!

**Comment by schungx** [comment]
Alternatively, if you do it via a plugin module, it is even simpler:

```rust
#[export_module]
pub mod FooModule {
    fn add_foo<T: FooTrait>(bar: &mut Bar, foo: T) { ... }

    #[rhai_fn(name = "add_foo"]
    pub fn add_foo1(bar: &mut Bar, foo: Foo1) { add_foo(bar, foo); }

    #[rhai_fn(name = "add_foo"]
    pub fn add_foo2(bar: &mut Bar, foo: Foo2) { add_foo(bar, foo); }

    #[rhai_fn(name = "add_foo"]
    pub fn add_foo_trait(bar: &mut Bar, foo: FooTraitObject) { add_foo(bar, foo); }
}
```

**Comment by schungx** [comment]
> I believe that since I'm receiving not just RefCell<T>, but Rc<RefCell<T>>, I should get the indirection that is required for dynamic type resolution.

OK, I see you're trying to use a function that takes a trait object.  You must remember there is no automatic coercion for an object (say `Foo1`) to convert to a trait object (say `dyn FooTrait`).  You must provide that conversion function (aka the `make_trait_object` function in my previous comment).

Alternatively, you may simply store everything as trait objects, for example:

```rust
engine.register_fn("make_foo1", || Rc::new(RefCell::new(Foo1 { ... } as dyn FooTrait)));
```

**Comment by curldivergence** [comment]
```You must remember there is no automatic coercion for an object (say Foo1) to convert to a trait object (say dyn FooTrait).```
I might be wrong, but isn't this automatic coercion the thing that happens in the snippet below? :)
```
impl Bar {
    fn add_foo(&mut self, foo: Rc<RefCell<dyn FooTrait>>) {
        self.foos.push(foo);
    }
...
}
...
let x: Rc<RefCell<Foo1>> = Rc::new(RefCell::new(Foo1("abc")));
let mut bar = Bar { foos: vec![] };
bar.add_foo(x);
```

**Comment by schungx** [comment]
Sorry, I mean there is no automatic coercion _for Rhai_, since Rhai does not internally know about generics or traits...

**Comment by curldivergence** [comment]
Ahh, now I get it :)
Thank you very much for your kind help, I'll proceed with one of the ways you've mentioned above.

**Comment by schungx** [comment]
Try this without `Box`:

```rust
engine.register_type_with_name::<Rc<RefCell<dyn FooTrait>>>("FooTraitObject")
      .register_fn("make_foo1", || Rc::new(RefCell::new(Foo1 { ... })) as Rc<RefCell<dyn FooTrait>>);
```

**Comment by curldivergence** [comment]
Yep, storing trait objects like you've suggested seems to work, thanks a lot for help :)
