### ISSUE TITLE
A ExprTooDeep error is returned for what seems to be a simple function

### ISSUE THREAD

**Issue by Hodkinson** [rhaiscript/rhai#447]
It works fine in the playground, but when I run this test locally I see

`Err(ParseError(ExprTooDeep, 5:39))`

```rust
#[test]
fn complexity_issue() {
    let script = r#"
        fn my_function(env,input){
            if input.arg == "SOMETHING" {
                let args = #{
                    "key": env.lookup("name")
                };
            }
        }
    "#;

    let mut engine = Engine::new();

    let result = engine.compile(script);
    println!("{:?}", result);
    assert!(result.is_ok());
}
```

**Comment by schungx** [comment]
Yes, in debug mode, Rust stack usage is heavy and functions cannot be nested deeply without overflowing the stack. That's why, under debug, the max expression nesting limit is set to a low number by default 

You can relax that via `Engine::set_max_expression_levels`

**Comment by Hodkinson** [comment]
I see, thank you, doing `engine.set_max_expr_depths(0, 0);` fixed it for me. Is that (effectively) what is used by default in release?

**Comment by schungx** [comment]
Release builds have a much larger limit, but by default there is a limit.

https://rhai.rs/book/safety/max-stmt-depth.html  has the numbers.
