### ISSUE TITLE
add rhai code example to readme

### ISSUE THREAD

**Issue by gbaranski** [rhaiscript/rhai#449]
Hi, I was doing some research on embeddable programming languages, and I've found rhai, but i can't find any example of how this language looks like, it'd be great to add one, [gluon](https://github.com/gluon-lang/gluon#examples) adds examples such as hello world or fibonacci

**Comment by gbaranski** [comment]
> There is a folder `examples` where you'd find some standard Rust samples such as hello world. In the `scripts` folder you'd find standard Rhai sample scripts such as Fibonacci.

Yes, but shouldn't that be in README to make it easier for new users?

**Comment by schungx** [comment]
There is also... you know... and entire Book, with a link in the `README`...

**Comment by gbaranski** [comment]
> There is also... you know... and entire Book, with a link in the `README`...

try to put yourself as a someone who makes research on which embedded programming language to use, and want's only languages that are similar to OCaml, so he can easily chose which languages look like OCaml after simply looking through README, without going into subfolders.

yes there's a link to a book, but there are also many other links which makes it harder to notice.
![image](https://user-images.githubusercontent.com/34353640/134035366-e34023e6-cf32-41e5-99c4-93e993f974ee.png)

**Comment by schungx** [comment]
Well, I would say this is quite clear...

![image](https://user-images.githubusercontent.com/661318/134035703-603af52f-2e25-4d79-af84-ff9b4345d379.png)

But you're right.  Probably a sample Rhai script as an example in the `README` would work well to let the user know what kind of language he's looking at...

**Comment by schungx** [comment]
I have added an `Example` section in the `README`, which will go live for later versions.

https://github.com/rhaiscript/rhai/tree/bug-fixes

**Comment by gbaranski** [comment]
Looks great, thanks
