### ISSUE TITLE
Question about usage in WASM. Could Rhai be faster than using Javascript?

### ISSUE THREAD

**Issue by kaphula** [rhaiscript/rhai#460]
Hey,

The manual states that: 

```
WebAssembly (WASM) Build
It is possible to use Rhai when compiling to WebAssembly (WASM). This yields a scripting engine (and language) that can be run in a standard web browser.

Why you would want to is another matter... as there is already a nice, fast, complete scripting language for the the common WASM environment (i.e. a browser) – and it is called JavaScript.

But anyhow, do it because you can!

When building for WASM, certain features will not be available, such as the script file API’s and loading modules from external script files.

```

As far as I understand, when it comes to WASM and Javascript, it is encouraged to **not** write programs where the Javascript code calls frequently the WASM code, but instead calls to WASM should be few and far between in a sense that we pass WASM little information, WASM does the heavy calculations and returns the small results back to Javascript.

Let's say we have a program that is written in Rust and it uses Rhai runtime as a dependency to interpret/compile Rhai scripts dynamically during the execution of the Rust application. When the Rhai scripts are run within the Rust application, they make make calls to the underlying native Rust application and also interact with it frequently otherwise. 

Then we compile this whole program to WASM, run it in browser and feed it Rhai scripts dynamically during the WASM program's runtime. Does not this mean that the whole scenario stays neatly in the realm of WASM all the time (except when we feed the program new scripts) and thus it would be in theory faster than writing a program where we would use plain Javascript to make those calls to the underlying Rust application's functions?

**Comment by schungx** [comment]
Not really sure about the runtime speed, as JavaScript is _wicked_ fast these days with JIT's and all.  JavaScript is at least 10x faster in raw processing speed than Rhai.

Whether that would be offset by WASM calling overheads is something that I haven't benchmarked...  But I admit, if all the scripted functions are short and do simple processing, acting as event handlers, then the calling overhead probably overwhelms the script processing time.

Another reason why I suggest using JavaScript is that, when you're working in a browser environment (i.e. if your WASM system is primarily intended to be run in a browser), or in a node.js environment (i.e. if your WASM will be loaded by node to make certain things faster), then you'd do your users a huge favor by not requiring them to learn yet another scripting language.  All your users will be right at home with JavaScript.

If your intended usage of the WASM is for multi-O/S, multi-environment, client+server side integration etc. then it makes sense to have everything stay in Rust.  In such a case, the browser is merely one of the many environments.

**Comment by schungx** [comment]
Any further issues with this?

**Comment by kaphula** [comment]
All good on my part. It can be closed. Thanks!
