### ISSUE TITLE
Behavior of Rust object map in case property doesn't exists

### ISSUE THREAD

**Issue by rikvdkleij** [rhaiscript/rhai#470]
Hi,
Do you want to consider to raise an error instead of returning `()` when getting a property of a map which doesn't exist? This makes it easier to understand why running a script has failed. Especially when the name of the property is mentioned in the error message. In the current solution it goes wrong further in a script because it doesn't expect a `()`.
Or make this behavior an engine configuration option?

**Comment by schungx** [comment]
The choice is based on the assumption that most maps do not store `null` values as proper values.  A property with `null` value is probably equivalent to one storing a single boolean (say `false`) as its value, thereby avoiding the `null` in the first place.

**Comment by zarik5** [comment]
I think we should follow the principle of least surprise. In this case I would consider accessing a undefined field an error. But there are other options:

* In case of undefined field keep the current behavior when using the indexing syntax (`["foo"]`) but throw an error in case of field syntax (`.foo`)
* When accessing a field of a undefined field, use a special case error that warns that the parent field might not exist.

**Comment by schungx** [comment]
Problem is, if we change this behavior, we'd be breaking existing code.

Maybe a special feature flag...  something like `fail_on_invalid_map_prop`...

**Comment by schungx** [comment]
The next version will have `Engine::set_fail_on_invalid_map_property` which controls whether an exception is raised when an invalid property is accessed on an object map.

**Comment by rikvdkleij** [comment]
@schungx Thanks!

**Comment by schungx** [comment]
If you turn that option on, all invalid properties on object maps will throw, even using index syntax.

You'll need to gate the access with `if "prop" in map { map.prop }`
