### ISSUE TITLE
Enrich NativeCallContext with caller information

### ISSUE THREAD

**Issue by jannschu** [rhaiscript/rhai#476]
Hi,

I am trying to implement something like rust's `assert_eq!` to allow some testing in rhai. To do that my current idea is to implement a function `assert_eq` in rust and then use exceptions hoping that the rust implementation would have access to the stacktrace for example. But I did not manage to get the position and source of the calling function for nice error messages, for example by using NativeCallContext. Could the position and source of the caller be added to NativeCallContext?

Another option to have something like `assert_eq!` probably is to use a custom syntax/parser and then store the source and position, or to add something like assertions to rhai itself.

**Comment by schungx** [comment]
It can be easily added to `NativeCallContext`.  I'll try it out to see if it makes the context object larger.

**Comment by schungx** [comment]
`NativeCallContext::position()` will be added to the next minor release version.
