### ISSUE TITLE
Custom operators don't work as described in documentation

### ISSUE THREAD

**Issue by rikvdkleij** [rhaiscript/rhai#477]
When I define a custom operator as described here https://rhai.rs/book/engine/custom-op.html#example
it works as `foo(x,y)` and not as `x foo y`.  Does infix only work for primitive types?

Also what are the rules for the name of symbol operators? When I define an operator as e.g. `#<` or `<#` it doesn't work because the parser fails to see both characters.

**Comment by schungx** [comment]
It seems to work in the doc test for `Engine::register_custom_operator`...

Custom operators must be identifiers; they cannot be symbols, as symbols are parsed in the tokenizer and if it is not recognized, it throws a parsing error early.

**Comment by schungx** [comment]
You don't seem to have registered a function called `lt`...

You need something like: `engine.register_fn("lt", |a: DateTime, b: DateTime| a < b)`

**Comment by rikvdkleij** [comment]
Sorry, I forgot to paste that code:
```
    engine.register_fn(
        "lt",
        |x: chrono::DateTime<Utc>, y: chrono::DateTime<Utc>| x.cmp(&y).is_lt(),
    );
```

It is working but not in infix notation.

I will take a look to the plugin solution but I don't think that's solved my issues. Seems more an issue with the parser.

**Comment by schungx** [comment]
What is the actual error you got?

BTW, you should probably register the actual type instead: `engine.register_type_with_name::<chrono::DateTime<Utc>>("DateTime")`

**Comment by rikvdkleij** [comment]
This is working:
```
        let script_content = indoc::indoc! {r#"
            if lt(cs_start_datetime,new_dt(2021,11,1,0)) {
                "foo"
            } else {
                "bar"
            }
        "#};

```

This gives error `ParseError(MissingToken("{", "to start a statement block"), 1:22)`:
```
        let script_content = indoc::indoc! {r#"
            if cs_start_datetime lt new_dt(2021,11,1,0) {
                "foo"
            } else {
                "bar"
            }
        "#};
```

> BTW, you should probably register the actual type instead: engine.register_type_with_name::<chrono::DateTime<Utc>>("DateTime")

Has no effect

**Comment by schungx** [comment]
I have a test version short of using `chrono` and it works just fine:

```rust
let mut engine = Engine::new();

// Register a custom operator called `lt` and give it
// a precedence of 160 (i.e. between +|- and *|/).
engine.register_custom_operator("lt", 160).unwrap();

// Register a binary function named `lt`
engine
    .register_fn("new_num", || 5 as INT)
    .register_fn("lt", |x: INT, y: INT| x < y);

let mut scope = Scope::new();
scope.push("x", 3 as INT);

assert_eq!(
    engine.eval_with_scope::<INT>(&mut scope, "if x lt new_num() { 42 } else { 123 }")?,
    42
);
```

**Comment by rikvdkleij** [comment]
And does it still works if you define parameters for `new_num`?

**Comment by schungx** [comment]
Yes it does work with parameters...

Considering that it failed at parsing, meaning that Rhai doesn't think `lt` is a custom operator.  That's very strange, if you register that operator before running the script.

**Comment by rikvdkleij** [comment]
Yes, it's defined before running the script.

**Comment by rikvdkleij** [comment]
O wait, I made the assumption that registering custom functions is only needed for evaluation of a script but it is also needed for the compilation....

And besides that I implemented datetime support after I did the refactor in which compilation was separated from the evaluation. Otherwise I noticed this issue during the refactor and was put directly on the right track for finding the cause.

Anyway, my mistake, did a wrong assumption. Thanks for your help!

**Comment by rikvdkleij** [comment]
So the confusing part is that everything was still working except for the definition of the custom operator.

**Comment by rikvdkleij** [comment]
Btw, I will change my solution and use your suggested plugin solution.

**Comment by schungx** [comment]
Glad for you to get it working.  The custom operator is actually only needed during parsing as the compiler desugars it to an actual function call.  It is no longer required in evaluation.
