### ISSUE TITLE
Support constants in `switch`

### ISSUE THREAD

**Issue by RazrFalcon** [rhaiscript/rhai#482]
Currently, I'm getting `Expecting a literal expression`.

**Comment by schungx** [comment]
What did you put in the case?  `switch` cases can only be literal constants.

**Comment by RazrFalcon** [comment]
```rust
const VALUE = 42;

switch 5 {
    VALUE => print("yes"),
    _ => print("no").
}
```

**Comment by schungx** [comment]
It doesn't support constants in the case position... It must be a literal, like `42`.

**Comment by RazrFalcon** [comment]
This is a pretty serious limitation. I have to use `if` for such cases.

**Comment by schungx** [comment]
You may do standard text processing on the script to replace the constants with values...

Just a thought.

**Comment by schungx** [comment]
But really, it is probably simpler to do:

1) Collect all lines starting with `const`
2) Run those lines as a script into `eval_with_scope`, getting values for the constants
3) Iterate the scope, for each constant value, replace `$(name)\s*=>\s*` with the actual value inside the script
4) Evaluate the modified script as normal

**Comment by RazrFalcon** [comment]
I will think about this "solution" 😄

**Comment by schungx** [comment]
An alternative is to simply embed a minimal C preprocessor (like https://github.com/Kestrer/gpp) into your project.  Then you can really do some wacky things:

```c
#define VALUE 42

switch 5 {
     VALUE => print("yes"),
    _ => print("no")
}
```

**Comment by schungx** [comment]
Closing this for now.  Putting a `wont fix` for now.
