### ISSUE TITLE
How to use `from_dynamic` with serde for structs with values that use `Option<...>`?

### ISSUE THREAD

**Issue by trbodev** [rhaiscript/rhai#483]

**Comment by schungx** [comment]
`from_dynamic` takes a `Dynamic` value and deserializes it into a target type.

However, it doesn't deserialize into `Option<...>` because there is no uncertainty here.  The `Dynamic` _always_ has a value, therefore technically speaking the `Option` is always `Some`.

**Comment by schungx** [comment]
In the up-coming version, `from_dynamic` can now deserialize into `Option` fields.
