### ISSUE TITLE
Integer f64 printed as Zero in string interpolation

### ISSUE THREAD

**Issue by germolinal** [rhaiscript/rhai#485]
First of all, thanks for this project! I am loving it. Rhai is becoming the main language for the API in my [www.simplesim.tools](www.simplesim.tools) project.

Now, I encountered an issue: **If a function returns an f64 that happens to be an integer, the `print` command will print it as Zero** (this also happens when returning an `f32` and using the `f32_float` feature... It does not happen when returning integers). 

You can replicate this bug as follows:

```rust
// main.rs

use rhai::{Engine, EvalAltResult};

fn some_long_calculation( ) -> f64 {
    99.
}

fn some_other_long_calculation( ) -> i64 {
    99
}

fn main() -> Result<(), Box<EvalAltResult>>
{
    let mut engine = Engine::new();
    engine  .register_fn("some_long_calculation", some_long_calculation)
            .register_fn("some_other_long_calculation", some_other_long_calculation);

    let ast = engine.compile("
        let a = some_long_calculation();
        print!(`a is ${a}`);
        print!(`a + 0.2 is ${a + 0.2}`);

        let int_a = some_other_long_calculation();
        print!(`int_a is ${int_a}`);
        print!(`int_a + 0.2 is ${int_a + 0.2}`);
    ")?;
   
    engine.eval_ast(&ast)?;


    Ok(())
}

```
This prints the following

```
a is 0.0
a + 0.2 is 99.2
int_a is 99
int_a + 0.2 is 99.2
```

This is my `Cargo.toml` file

```toml
# Cargo.toml
[package]
name = "rhai_test"
version = "0.1.0"
edition = "2018"

[dependencies]
rhai = { version = "1.1.2" }
```

**Comment by schungx** [comment]
Oops.  That's a bug. It'll be fixed.  Thanks!

**Comment by schungx** [comment]
Closing this as the fix will appear in the next release.
