### ISSUE TITLE
Importing deep structure

### ISSUE THREAD

**Issue by zarik5** [rhaiscript/rhai#486]
Currently, `rhai::serde::to_dynamic()` can convert any structure with `#[derive(serde::Serialize)]` to a dynamic object and also its fields when they are trivially convertible to rhai objects (like primitives and maps). The problem arises when the structure you want to convert contains other unknown structures; within rhai their type becomes `()`. Is there a way to recursively convert all fields? An acceptable alternative would be to use an intermediate JSON form, but right now even using `serde_json::to_value()` I encounter the same problem.

**Comment by schungx** [comment]
Essentially, to be serializable with `serde`, everything must break down into fields, or lists, or maps, or tuples etc.  So it should automatically work for types that are serializable.

I believe `enum`s are serialized as a string and tuples are serialized to a list.

Can you give an example of a type that cannot convert to a `Dynamic`?

**Comment by zarik5** [comment]
Uh, this was totally my fault. I converted the field names to camel case with serde, but not all, and I got it mixed up when writing rhai code. What threw me off is the error I got. For example if I have `#{ "myField1": #{ "myField2": bool } }`, if I write `my_object.my_field1.myField2` (notice the wrong casing), I get the error:
`Unknown property 'myField2' - a getter is not registered for type '()'`

**Comment by schungx** [comment]
Yes, that's correct.  A non-existent field in a map returns `()`.  This is similar to JavaScript, but is a source of contention.  

https://github.com/rhaiscript/rhai/issues/470 describes this issue.
