### ISSUE TITLE
Comparing Number with Function

### ISSUE THREAD

**Issue by Kaiser1989** [rhaiscript/rhai#491]
I noticed some strange comparison behaviours:

```rhai
print(2.0 > 1.0);
print(2.0 > 1);
print(2.0 > true);
print(1.0 > |x| x + 1);

// but:

print(1.0 + |x| x + 1);

```
output:
```
Waiting for Web Worker to finish loading...
Running script at 2021-11-23T08:23:38.133Z

[PRINT] true
[PRINT] true
[PRINT] false
[PRINT] false

EXCEPTION: Function not found: + (f64, Fn) (line 3, position 11)
Finished at 2021-11-23T08:34:42.034Z
```

where comparing any number with booleans or closures returns false (would expect an error, function not found).

**Comment by schungx** [comment]
This is by design.

Comparison operators (i.e. `==`, `!=`, `<`, `<=`, `>`, `>=`), when applied to different types, will always return `false` (`!=` returns `true`), unless that specific operator has been defined with a custom function.

This is to simplify a lot of code, for example:

```
let x = get_some_value();

if x == 42 { ... }     // defaults to false for all non-numeric values of x, e.g. ()
```

**Comment by Kaiser1989** [comment]
Perfect, Thanks for your fast answer!

This means i have to add some comparators now ;)

**Comment by schungx** [comment]
If it is just for printing you can do:

``print(`1.0 ${|x| x + 1}`);``
