### ISSUE TITLE
Weird behavior of `map` after update to 1.2

### ISSUE THREAD

**Issue by PolyMeilex** [rhaiscript/rhai#492]
Hi, I recently updated rhai in [my project](https://github.com/PolyMeilex/Anodium/tree/master/src/config)
And now the array map fn is acting really weird:
### Example:
- `outputs` is an array of `OutputConfig` structs

```rs
fn arrange_outputs(outputs) {
    let output_x = 0 + 1;

    print("abc:" + output_x);

    outputs.map(|output| {
        print("abc:" + output_x);

        output
    });
    
    outputs
}
```
The output is:
```
abc:1
abc:anodium::config::output::OutputConfig
```

**Comment by schungx** [comment]
That seems to be a bug regarding external variable captures.

**Comment by schungx** [comment]
If you'd like to pull from the `v1.2-fixes` branch here, you can try out the fix.

I'll put out version `1.2.1` in a bit.

**Comment by PolyMeilex** [comment]
Thanks for a quick fix, works like a charm

**Comment by schungx** [comment]
`1.2.1` is now out with this fix.
