### ISSUE TITLE
Panic 'op-assigment operator'

### ISSUE THREAD

**Issue by lroobrou** [rhaiscript/rhai#510]
After bumping rhai from 1.3.0 to 1.4.0, I received a panic when loading some scripts, with the following message.

```thread 'main' panicked at 'op-assignment operator'```

The panic occurs at src/ast/stmt.rs:49:14. I turns out that assignments of the form `var = var + integer` are causing this. Here is an example program that panics with 1.4.0, which runs just fine with 1.3.0.

``` rust
extern crate rhai;

use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let engine = rhai::Engine::new();
    let result: i64 = engine.eval(
        r#"
        let a = 0;
        a = a + 1;  // panics
        a
        "#,
    )?;

    println!("result = {}", result);

    Ok(())
}
```

**Comment by schungx** [comment]
Yes, good catch.  Dunno how this slipped through...

**Comment by schungx** [comment]
`1.4.1` is published which should contain this bug fix, among others.

Thanks for raising this.  Let me know if the new version solves your problem.

**Comment by lroobrou** [comment]
Yes, problem solved. :)
