### ISSUE TITLE
Is there any interpolation function supporting byte type?

### ISSUE THREAD

**Issue by cn-kali-team** [rhaiscript/rhai#522]
- I know there are interpolation expressions for strings.
```javascript
let k = "rhai";
let s = `hi ${k}`;
print(s);
// hi rhai
```
- I have byte type now.
```javascript
let body = "ssssssssssssssssssssss".as_bytes();
print(body);
// [7373737373737373 7373737373737373 737373737373]
let body = `aaa ${body}`;
print(body);
// aaa [7373737373737373 7373737373737373 737373737373]
```
- I have to extract the byte data in the string with regular expression in rust, and then convert the string into bytes and splice it.
```rust
let s = "aaa [7373737373737373 7373737373737373 737373737373]";
do_something()
let mut all_bytes: Vec<u8> = Vec::new();
all_bytes.push_str("aaa");
all_bytes.push_byte(rhai_blob_string_to_bytes("[7373737373737373 7373737373737373 737373737373"));

```
- Or whether there is illegal UTF-8 conversion of byte data into string without loss, that is, it is better to use string to represent byte data in script.

**Comment by schungx** [comment]
You need to realize that interpolation is nothing but syntactic sugar for the `+` operator.

Therefore, the following are equivalent:

```rust
let s = `hi ${k}`;    // <- this

let s = "hi " + k;    // <- is equivalent to this
```

So for your bytes, you can easily do:

```rust
let body = "ssssssssssssssssssssss".as_bytes();

let body = "aaa ".as_bytes() + body;
```

**Comment by schungx** [comment]
I'll add a `to_blob` method to strings in the next version so you don't have to define your own `as_bytes`.

**Comment by schungx** [comment]
However, after reading your post more carefully, it seems that you want to use strings interpolation but with BLOB's that are UTF-8 data.  You may want built-in support for building strings out of UTF-8 bytes other than sub-strings.

If this is what you want, then there is no such built-in support right now.  It would not be difficult to add though, but the trick is to do it yourself by defining the `+` operator for the operand types `string` and `Blob`.  Something like:

```rust
engine.register_fn("+", |s: ImmutableString, b: Blob| {
    if b.is_empty() {
        s
    } else if s.is_empty() {
        String::from_utf8_lossy(&b).into_owned().into()
    } else {
        let mut s = s.to_string();
        let b = String::from_utf8_lossy(&b);
        s.push_str(b.as_ref());
        s
    }
});
````

**Comment by cn-kali-team** [comment]
> 

However, illegal strings will be lost.
I just want to convert a string to bytes, not bytes to strings, because converting from bytes to strings will lose data.

**Comment by cn-kali-team** [comment]
If it is the previous format, I can easily convert the string of blob to byte type without loss, but the current compact format is changeable, and I have to write more code to convert it back to byte type.
```javascript
let body = "ssssssssssssssssssssss".to_blob();
print(body);
// [115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
// [7373737373737373 7373737373737373 737373737373]
```
How to hook byte type ` to_ string() ` method. I want to restore the previous format when converting bytes to strings, not compact.
In this way, I can better separate the connection between string and byte.

**Comment by schungx** [comment]
Not very sure what you want.

Which print format do you want?

Or you may give a more concrete example.

**Comment by cn-kali-team** [comment]
like this
```javascript
// [115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
```
This is the previous format, but now it is changed to compact. I wonder if there is a way to get the previous format by hook without modifying the source code and using patch.
```javascript
let body = "ssssssssssssssssssssss".to_blob();
print(body);
// [115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
let body = `aaa ${body}`;
print(body);
// aaa [115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
```

**Comment by schungx** [comment]
Ah, OK.  Actually, I've changed the source code for special treatment for BLOB's, so in the future

```rust
let body = `aaa ${body}`;
print(body);
// aaa sssssssssssssssssssssssss
```

In order to get the previous compact version, you can do:

```rust
let body = `aaa ${body.to_string()}`;
print(body);
// aaa [7373737373737373 7373737373737373 737373737373]
```

For the non-compact version, you need to change the BLOB into an array of integers.  For example:

```rust
let x = [];
for ch in body { x += ch; }
let body = `aaa ${x}`;
print(body);
// aaa [115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
```

**Comment by cn-kali-team** [comment]
> In the future, you can do:
> 
> ```rust
> let body = `aaa ${body.to_array()}`;
> print(body);
> // aaa [115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
> ```
In the interpolation expression, I don't know whether the `body` is of byte type, so I can't judge whether it needs to be used `to_ array() ` method.
Can I add ` engine.set_blob_format() `, allowing developers to choose the format to return.
```rust
let mut engine = Engine::new();
engine.disable_symbol("eval");
engine.set_blob_format("array");
```
- and
```javascript
let body = `aaa ${body}`;
print(body);
// aaa [115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
```

**Comment by cn-kali-team** [comment]
I've done it
```rust
#[export_fn]
pub fn blob_to_array_string(bytes: Blob) -> String {
    format!("{:?}", bytes)
}
#[export_fn]
pub fn string_to_bytes(string: &str) -> rhai::Blob {
    string.as_bytes().to_vec()
}

engine.register_fn("to_string", blob_to_array_string);
engine.register_fn("to_blob", string_to_bytes);
```

```javascript
let body = "ssssssssssssssssssssss".to_blob();
let body = `aaa${body}`;
print(body);
aaa[115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]
```
- I can also prefix blob when converting
```rust
#[export_fn]
pub fn blob_to_array_string(bytes: Blob) -> String {
    format!("blob:_prefix:{:?}:blob_suffix", bytes)
}
```
```javascript
let body = "ssssssssssssssssssssss".to_blob();
let body = `aaa${body}`;
print(body);
aaablob:_prefix:[115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115]:blob_suffix
```

**Comment by schungx** [comment]
Yep, that's the way to do it.  You can just "monkey patch" Rhai's built-in functions to suit your own.  No need for new options.
