### ISSUE TITLE
register a function in rhai that uses/binds a variable from rust

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [rhaiscript/rhai#523]
I am very new to rust, so maybe this is just me being a newbie.

I want to do something like this:

```rust
fn get(url: &str) {
    // Some code to send a http GET to the given url
}

fn build_engine() {
    let target_url = load_url_from_config();
    let mut engine = rhai::Engine::new();
    engine.register_fn("get_target_url", || get(target_url));
}
```

But it seems, that I cannot pass closures to register_fn:

```
the trait `RegisterNativeFunction<_, ()>` is not implemented for ...
```

But how can I get the variable "target_url" into the call if `get_targer_url` (rhai function) whithout having to pass it in rhai?

**Comment by cn-kali-team** [comment]
https://rhai.rs/book/rust/functions.html

**Comment by schungx** [comment]
You'll need to give more info, such as what is the return type of `get`... is it `Clone`?  Rhai needs to work with data types that are `Clone`, for example.

Also, functions for `register_fn` must be `'static`, so maybe you need to do: `move || get(target_url)`

**Comment by schungx** [comment]
Closing this for now.  Feel free to reopen if you have any problems.
