### ISSUE TITLE
Anonymous function are not exported by modules.

### ISSUE THREAD

**Issue by ltabis** [rhaiscript/rhai#526]
Hello,

I discovered that anonymous function seems to, even though they are de-sugared as functions, not exported by modules.
Here is an example:

```rust
// --- main.rs

use std::str::FromStr;

fn main() {
    let mut engine = rhai::Engine::new();

    engine.set_module_resolver(rhai::module_resolvers::FileModuleResolver::new_with_path(
        "./scripts",
    ));

    let ast = engine
        .compile_file(std::path::PathBuf::from_str("./scripts/main.rhai").unwrap())
        .expect("failed to compile");

    engine.eval_ast::<()>(&ast).unwrap();
}

// --- scripts/external.rhai

export const anonymous_func = |param| print(param);

fn normal_func(param) {
    print(param)
}

// --- scripts/main.rhai

import "external" as external;

external::normal_func(42);
external::anonymous_func.call(42);
```

calling the following script returns:
```
42
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorFunctionNotFound("anon$3135e461af3cc922 (i64)", 4:26)', src/main.rs:14:33
```

`anon$3135e461af3cc922` "should" have been exported by the module, since it [de-sugars into a function](https://rhai.rs/book/language/fn-anon.html?highlight=anonymous%20fun#anonymous-functions).

Could it be that `anon$3135e461af3cc922` is under the "external" namespace, and to be able to call it the function pointer should be something like this:
```rust
Fn("external::anon$3135e461af3cc922")
```

I guess anonymous functions not being exported could be normal behavior, but I couldn't find anything specified in the documentation. 
Did I missed something ?

**Comment by schungx** [comment]
Hhmmm... this can be a bug.  The function should be exported.

**Comment by ltabis** [comment]
Thank you for your quick response ! I know it is a weird use case, I'll find another way to achieve what I want in the meantime. Have a good day.

**Comment by schungx** [comment]
OK, it'll throw a runtime error then.

**Comment by schungx** [comment]
This will be in effect for the next release.  Thanks for catching this.

Closing for now.
