### ISSUE TITLE
parser panics when namespace qualifying a method call 

### ISSUE THREAD

**Issue by tcheinen** [rhaiscript/rhai#528]
an expression like "a.b::c()" makes the parser panic with the error `thread 'main' panicked at 'internal error: entered unreachable code: method call should not be namespace-qualified', /home/sky/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.5.0/src/parser.rs:1971:13`; 

```rust
fn main() {
    let engine = rhai::Engine::new();
    engine.run("a.b::c()");
}
```

**Comment by schungx** [comment]
Yes, this is a known bug.

It'll be fixed in the next release.

Do you need this urgently?

**Comment by tcheinen** [comment]
I don't; just reporting

**Comment by schungx** [comment]
https://github.com/rhaiscript/rhai/pull/529 fixes this.
