### ISSUE TITLE
Returns the result after string replace

### ISSUE THREAD

**Issue by cn-kali-team** [rhaiscript/rhai#530]
```javascript
let Hostname = "172.17.0.2:8080";
let t = replace("https://HOST/-redux","HOST",Hostname);
print(Hostname);
let tt = "https://HOST/-redux".replace("HOST",Hostname);
print(type_of(tt));
```
- output
```bash
172.17.0.2:8080
()
```
- Expected results, Like Rust
```bash
172.17.0.2:8080
https://172.17.0.2:8080/-redux
```

**Comment by schungx** [comment]
`replace` modifies the string in-place.  So you have to do:

```
let tt = "https://HOST/-redux";
tt.replace("HOST",Hostname);
print(tt);
```

**Comment by cn-kali-team** [comment]
It often requires the string replacement function to be invoked in DSL. Will this function be added in the future?
like:
```javascript
let url = `${BaseURL}/wp-admin/admin-ajax.php?action=${hash::md5(replace("https://HOST/-redux","HOST",Hostname))}`;
```

**Comment by schungx** [comment]
```rust
let url = `${BaseURL}/wp-admin/admin-ajax.php?action=${hash::md5({ let h="https://HOST/-redux"; h.replace("HOST",Hostname); h})}`;
```

**Comment by cn-kali-team** [comment]
Oh, it doesn't meet the code specification.
If there is no built-in function, I will patch it
```rust
#[export_fn]
pub fn replace(string: &str, from: &str, to: &str) -> String {
    let string = string.replace(from, to);
    return string;
}
engine.register_fn("replace", replace);
```
However, there will be more and more patches. I still want the built-in method to return results

**Comment by schungx** [comment]
Yes, you may patch it, and create a new function for the old behavior, for example: `replace_in_place`.

Or you can create a new function for the new behavior (e.g. `replace_new`) and leave the standard function untouched.

**Comment by schungx** [comment]
Yes, you may patch it, and create a new function for the old behavior, for example: `replace_in_place`.

Or you can create a new function for the new behavior (e.g. `replace_new`) and leave the standard function untouched.

**Comment by cn-kali-team** [comment]
So is it considered to support modifying itself and merging the returned results into the built-in method at the same time?

**Comment by schungx** [comment]
> So is it considered to support modifying itself and merging the returned results into the built-in method at the same time?

What I mean is, the standard behavior is unlikely to change for stability reason.

However, it is very easy for you to patch the system, so you can simply do it and not worry about whether the standard library is changed.

If you have many such patches, you simply:

1) Make a plugin module with all the patch functions
2) Create a package from that plugin module
3) Use `Engine::register_global_module` to add that package

So in the future if you have more patches, you just add it to the module and everything else will be automatic.

**Comment by cn-kali-team** [comment]
OK, thanks
