### ISSUE TITLE
How to write Infinity

### ISSUE THREAD

**Issue by Kaiser1989** [rhaiscript/rhai#534]
I searched docs and code but didn't find anything.

Is it possible to write Infinity as number? Currently i'm only able to do it by this math statement:
```
print(1.0 / 0.0)
```

outputs
```
Waiting for Web Worker to finish loading...
Running script at 2022-03-07T11:15:04.027Z

[PRINT] inf

Script returned: ""
Finished at 2022-03-07T11:15:04.031Z
```

**Comment by schungx** [comment]
Well, I wonder why you'd want to...

But you can easily register a function, say `inf()`, that simply returns infinity.

While you're at it, you may want to distinguish between positive vs negative infinity.

**Comment by Kaiser1989** [comment]
Inf, -Inf & NaN...

Maybe someone wants to check against NaN values. Just wondering if there are any build-in functions.

I will register them myself.
THX for your fast answer!

**Comment by schungx** [comment]
If you just want to test them, there are these functions: https://rhai.rs/book/language/num-fn.html#floating-point-functions
