### ISSUE TITLE
Documentation for Option

### ISSUE THREAD

**Issue by njust** [rhaiscript/rhai#538]
I was searching the rhai.rs/book how to handle optional parameters, but couldn't find something helpful. Should I implement my own option based on the enum [documentation](https://rhai.rs/book/patterns/enums.html#working-with-rust-enums) ?

**Comment by schungx** [comment]
Depends on whether your function is Rust-native or Rhai-based.

For Rhai functions: All parameters are dynamic, so just pass `()` as `None`.  Or: leverage overloading (see below).

For Rust functions: Leverage overloading by registering multiple versions of the same function, some without optional parameters.

**Comment by njust** [comment]
Thanks a lot. The relevant page from the online book is [here](https://rhai.rs/book/language/overload.html?highlight=overload#function-overloading), in case someone else stumbles upon this.
