### ISSUE TITLE
Release 1.6.0 to crates.io

### ISSUE THREAD

**Issue by sunng87** [rhaiscript/rhai#544]
1.5 now builds failed on latest rust nightly:
https://github.com/sunng87/handlebars-rust/runs/5720956450?check_suite_focus=true#step:4:99

The current HEAD has no issue with the nightly build

**Comment by schungx** [comment]
That's strange, as I cannot reproduce the error...

Can you do a `cargo clean` and try again?  Probably a messed up version in `Cargo.lock`...  Or a mismatch in the version of `rhai_codegen`...

**Comment by sunng87** [comment]
The github CI always does clean build. You can checkout handlebars [https://github.com/sunng87/handlebars-rust](https://github.com/sunng87/handlebars-rust) and do `cargo build --all-features`

It's reproducible with latest nightly `rustc 1.61.0-nightly (ab0c2e18d 2022-03-27)`

**Comment by schungx** [comment]
Let me check it out.

Can you check if https://github.com/schungx/rhai builds?  That's my dev repo.

**Comment by schungx** [comment]
On `nightly-x86_64-pc-windows-msvc`

```text
cargo +nightly build --all-features
    Updating crates.io index
  Downloaded rust-embed-impl v6.2.0
  Downloaded rust-embed-utils v7.1.0
  Downloaded cpufeatures v0.2.2
  Downloaded getrandom v0.2.6
  Downloaded sha2 v0.9.9
  Downloaded rust-embed v6.3.0
  Downloaded 6 crates (966.2 KB) in 5.77s
   Compiling proc-macro2 v1.0.36
   Compiling version_check v0.9.4
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.89
   Compiling typenum v1.15.0
   Compiling cfg-if v1.0.0
   Compiling winapi v0.3.9
   Compiling serde_derive v1.0.136
   Compiling cpufeatures v0.2.2
   Compiling autocfg v1.1.0
   Compiling opaque-debug v0.3.0
   Compiling ucd-trie v0.1.3
   Compiling serde v1.0.136
   Compiling maplit v1.0.2
   Compiling static_assertions v1.1.0
   Compiling log v0.4.16
   Compiling once_cell v1.10.0
   Compiling serde_json v1.0.79
   Compiling ryu v1.0.9
   Compiling smallvec v1.8.0
   Compiling itoa v1.0.1
   Compiling quick-error v2.0.1
   Compiling getrandom v0.2.6
   Compiling pest v2.1.3
   Compiling smartstring v0.2.10
   Compiling generic-array v0.14.5
   Compiling ahash v0.7.6
   Compiling num-traits v0.2.14
   Compiling quote v1.0.17
   Compiling pest_meta v2.1.3
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling sha2 v0.9.9
   Compiling winapi-util v0.1.5
   Compiling same-file v1.0.6
   Compiling walkdir v2.3.2
   Compiling rust-embed-utils v7.1.0
   Compiling pest_generator v2.1.3
   Compiling rust-embed-impl v6.2.0
   Compiling rhai_codegen v1.3.0
   Compiling pest_derive v2.1.0
   Compiling rust-embed v6.3.0
   Compiling rhai v1.5.0
   Compiling handlebars v4.2.3-alpha.0 (C:\Git\handlebars-rust)
    Finished dev [unoptimized + debuginfo] target(s) in 56.26s
```

**Comment by schungx** [comment]
OK.  It is with macro hygene changes in nightly.

The very recent nightly changes macro hygene which causes the error.  It has already been fixed, but the fix is not in version `1.5.0`.

Do you need it urgently?  As I was planning to test out `1.6.0` for a bit before releasing it...

**Comment by schungx** [comment]
I'll release `1.6.0` in a bit, which should resolve this hygene error.

**Comment by schungx** [comment]
`1.6.0` has been released.

**Comment by sunng87** [comment]
Thank you!
