### ISSUE TITLE
is there any way to serialize and deserialize rhai ast from and to string?

### ISSUE THREAD

**Issue by OfekShochat** [rhaiscript/rhai#547]
hello! Im trying to cache asts but I don't see any way to do this. I don't think #161 is finished, but idk. is there any standard way of doing this or should I try and take all the info and then reconstruct the ast?
thanks!
ps great project

**Comment by schungx** [comment]
Well, I actually tried something like this in my on fork, in a branch called `ast_serde`.  It is very old though.

https://github.com/schungx/rhai/tree/ast_serde

At half ways, I realized that there really is no point in doing this, as persisting the original script is easier and quicker than generating a string serialization from an `AST`.

Therefore, the standard way is to persist the script text itself (which can be compressed easily if you're really pressed for space).
