### ISSUE TITLE
ErrorFunctionNotFound after updating to v1.6

### ISSUE THREAD

**Issue by OfekShochat** [rhaiscript/rhai#548]
hello again,
```
let mut engine = Engine::new();
engine.register_type::<ContractStorage>();
engine.register_fn("get", ContractStorage::get_segment);
engine.register_fn("set", ContractStorage::set_segment);
engine.on_print(|_| {});
```
this now throws ErrorFunctionNotFound?

**Comment by schungx** [comment]
Can you elaborate?

Such as what script throws the error?

**Comment by OfekShochat** [comment]
```
fn something() {
    storage.get("hello");
}
```
where storage is with type ContractStorage

**Comment by schungx** [comment]
I cannot reproduce the error:

```rust
#[derive(Clone)]
struct Test {
    x: INT,
}

impl Test {
    fn new() -> Self {
	    Self { x: 1 }
	}
    fn get_len(&mut self, string: &str) -> INT {
        string.len() as INT + self.x
    }
}

let mut engine = Engine::new();

engine
    .register_type::<Test>()
    .register_fn("new_test", Test::new)
    .register_fn("get_len", Test::get_len);

assert_eq!(
    engine.eval::<INT>(r#"let a = new_test(); a.get_len("hello")"#)?,
    6
);
```

**Comment by schungx** [comment]
Which function is not found?

`get` or `something`?

**Comment by OfekShochat** [comment]
Get

**Comment by OfekShochat** [comment]
full code on https://gitfront.io/r/ghostway/74ee0920d5a9e421f109e1c4b2567f4b5fec1afa/teral/blob/src/contracts/mod.rs

**Comment by schungx** [comment]
```rust
    fn get_segment(&self, key: &str) -> Dynamic {
```

You can't use `&self` in Rhai.  It must be:

```rust
    fn get_segment(&mut self, key: &str) -> Dynamic {
```

**Comment by OfekShochat** [comment]
aha, cool, thank you so much! can I ask why?

**Comment by schungx** [comment]
> aha, cool, thank you so much! can I ask why?

Limitation in the Rust compiler.

For the Rust compiler, `&T` and `T` are the same, meaning that a single generic type parameter `T` can also refer to references.  A reference is a type.

Therefore, there is no simple way to distinguish between a function taking `&T` vs. one that takes `T`.  There is no way to separate them.

Rust has a "specialization" feature that has been in the works forever and still not stabilized.  It is supposed to resolve this kind of problems.

Incidentally, `&mut T` has no such issue, as `T` cannot represent a `&mut T`.  `&mut T` in Rust is very special - it is invariant.

**Comment by OfekShochat** [comment]
I see, cool!
