### ISSUE TITLE
Function can not be resolved with Dynamic when registering via `Module::set_native_fn`

### ISSUE THREAD

**Issue by soerenmeier** [rhaiscript/rhai#549]
The following code added to tests/modules.rs throws an error:
```rust
#[test]
fn test_module_dynamic() -> Result<(), Box<EvalAltResult>> {
    fn test_fn(input: Dynamic) -> Result<INT, Box<EvalAltResult>> {
        let s = input.into_string().unwrap();
        Ok(s.len() as INT)
    }

    let mut engine = rhai::Engine::new();
    let mut module = Module::new();
    module.set_native_fn("test", test_fn);

    let mut static_modules = rhai::module_resolvers::StaticModuleResolver::new();
    static_modules.insert("test", module);
    engine.set_module_resolver(static_modules);

    assert_eq!(
        engine.eval::<INT>(r#"import "test" as test; test::test("test");"#)?,
        4
    );

    Ok(())
}
```
Error:
```
---- test_module_dynamic stdout ----
Error: ErrorFunctionNotFound("test::test (&str | ImmutableString | String)", 1:30)
thread 'test_module_dynamic' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/test/src/lib.rs:187:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Seems like this is a bug, or is dynamic not supported when using `Module::set_native_fn`?
I'd be willing to make a PR, but would appreciate some guidance where to look.

Thanks for the hard work you have put into rhai.

**Comment by schungx** [comment]
Good catch.

It seems like module functions do not support `Dynamic` parameters.  I'll look into it.

**Comment by schungx** [comment]
Good catch.  It seems like `Dynamic` parameters are not supported for loaded module functions.

Qualified (i.e. called with a path) function calls go through a different code path than non-qualified (i.e. called without a path) function calls.  I'll need to add searching for `Dynamic` parameters to it.

**Comment by schungx** [comment]
> I'd be willing to make a PR, but would appreciate some guidance where to look.

Glad for you to offer, but it seems to be in a tricky position in the code that requires in-depth knowledge of how Rhai works, so it might be better that I fix it.

**Comment by schungx** [comment]
If you'd pull from https://github.com/schungx/rhai  you can try out the fix.

**Comment by soerenmeier** [comment]
Thanks, works great.

**Comment by schungx** [comment]
I'm thinking, since this has been there for so many versions, I'll wait until `1.7` for this fix to land.  You OK with this?

**Comment by soerenmeier** [comment]
Fine by me. Feel free to close this if you want.
