### ISSUE TITLE
Indexers and +=

### ISSUE THREAD

**Issue by markusmoenig** [rhaiscript/rhai#551]
Hi,

great job with this, I am using Rhai in my classical RPG creator Eldiron.com for evaluating expressions and scripts. See attached.

Question: When using Indexers and using them in a script, why does code like

`target["HP"] += 1`

not throw an error ? Because it gets evaluated as

`target["HP"] = 1`

which is different than what is intended.

Thanks,

<img width="1352" alt="Screen Shot 2022-04-14 at 08 26 12" src="https://user-images.githubusercontent.com/10293923/163378343-95c5c17c-424e-454d-84b7-6d57b2a7cf02.png">

**Comment by schungx** [comment]
Using an object map, I can't reproduce the error.

`target["HP"] += `;` is syntactic sugar for `target["HP"] = target["HP"] + 1;`

Are you defining your own indexer functions?  If so, it should "get" the value, and then sets it to the new value...

**Comment by schungx** [comment]
This unit test (in `get_set.rs`) should check what you're looking at:

```
#[test]
fn test_get_set_op_assignment() -> Result<(), Box<EvalAltResult>> {
    #[derive(Clone, Debug, Eq, PartialEq)]
    struct Num(INT);

    impl Num {
        fn get(&mut self) -> INT {
            self.0
        }
        fn set(&mut self, x: INT) {
            self.0 = x;
        }
    }

    let mut engine = Engine::new();

    engine
        .register_type::<Num>()
        .register_fn("new_ts", || Num(40))
        .register_get_set("v", Num::get, Num::set);

    assert_eq!(
        engine.eval::<Num>("let a = new_ts(); a.v = a.v + 2; a")?,
        Num(42)
    );
    assert_eq!(
        engine.eval::<Num>("let a = new_ts(); a.v += 2; a")?,
        Num(42)
    );

    Ok(())
}
```

**Comment by schungx** [comment]
Ah OK, I can reproduce that with a custom indexer.  It seems to be a bug.

**Comment by markusmoenig** [comment]
OK :)

It also has something to do with the type. My variables are f64. When I do

target["HP"] += 1

which should work fine but I get:

Err(ErrorIndexingType("server::gamedata::script::InstanceVariables [string] = i64", 1:7))

When I use 

target["HP"] += 1.0

I get no error and HP is always set to 1.

**Comment by schungx** [comment]
You can pull from https://github.com/rhaiscript/rhai/ to try out the fix.

**Comment by markusmoenig** [comment]
Thanks so much for the quick fix! Works perfect!

You can close this issue at your convenience. Note I have opened up #553 as a follow up feature request.
