### ISSUE TITLE
Convert Decimal with to_int()

### ISSUE THREAD

**Issue by robmarto** [rhaiscript/rhai#561]
Getting error with converting decimal using to_int conversion as specified in https://rhai.rs/book/language/convert.html this should be available.

Toml:

    [dependencies]
    rhai = { version = "*", features = ["sync", "decimal"] }
    rust_decimal = "*"
    rust_decimal_macros = "*"

Code:

    let mut scope = Scope::new();
    let mut engine = Engine::new();
    engine.register_fn("round",Decimal::round_dp);
    scope.push("value", Decimal::from_str("51.34").unwrap());
    
    let result:String = engine.eval_with_scope(&mut scope, 
        "
        let rounded_value = value.round(0);
        let int_value = rounded_value.to_int();
        return switch int_value { 
            0..=10 => `value between 0 and 10`,
            11..=20 => `value between 0 and 10`,
            21..=40 => `value between 0 and 10`,
            41..=60 => `value between 0 and 10`,
            61..=80 => `value between 0 and 10`,
            81..=100 => `value between 0 and 10`
        }"
    )?;

Result:
`Error: ErrorFunctionNotFound("to_int (decimal)", 3:39)`

Workaround is to convert Decimal > to_float > to_int:
`let int_value = rounded_value.to_float().to_int();`

**Comment by schungx** [comment]
Yes, this is an omission.  It will be added in the next version.

In the meantime, it is OK to convert first to float then to int...

**Comment by robmarto** [comment]
Thanks. Closing issue.
