### ISSUE TITLE
access map in a map error

### ISSUE THREAD

**Issue by zhuchuanjing** [rhaiscript/rhai#562]
let obj = #{"age": 9, "id":"who am i", "x-id": #{"nAAawwwwsshame":"zhu", "age": 100}};
log(obj["x-id"]["age"]);

get a error:
ErrorParsing(MalformedIndexExpr("Array or string expects numeric index, not a string"), 5:17)

**Comment by schungx** [comment]
Thanks.  This is a parsing bug.  The fix will land for the next version.

In the meantime, you can use `obj["x-id"].age`

**Comment by schungx** [comment]
Actually, you have flushed out even deeper problems with parsing of indexing expressions that pre-dates the introduction of indexers.  These will all be fixed, thanks to your report.

**Comment by zhuchuanjing** [comment]
thx
