### ISSUE TITLE
is the # symbol nesseary?

### ISSUE THREAD

**Issue by zhuchuanjing** [rhaiscript/rhai#565]
rhai's object define need a magic symbol '#'
it make some strange sense,
is there any possible to remove this # ?

**Comment by schungx** [comment]
Unfortunately it is required, otherwise it requires more than one look-ahead symbol to distinguish between a statement block and an object hash.  In fact, it would require two look-ahead symbols, or go through fire hoops to parse.

```rust
#{ prop : ...
^^ ^^^^
1   2

{ prop : ...
^ ^^^^
1  2
```

**Comment by schungx** [comment]
What don't you like about `#{`, since it is nice and unambiguous.  You can also search for all object literals by searching for this prefix.

One issue is you probably want to parse JSON into Rhai, in which case Rhai has you covered: https://rhai.rs/book/language/json.html

**Comment by schungx** [comment]
Is this issue resolved?
