### ISSUE TITLE
Allow rhai-run to read from stdin

### ISSUE THREAD

**Issue by AlexGustafsson** [rhaiscript/rhai#568]
The rhai-run binary only supports reading from a file specified by path. I'd like to be able to read from stdin. Unfortunately it's not as simple as running `rhai-run /dev/stdin` as I'm targeting WASM. Rust's WASM target does not support reading files from a path.

TLDR; I'd like the following to be true.

```shell
cat scripts/fibonacci.rhai | ./rhai
```

$$
\iff
$$

```shell
./rhai scripts/fibonacci.rhai
```

**Comment by schungx** [comment]
That should be quite simple to change by ripping out the file loading code and replacing by a read-to-EOF from stdin.

I would encourage you to give it a shot yourself.

However, there are a few things to also consider: firstly, are you sure WASM supports reading from stdin?  Second, you may need a different way to print error messages or return the result if it is WASM.

**Comment by AlexGustafsson** [comment]
I quickly rewrote `rhai-run.rs` to read from stdin instead of files and stdin with WASM (WASI really) does seem to work fine. I'm using an embedded Wasmer runtime with parts of the WASI layer implemented on my own. I'll see if I can get a working PR together.

Stdout and stderr already work fine, so there shouldn't be any need for a different mechanic to print things.

**Comment by schungx** [comment]
> I'll see if I can get a working PR together.

I suggest putting the relevant sections of code under a feature gate (e.g. `stdin` or something).
