### ISSUE TITLE
Strict variable mode does not take custom modules into account

### ISSUE THREAD

**Issue by cortesi** [rhaiscript/rhai#574]
I'm evaluating rhai for a project where an API will be exposed as a set of native functions contained in modules. It's important for usability that I be able to check that the functions invoked by users exist when scripts are compiled. Strict variable mode seems to be what I need, but it doesn't appear to take modules registered on the engine into account.

```rust
use rhai::{Engine, EvalAltResult, Module};

fn main() -> Result<(), Box<EvalAltResult>> {
    let mut engine = Engine::new();
    let mut m = Module::new();
    m.set_var("foo", 3);
    engine.register_static_module("test", m.into());

    // When this line is uncommented, compilation (and execution) succeeds.
    // With this line, compilation fails with ModuleUndefined("test")
    engine.set_strict_variables(true);

    engine.compile(r#"print(test::foo)"#)?;
    Ok(())
}
```

**Comment by schungx** [comment]
Ah.  OK.  This sounds reasonable.

BTW, strict variables mode only checks that the module exists (i.e. `tests` exists).  It does not check that `test::foo` exists.  That is because, depending on the module resolver, variables may be dynamic.

**Comment by cortesi** [comment]
Is there a supported way for me to make sure both the module and the function exists, perhaps with a static module resolver? At this point I'm considering walking the AST to do this, but it feels like there should be something more direct. I imagine this is a common usability issue given rhai's application domain.

**Comment by cortesi** [comment]
Let me clarify what I'm up to. As I mentioned in the other ticket, the application here is a terminal UI framework. Apps are composed of nodes in a tree (widgets, basically). Nodes expose commands, and these commands are in turn exposed through modules to scripts, which drive key bindings, mouse interactions and general scriptability. All the commands and therefore the contents of the native modules are known up front, and are static for the life of the application. I don't expect these scripts to ever be complicated - a few lines with maybe a few conditionals, and definitely no user-defined modules. 

So, say the user has a script that calls `list::next()` - for usability, I need to be able to check whether the function exists or not at compile time, so I can error out early. At this point, it seems that walking the AST to pull out invocations and check them might be what I have to do. However, it might make sense for rhai to have a restricted mode, like the strict variable mode, where the entire module surface is assumed to be fixed at the point of compilation, and where all invocations are checked at compile time. Many use cases where rhai needs to serve as a language for light-weight bindings could benefit from this.

**Comment by schungx** [comment]
@cortesi   if you pull from https://github.com/schungx/rhai you can try out the fix.
