### ISSUE TITLE
How to handle Error gracefully

### ISSUE THREAD

**Issue by youngzhaozju** [rhaiscript/rhai#588]
Hey,

Is there any possible way to make rhai script to handle errors from rust function gracefully? 
Something like the anyhow feature in py03: https://pyo3.rs/main/doc/pyo3/anyhow/index.html

Thank you!
Regards,
Yang

// ------------ Example ---------------
fn main() -> Result<(), Box<EvalAltResult>> {
    #[derive(Debug, Clone)]
    struct TestStruct {
        x: i64,
    }

    impl TestStruct {
        pub fn new() -> Self {
            Self { x: 1 }
        }
        pub fn update(&mut self) {
            self.x += 1000;
        }

        **// ------ I want to return like this to let the rhai script know that there is something wrong returned from this function.--------**
        pub fn calculate(&mut self, data: i64) -> **anyhow::Result<**i64**>** {
          **return Ok(**  self.x * data **)**
        }
        pub fn get_x(&mut self) -> i64 {
            self.x
        }
        pub fn set_x(&mut self, value: i64) {
            self.x = value;
        }
    }

    let mut engine = Engine::new();

    engine
        .register_type_with_name::<TestStruct>("TestStruct")
        .register_fn("new_ts", TestStruct::new)
        .register_fn("update", TestStruct::update)
        .register_fn("calc", TestStruct::calculate)
        .register_get_set("x", TestStruct::get_x, TestStruct::set_x);

    #[cfg(feature = "metadata")]
    {
        println!("Functions registered:");

        engine
            .gen_fn_signatures(false)
            .into_iter()
            .for_each(|func| println!("{}", func));

        println!();
    }

    let result = engine.eval::<i64>(
        "
            let x = new_ts();
            x.x = 42;
            x.update();
            x.calc(x.x)
        ",
    )?;

    println!("result: {}", result); // prints 1085764

    Ok(())
}

**Comment by schungx** [comment]
How about this: https://rhai.rs/book/rust/fallible.html

**Comment by youngzhaozju** [comment]
It's great!!!
Thank you again!
