### ISSUE TITLE
Accepting integer and float at once

### ISSUE THREAD

**Issue by AcrylicShrimp** [rhaiscript/rhai#603]
Hello! I'm trying to add a rust function that accepts 4 float(f32)s. The problem is, the Rhai does not allow callers to put integers instead of floats. I think it is weird, because they look very similar.

```rhai
import "mk" as mk;

let color1 = mk::color::create(1, 0, 1); // It's not work, because the numbers are integers.
let color2 = mk::color::create(0., 0., 1.); // This one will work.
```

I know that they are different. But it's almost not possible to provide all of type combinations. And, there are many cases that using both types without separating them strictly is useful.

So, is there a wrapper type for numeric types, or a way to write my own one? Maybe should I just use `Dynamic`? If I should use `Dynamic`, how can I perform type conversion on it?

Thank you!

**Comment by schungx** [comment]
That would be a problem.  In this regard, Rhai is similar to Rust in that integers and floats are two distinct data types and do not mix.  Those who are used to JavaScript would be annoyed.

Using `Dynamic` is an option.  Just use `value.is::<INT>()` and `value.is::<FLOAT>()` to check the type.  To extract the values, use `value.as_int().unwrap()` and `value.as_float().unwrap()`.

**Comment by AcrylicShrimp** [comment]
Good advice! I think I can use macros to automate those things. But still think that it would be great if I can take control how actual Rust types can be converted from the Rhai's one.

**Comment by schungx** [comment]
If you're using macros, you can simply just register eight versions for 3 parameters (or 16 versions for 4 parameters).  It is not too bad.  Use macros to do conversion from int to float on the correct parameters.

**Comment by AcrylicShrimp** [comment]
Oh, I see. Should we close this issue? Or let it as-is for new-feature? What do you think?

**Comment by schungx** [comment]
You can close this for now.  Thanks!

**Comment by schungx** [comment]
> If you're using macros, you can simply just register eight versions for 3 parameters (or 16 versions for 4 parameters). It is not too bad. Use macros to do conversion from int to float on the correct parameters.

A macro can use a recursive sub-macro to process the parameters:

```rust
// Assume `process_arg!` takes one parameter and expands it into two versions
process_arg!(x, process_arg!(y, process_arg!(z)));
```
