### ISSUE TITLE
macro for inlining rhai?

### ISSUE THREAD

**Issue by cmccomb** [rhaiscript/rhai#606]
I've been thinking about a macro that would help to inline rhai. Something like this:
```rust
macro_rules! rhai {
    () => {};
    ($($t:tt)+) => {
        {
            let engine = rhai::Engine::new();
            engine.eval(
                concat!(
                    $(
                        stringify!($t), " "
                    ),+
                )
            ).unwrap()
        }
    };
}
```

And usage would look something like this:
```rust
fn main() {
    use rhai::INT;
    let x: INT = rhai!(
        fn call_me() {      
            return 3;
        }
        let result = call_me();
        result
    );
    println!("{x}");
}
```

Pros:
1. Inline rhai easily

Cons
1. No easy way that I can see to add packages (`rhai-rand` and `rhai-sci`)

Would something like this be valuable?

**Comment by schungx** [comment]
It would be rather restricted... usually in these kind of macros, it is not easy to include external types.  For example, the user may have imported `rhai` under another module name, and the macro would break if it assumes `rhai::Engine`.  One way is to require importing a prelude from `rhai` which already contains `Engine`.

Also, I believe we can call this macro with `{}` instead of `()`, so it might be nicer to do:

```rust
use rhai::*;

fn main() {
    let x: INT = rhai! {
        fn call_me() {      
            return 3;
        }
        let result = call_me();
        result
    };
    println!("{x}");
}
```

**Comment by schungx** [comment]
It does remove the need to create an `Engine`, but considering that it really takes one line:

```rust
let x: INT = Engine::new().eval(script).unwrap();
```

I am not sure whether it provides any material benefit other than hiding the `Engine` itself.

**Comment by cmccomb** [comment]
I hadn't thought of the one line version that you provided! That's obviously much more robust.

**Comment by schungx** [comment]
Do you think I should provide the functions directly from the `rhai` namespace?

**Comment by cmccomb** [comment]
I've thought about this concept a bit more today and I don't think there's a strong need. Just my perspective though!

**Comment by schungx** [comment]
Anyhow, I see that it doesn't really hurt, so I just added them.  ;-)

**Comment by cmccomb** [comment]
Yay!!
