### ISSUE TITLE
A link in the README.md is invalid.

### ISSUE THREAD

**Issue by Yusuto** [rhaiscript/rhai#607]
A relatively minor thing, I'm opening this issue, in order to ask, if this is rather a bug to be fixed in The Rhai Book, or in this README.

The invalid link is `https://rhai.rs/book/engine/optimize.html`, what I think the link wants to point to is `https://rhai.rs/book/engine/optimize/index.html`, but then, many of the other links don't need an `index.html`, such as `https://rhai.rs/book/language/numbers.html`, so I'd assume this is rather a bug that concerns The Rhai Book?

The quick-fix would of course be just change `https://rhai.rs/book/engine/optimize.html` to `https://rhai.rs/book/engine/optimize/index.html`, but fixing that issue in The Rhai Book seems like the more complete solution.

**Comment by Yusuto** [comment]
Actually, looking through the README.md a bit more and clicking some links (which dear me should have done before opening the issue), there are a few more that lead to 404-pages, but seem to have obvious targets that exist within the book, just under a different URL. Should they all just be corrected to the new URLs, or is it more clean to take a closer look at The Rhai Book to see if any URLs (such as `https://rhai.rs/book/engine/optimize/index.html`) are ›incorrect‹?

**Comment by schungx** [comment]
Yes, I moved stuff from the Book around and probably forgot to update the url links in the `README`!  Good catch!

**Comment by schungx** [comment]
PR https://github.com/rhaiscript/rhai/pull/608 fixes the URL's in the `README`.
