### ISSUE TITLE
Registering Indexers with NativeCallContext argument

### ISSUE THREAD

**Issue by makspll** [rhaiscript/rhai#620]
I believe this is possible via registering a plugin, but not via the raw engine API, the type signature of all indexer registering functions does not allow a NativeCallContext argument

**Comment by schungx** [comment]
You're right.  I should rework the types allowed.  Right now indexers and getters/setters do not allow for `NativeCallContext`.

**Comment by makspll** [comment]
Hmm I see, is there any workaround I can use, short of defining a plugin (I have to do this in a trait method with a generic type) I can use for now ?

**Comment by schungx** [comment]
You can use the `register_fn_raw` API for now?

**Comment by makspll** [comment]
Do indexers get a special function name, or do the types solely determine if a function is an indexer ?

**Comment by schungx** [comment]
Or alternatively, you can just register these: `index$get$` for get indexers and `index$set$` for set indexers.

Just register them as normal functions under this name and it should work fine...

The API functions are simply wrappers that register under these names.

**Comment by makspll** [comment]
perfect! I wasn't sure, but it seemed like this would be the case!

**Comment by schungx** [comment]
This is the implementation of `register_indexer_get`:

```rust
self.register_fn("index$get$", get_fn)
```

**Comment by makspll** [comment]
That should be me sorted then, thanks for the quick response!

**Comment by schungx** [comment]
The latest drop should have resolved this issue.  Thanks for catching this.
