### ISSUE TITLE
Fallible Iterators

### ISSUE THREAD

**Issue by makspll** [rhaiscript/rhai#621]
I am finding myself trying to implement fallible iterators but it seems that since `EvalAltResult` does not implement Clone, it's not possible to have `Result<T,Box<EvalAltResult>>` as the associated `Item` type, would fallible iterators be something you'd consider adding?

Another solution might also be adding an `Error` variant to the `Union` type, then I could have my type be `Dynamic` instead.

As a motivating example, my iterators are for an abstraction over `Vec<T>` pointers essentially, I iterate over a `ScriptRef` struct which is a pointer to the T element, and then convert these to `Dynamic` structs in the iterator which is a fallible process due to the presence of `RwLocks`. 

Actually, I suppose I could also do the conversion while creating the iterator as a whole, but that would require possibly panicking inside of `IntoIterator`

**Comment by schungx** [comment]
Well, not in the original design, where iterators are not intended to be fallible.  But you're right - there is no reason for them not to be.

But that means that the iterator really should be `dyn Iterator<Item = Result<Dynamic, Box<EvalAltResult>>>`...

**Comment by schungx** [comment]
An alternative is to map all errors to `()` (essentially `null`)... then you can just break when you encounter one.  That is probably more idiomatic for Rhai...

**Comment by schungx** [comment]
Actually, it turns out it is really easy to add, so I just added it.

PR https://github.com/rhaiscript/rhai/pull/622

**Comment by makspll** [comment]
Amazing work! This will make my life much easier :D

**Comment by schungx** [comment]
I you can pull from the master repo for the time being, this will go into the next major version.

**Comment by makspll** [comment]
When are you planning on releasing the next major bump ?

**Comment by schungx** [comment]
If necessary I can put up a `1.9.1`...

**Comment by makspll** [comment]
Basically, I will probably be releasing a version within a couple days to a week, but I can just pull out stuff with this functionality into a separate branch and merge it back when you release

**Comment by schungx** [comment]
Why don't you give me a ping when you're ready to release, then I'll just release `1.9.1` to coincide with yours.

**Comment by schungx** [comment]
> and the CustomType trait is an absolute God send btw!

Glad you like it!  This is courtesy of a PR from @tguichaoua.

My new drop will also include `is_result_iterable` for you to register a fallible iterator within `CustomType`.

**Comment by makspll** [comment]
Sure that works, will ping you!

>Glad you like it! This is courtesy of a PR from @tguichaoua.
>My new drop will also include is_result_iterable for you to register a fallible iterator within CustomType.

Oh that's brilliant, it's really nice since it puts the implementation under a "type nest" which is really clean + it lets you do blanket implementations which is really cool!
