### ISSUE TITLE
Cannot reach a function that defined in non-entry module from Rust

### ISSUE THREAD

**Issue by AcrylicShrimp** [rhaiscript/rhai#626]
Hello!

I'm trying to call a Rhai closure from Rust. I have two Rhai script files. The `entry.rhai` is the only file evaluated by Rust.

`entry.rhai`
```rhai
import "utils/fps-counter" as FPSCounter;
```

`utils/fps-counter.rhai`
```rhai
mk::Event::Update::listen(|event| {
    print("called");
});
```

The problem is, Rhai runtime is unable to reach the registered closure.

```
Function not found: anon$5ea4915a2a21b372 (mk::script::api::event::lifecycles::Update)
```

But it works well if I move the function call of `mk::Event::Update::listen` to `entry.rhai`.

`entry.rhai`
```
mk::Event::Update::listen(|event| {
    print("called");
});
```

```
called
called
called
...
```

I'm calling that closure like below:

```rust
struct CompiledModule {
    ast: AST,
    scope: Scope<'static>,
}

pub struct ScriptManager {
    engine: Engine,
    module: Option<CompiledModule>,
}

impl ScriptManager {
    pub fn compile(&mut self, script: impl AsRef<str>) -> Result<()> {
        let scope = Scope::new();
        let ast = self
            .engine
            .compile_into_self_contained(&scope, script)
            .with_context(|| "failed to compile the entry script")?;

        self.module = Some(CompiledModule { ast, scope });
        Ok(())
    }
    
    pub fn call<R>(&self, f: &FnPtr, args: impl FuncArgs) -> Result<R>
        where
            R: Clone + Send + Sync + 'static,
    {
        let module = if let Some(module) = &self.module {
            module
        } else {
            return Err(anyhow!("no entry script compiled"));
        };
    
        f.call(&self.engine, &module.ast, args)
            .map_err(|err| {
                println!("err: {}", err);
                err
            })
            .with_context(|| "failed to call the function")
    }
}
```

Any idea on this problem? What should I check?

Thank you as always!

**Comment by schungx** [comment]
Does it work if you do not compile it into a self-contained AST?

Like loading the modules dynamically.

**Comment by AcrylicShrimp** [comment]
I tried the below list for compilation with no luck.

- `compile`
- `compile_with_scope`
- `compile_into_self_contained`

**Comment by schungx** [comment]
That is quite strange because loading the modules from files should capture all the closures and local functions.

Do you have a custom module resolver?

**Comment by AcrylicShrimp** [comment]
Yes I have, but I fall-backs to FileResolver. Here' the code:

```rust
struct MkModuleResolver {
    mk_module: Shared<Module>,
    file_module_resolver: FileModuleResolver,
}

impl MkModuleResolver {
    pub fn new(base_path: impl Into<PathBuf>) -> Self {
        Self {
            mk_module: build_module().into(),
            file_module_resolver: FileModuleResolver::new_with_path(base_path),
        }
    }
}

impl ModuleResolver for MkModuleResolver {
    fn resolve(
        &self,
        engine: &Engine,
        source: Option<&str>,
        path: &str,
        pos: Position,
    ) -> Result<Shared<Module>, Box<EvalAltResult>> {
        if path == "mk" {
            Ok(self.mk_module.clone())
        } else {
            self.file_module_resolver.resolve(engine, source, path, pos)
        }
    }
}
```

**Comment by schungx** [comment]
Seems like closures are somehow not kept in loaded modules.  That's a good catch.  I'll fix it.

**Comment by AcrylicShrimp** [comment]
Good! Please let me know when you're done, I'm stuck here...

**Comment by schungx** [comment]
Wait... it is not a bug afterall.  I just had a typo.

So back to the drawing board...

**Comment by AcrylicShrimp** [comment]
Ok! If you think it's my fault, let me know. My code is always open.

**Comment by schungx** [comment]
So far I haven't been able to reproduce the error, which means it is probably more subtle.

I have tried this:

```rust
// foo.rhai
import "hello" as h;
h::test(1, 2);

// hello.rhai
fn bar(x, y) { x + y }

fn test(a, b) {
    let f = |u, v| u - v;
    bar(a, b) * f.call(a, b)
}
```

I ran it and it is working fine.

Can you prune your case down to a simple reproduction?

**Comment by schungx** [comment]
After much testing, I suspect that `f.call(&self.engine, &module.ast, args)` is tripping you up.

Perhaps you might be calling a Rhai function pointer from withing a Rust function registered into the engine?

You're passing it `module.ast` which means the root level.  That's why, if you define the closure at the root level, it worked.

You might want to call that function pointer with the `NativeCallContext` of the Rust function instead.

**Comment by AcrylicShrimp** [comment]
Oh, I will try. But can I store that `NativeCallContext` somehow? I should call that closure later, not that moment the closure has been passed.

**Comment by schungx** [comment]
> Oh, I will try. But can I store that `NativeCallContext` somehow? I should call that closure later, not that moment the closure has been passed.

Not really, that's the problem.  It encapsulates the calling context deeply inside multiple layers of modules up to that point.  It really isn't easy to duplicate...

Maybe I can try.

**Comment by schungx** [comment]
`NativeCallContext::namespace()` give you a list of `Module`'s, which is what you need to pass into `f.call()` instead of `ast.as_ref()`.  That list of modules is the nested stack of modules up to that point, allowing you to access everything within the chain.

Unfortunately there is no real easy way to recreate that list except to manually resolve the stack of modules one by one based on the path name.

**Comment by AcrylicShrimp** [comment]
Hmm, so I cannot implement those features (at least easily) at this moment. Ok. But it is critical feature for my engine, I cannot continue for now. I should stop for now, or consider other script language to use.

Thank you!

**Comment by AcrylicShrimp** [comment]
> There is no convenient way right now for you to manually resolve a module (based on a path) from an Engine, but I will add a Engine::module_resolver() method which will allow you to do that.

Um, In this case, should I manually resolve modules every closure has been registered?

**Comment by schungx** [comment]
Actually I have edited my message just 5 minutes before you replied.  So here is my idea of a solution:

You call `NativeCallContext:;iter_namespaces()` and get the _last_ namespace (which should be the one calling environment).

You check `Module::id()` which should contain the path of that module.

You resolve that module.  Currently you have to do it via a new resolver, but I'll add a method to `Engine` that lets you just resolve modules from it.

Once you get that module, you recreate the list: `&[ast.as_ref(), module]` which you can then use to create your new `NativeCalContext`.  After that, Bob's your Uncle.

**Comment by AcrylicShrimp** [comment]
Thanks, I'll try!

**Comment by schungx** [comment]
> Um, In this case, should I manually resolve modules every closure has been registered?

The trick really is to _find_ that closure.  Once you find it, the environment operating environment (including all other functions) are already encapsulated into that function, so you can just call it.

Finding that closure, however, requires you to be able to access the module that defines it.

It is best to do this in your registration function, because logically it runs inside the module that also defines the closure.

You can get the path of that module simply via `NativeCallContext::iter_namespaces()`.  The trick is to actually resolve it (which you can always do by loading that file again via a `FileModuleResolver`, but it is better to get it directly from the `Engine`).

**Comment by schungx** [comment]
Actually, come to think of it, there is an even simpler solution.

`AST::resolver()` is exposed under the `internals` feature.  Since you're compiling the entire tree of scripts as a self-contained AST, all modules are already pre-resolved.  You can use `ast.resolver().unwrap().resolve(...)` to actually resolve that module.

Then you can add that module to a list, and use `NativeCallContext::new()` to recreate the context, where you can call your `FnPtr`.

**Comment by schungx** [comment]
BTW, I think you'd want the _first_ module in the list, not the last.  Anyhow, check the `id` of the module to see which one is the right path.  I think it should be the _first_ one.

**Comment by AcrylicShrimp** [comment]
Ok, let me try. I'll report here when it's done.

**Comment by schungx** [comment]
In this case, you don't even need to keep the AST around, as all your functions/closures reside in modules.  All you need is the path to the correct module for each closure.

**Comment by schungx** [comment]
OK, it seems like for Rust functions, I didn't bother to give you the path of the current module (never thought it would be needed).

I'll think a bit to see what can be done to resolve your issue.

**Comment by schungx** [comment]
I have tried it and successfully recreated the `NativeCallContext` simply by storing all the fields:

```rust
// Store fields for later use
let fn_name = context.fn_name().to_string();
let source = context.source().map(|s| s.to_string());
let global = context.global_runtime_state().unwrap().clone();
let pos = context.position();
let call_level = context.call_level();

// Store the paths of the stack of call modules up to this point.
// Modules are iterated in reverse order (meaning the current module last)
// so the list must be reversed.
let modules_list: Vec<String> =
    context.iter_namespaces().rev()
           .map(|m| m.id().unwrap_or(""))
           .filter(|id| !id.is_empty())
           .map(|id| id.to_string())
           .collect();

// ... store the fields somewhere ...

// ... do something else ...

// Recreate the 'NativeCallContext' - requires the 'internals' feature
let mut libraries = Vec::<Shared<Module>>::new();

for path in modules_list {
    // Recreate the stack of call modules by resolving each path with
    // the module resolver.
    let module = engine.module_resolver().resolve(engine, None, &path, pos)?;

    libraries.push(module);
}

let lib: Vec<&Module> = libraries.iter().map(|m| m.as_ref()).collect();

let new_context = NativeCallContext::new_with_all_fields(
                        &engine,
                        &fn_name,
                        src,
                        &global,
                        &lib,
                        pos,
                        call_level
                  );
```

**Comment by AcrylicShrimp** [comment]
Ok, I successfully handled this issue. I can call closures that are not defined in root module now! But, I think, it is very very counterintuitive, and very tricky to implement - I have written module caching logics and many other things to overcome this issue. Moreover, it's very inefficient because this solution introduces extra overhead. And I have to allocate some dynamic length of vectors every time to call a Rhai function/closure.

Can it be better somehow? If not, it's ok for now, but I will have to consider to use other languages :(

Anyway, thank you :)

**Comment by schungx** [comment]
> it is very very counterintuitive, and very tricky to implement

It really is, because you're really forcing Rhai to do something that it wasn't designed to do -- which is to suspend an execution state and resume it later on (probably on another thread).

My feeling is that any language you embed is going to give you the exact same problem because eventually you're going to need to do essentially the same thing -- which is to save the execution state (up to that point) as a struct... then restore that state (as much as possible) when you're ready to resume.

Some languages may give you a pre-built way to store the execution state and you might save some keystrokes, but essentially, in the background, it'll all be done in the same way.

**Comment by AcrylicShrimp** [comment]
> My feeling is that any language you embed is going to give you the exact same problem because eventually you're going to need to do essentially the same thing

Well, at least `Lua` doesn't have is problem. Normally, there's not state to management, to call closures. Closures are always callable, because that closure holds captures in their hand(closure = function + captures).

But I don't know the Rhai's implementation well. Maybe the Rhai need context to call closures, to restore/reconstruct an environment to emulate capturing where the closures are defined.

Anyway, As I said, it's good for now. I hope there's no further problems... thank you as always :)

**Comment by AcrylicShrimp** [comment]
And I think it's very common to register a script function/closure to the host side, and call them back later. The Rhai should support those features, as the Rhai is script language, in my opinion.

**Comment by schungx** [comment]
You're correct.  Some systems simply store the the function itself with the closure, so it can, sort of, "always find" it whenever you need to call it.  However, this doesn't resolve you from having to make available other functions that this closure may call, which essentially is the same problem.

It is much easier to do this without multiple nested layers of modules that import each other, each with proper encapsulation.  Encapsulated modules mean that you're not supposed to affect what's inside a module from the outside.  However, by storing a closure to call later on, if it depends on something within a deeply-nested module, then there are basically only a few options:

1) Make all those functions accessible outside the module system (essentially that means making them all global)
2) Store the entire tree of modules together with the closure
3) Have some way to recreate that tree of modules when you call the closure

Of course, if you are not loading dynamic modules (e.g. you're using a system where the modules are pre-loaded into the engine), then it obviously is not a problem.

The problem always surfaces when: 1) you have a closure, 2) that depends on some function, 3) within a dynamically-loaded module that's deeply-nested, 4) and modules are generally encapsulated.  Take away one of them and you don't have a problem.
