### ISSUE TITLE
Using `clippy`

### ISSUE THREAD

**Issue by Mathieu-Lala** [rhaiscript/rhai#629]
:wave: 

I added these line to `lib.rs` :
```rs
#![warn(clippy::all)]
#![warn(clippy::pedantic)]
#![warn(clippy::nursery)]
#![warn(clippy::cargo)]
```
And there is quite a lot of warnings (1K+)

Do you think these should be addressed ?

**Comment by schungx** [comment]
I regularly run these just to flush out warnings. However probably a bit heavy yo have inside the library as default.

**Comment by schungx** [comment]
Closing this for now unless there are new clippy flags that we should set by default.
