### ISSUE TITLE
Accessing an object map inside another object map from rust.

### ISSUE THREAD

**Issue by defensadev** [rhaiscript/rhai#643]
Hi, great work on rhai, I really like the language and the design choices (not trying to be a new lang + pure functions).

One of the problems I'm having involves invoking a rhai function from rust, this rhai function returns an object map (a btree alias once in rust). I can easily access properties that are, for example integers or numbers via cast.

```rust
let my_obj = engine.call_fn::<rhai::Map>(&mut rhai::Scope::new(), &ast, "my_func", ()).unwrap();

// get an int from the object map
my_obj.get("my_property").unwrap().as_int();

// code to get a sub object????
let my_sub_obj: rhai::Map = my_obj.get("my_sub_map").unwrap().cast()
// ERROR: cannot move out of a shared reference
```

I'm sure I'm just doing something wrong with the borrow checker, but for the life of me I can't figure what...

I appreciate any insight to help solving my problem! Thanks again for the work on rhai.

**Comment by defensadev** [comment]
Currently trying to use this method to access a sub object

```rust
let my_sub_obj = my_obj.get("my_sub_map").unwrap().clone_cast::<rhai::Map>();
```

**Comment by schungx** [comment]
`Map` is just an alias to `BTreeMap`, so `get` returns a reference to data.  Therefore you cannot move items using such a reference.

You need to use the appropriate `BTreeMap` API to get around this problem:

1) `get_mut` will get a mutable reference.  Then you can use `mem::take` to steal the property value (leaving the default behind).

2) `remove` will remove that property from the `BTreeMap` and the return its value.

3) you can `into_iter` it to deconstruct the `BTreeMap` into (key, value) pairs.

It depends on whether you want to keep the return value for something else.  If you don't, then use one of the above to deconstruct it.

**Comment by defensadev** [comment]
Ok remove worked for my use case!

Thanks for the speedy response!
