### ISSUE TITLE
Engine::new() panics on arm

### ISSUE THREAD

**Issue by KnorrFG** [rhaiscript/rhai#644]
Hey,
when I compile for the target armv7-unknown-linux-gnueabihf the following program:

```rust
fn main() {
    rhai::Engine::new();
}
```

will panic:
```
thread 'main' panicked at 'attempt to shift left with overflow', /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/types/bloom_filter.rs:28:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: rhai::types::bloom_filter::BloomFilterU64::hash
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/types/bloom_filter.rs:28:21
   4: rhai::types::bloom_filter::BloomFilterU64::mark
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/types/bloom_filter.rs:51:30
   5: rhai::module::Module::set_fn
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/module/mod.rs:1006:13
   6: rhai::packages::string_basic::print_debug_functions::rhai_generate_into_module
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/packages/string_basic.rs:50:1
   7: <rhai::packages::string_basic::BasicStringPackage as rhai::packages::Package>::init
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/packages/string_basic.rs:22:9
   8: <rhai::packages::pkg_core::CorePackage as rhai::packages::Package>::init
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/packages/mod.rs:139:41
   9: <rhai::packages::pkg_std::StandardPackage as rhai::packages::Package>::init
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/packages/mod.rs:139:41
  10: rhai::packages::pkg_std::StandardPackage::new
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/packages/mod.rs:170:17
  11: rhai::engine::Engine::new
             at /home/neuro/.cargo/registry/src/github.com-1ecc6299db9ec823/rhai-1.10.0/src/engine.rs:253:39
  12: test_station::utils::ScopedEngine::new
             at /project/src/utils.rs:19:21
  13: run_test::main
             at /project/src/bin/run_test.rs:35:22
  14: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I was able until today to run my program on a raspberry pi. Since today this crash happens. I actually have `rhai = { version = "1.9.1", features = ["sync"]}` in my Cargo.toml, but if I search for rhai in my Cargo.lock I get the follwing:

```
[[package]]
name = "rhai"
version = "1.10.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "863c895db914cfbef71203b027f6336c00c9aed51c985c484584c37dd0375c51"
dependencies = [
 "ahash 0.8.0",
 "bitflags",
 "instant",
 "num-traits",
 "rhai_codegen",
 "smallvec",
 "smartstring",
]

[[package]]
name = "rhai_codegen"
version = "1.4.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "36791b0b801159db25130fd46ac726d2751c070260bba3a4a0a3eeb6231bb82a"
dependencies = [
 "proc-macro2",
 "quote",
 "syn",
]

```

So I'm not sure which version is actuallly used. Also I don't know why there is a 1.10 in my Cargo.lock. I assume that it might have worked on 1.9.1 and stopped working on 1.10.0, even though I have no idea how it slipped onto my disk.

The reason that this crashes is that armv7 is a 32bit architecture, and usize is 32bit long there, and this code (which is the code that causes the crash):

```rust
    const fn hash(value: u64) -> (usize, usize) {
        let hash = (value & 0x00ff) as usize;
        (hash / 64, 0x01 << (hash % 64))
    }
```

shifts it by more than 32.

**Comment by schungx** [comment]
Yes this is a know bug introduced with version `1.10.0`.  I forgot to change 64 to 32 when running on 32-bit systems.  

This bug is fixed in the dev repo, so if you can pull directly from GitHub, it should be fixed.

If you need, I can push out version `1.10.1`.

**Comment by KnorrFG** [comment]
I see. Thanks for the Info. I'll go with the pin to 1.9.1 I don't require any 1.10 features.

**Comment by schungx** [comment]
In hindsight, it is really no OK for a new release to fail on all 32-bit architectures.

I'll probably put out a `1.10.1` soon.

Can you help by testing the latest drop on GitHub just to make sure that it works?

**Comment by KnorrFG** [comment]
I ran the testsuit of the current master on the raspberry (just `cargo test`) and this was the result
```
running 1 test
test tests::check_struct_sizes ... FAILED

failures:

---- tests::check_struct_sizes stdout ----
thread 'tests::check_struct_sizes' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `32`', src/tests.rs:22:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::check_struct_sizes

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '--lib'
```

There were also a lot of warnings. Should I post them too?

**Comment by schungx** [comment]
Hhmmm.... yes, this test doesn't take proper care for 32-bit as well (the structures are smaller on 32-bit).  Did you run `cargo test` before on `1.9.1`?  It should give you the same error because I don't think I have changed it.

By all means post all the warnings, unless you see them coming from test files.  Test files I haven't really cared about silencing warnings.

**Comment by KnorrFG** [comment]
You are right. The test failed the same way in 1.9.1. The warnings are all from tests and examples.
I now just compiled the Engine::new() call with the latest master on the Pi, and it didn't crash.

**Comment by schungx** [comment]
Can you run `cargo test` for the current drop (I just merged a fix)?  See if it goes through correctly?

**Comment by KnorrFG** [comment]
`test result: ok. 125 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 557.79s` :+1:

**Comment by schungx** [comment]
`1.10.1` released.

**Comment by KnorrFG** [comment]
Great, thank you. I guess I'll close this then :+1:
