### ISSUE TITLE
look_ahead in custom syntax is ambigious

### ISSUE THREAD

**Issue by the-eater** [rhaiscript/rhai#648]
Since the `look_ahead` in the parser function for `register_custom_syntax_raw` is simplified to a `&str` there is from the functions side of view, no different between the identifier `string` and the string `"gamer"`

it might be nice to have the `Token` directly passed instead

**Comment by schungx** [comment]
> it might be nice to have the `Token` directly passed instead

I believe `Token` is not normally exported except under `internals`.

**Comment by schungx** [comment]
What about changing it to quoted format? So `"gamer"`?

**Comment by schungx** [comment]
I can make literal strings return `"gamer"` instead of `string`...  that might help distinguish between them.

**Comment by schungx** [comment]
This will now be resolved in the next release.  Literal strings will be wrapped in `""`.
