### ISSUE TITLE
Question: Proper way to make a WASM build

### ISSUE THREAD

**Issue by ethanfrey** [rhaiscript/rhai#652]
Hi, I was very excited to here this could run in wasm and wanted to test it out, first to see relative byte code sizes I could expect before embedding it in my program. However, I had a number of errors compiling (on Rust 1.62). The minimal version that finally worked was:

`cargo build --release --target wasm32-unknown-unknown --no-default-features`
But I think I really would want:
`cargo build --release --target wasm32-unknown-unknown --no-default-features --features wasm-bindgen`

The following variants all errored:

* `cargo build --release --target wasm32-unknown-unknown`
* `cargo build --release --target wasm32-unknown-unknown --features wasm-bindgen`

```
   Compiling getrandom v0.2.7
error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
```

* `cargo build --release --target wasm32-unknown-unknown --features wasm-bindgen,no_std --no-default-features` also errored:

```
error: `wasm-bindgen` cannot be used with `no-std`
   --> src/lib.rs:447:1
    |
447 | compile_error!("`wasm-bindgen` cannot be used with `no-std`");
```

It seems funny to disable both `std` and `no_std` to get it to compile. Is this the proper approach?

NB: I looked at [the CI Scripts](https://github.com/rhaiscript/rhai/blob/main/.github/workflows/build.yml) to see how you build wasm there, and it is not included. May be nice to add a small section there, to at least test it compiles to wasm properly (even if it doesn't spin up node server and run the wasm)

**Comment by schungx** [comment]
You can also consult: https://rhai.rs/book/start/builds/wasm.html

**Comment by schungx** [comment]
Ah, I get it now.  There is a problem in recent versions due to the `ahash` dependency.  `ahash` changed the way feature flags are used and caused all kinds of problems with builds.

The problem is, `ahash/runtime-rng` which is enabled by `std` does not seem compatible with wasm.  I'll have to think of a way to do this elegantly...

In the meantime, you're correct to find that you  must exclude `std` via `--no-default-features`.  You probably should also include `ahash/compile-time-rng`.

**Comment by ethanfrey** [comment]
Thank you for this advice.

I made a PR that should address this as well as I could: https://github.com/rhaiscript/rhai/pull/653 (both CI tests as well as feature changes). I tried to unify std feature to enable runtime or compiletime ahash rng based on target, but hit the limits of Cargo.toml (or my knowledge and google ability).

We should add docs, but now the following two would work well for Wasm builds:

`cargo build --target wasm32-unknown-unknown --features js` (compiles std, with browser get random)
`cargo build --target wasm32-unknown-unknown --no-default-features --features wasm-std` (almost the same as std, but with compile-time-rng)

Happy for feedback on this approach and how to cleanup / improve it.

**Comment by ethanfrey** [comment]
P.S. you can see the CI runs here: https://github.com/ethanfrey/rhai/pull/1

**Comment by ethanfrey** [comment]
Great. With #656 and #659, this works. For the record, here is how.

If you can use wasm-bindgen, this will work (targeting web):

`wasm build --target wasm32-unknown-unknown --features wasm-bindgen`

If you want to make a wasm build with no imports (custom runtime), you need to disable access to png and system time. You can do like this:

`wasm build --target wasm32-unknown-unknown --no-default-features --features std,no_time`

**Comment by schungx** [comment]
> If you can use wasm-bindgen, this will work (targeting web):
> wasm build --target wasm32-unknown-unknown --features wasm-bindgen

Unfortunately you'd also need to pull in. `getrandom/js` to get it to work on browser.
