### ISSUE TITLE
Static hashing fine-tune

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai#665]
@l1npengtul a couple issues:

1) `let value = f();` in `get_or_init` seems to be run every call; instead it needs only be run once when the value should be set.

2) Is there a way for `get` and `get_or_init` to return a reference to the data instead of copying it?  Although copying four 64-bit words during each call is not a big deal, but still it might be faster to just return an `Option<&T>` instead.  I see that you do a `read` to copy that value (which is an array)... maybe just return `cast` itself as a reference?

**Comment by l1npengtul** [comment]
Ive made #666 to address this.
