### ISSUE TITLE
blob bug

### ISSUE THREAD

**Issue by zhuchuanjing** [rhaiscript/rhai#675]
if obj is a dynamic
and bytes is a blob in this dynamic.
other.data = obj.bytes will get below error!
Expression exceeds maximum complexity

**Comment by schungx** [comment]
This is not related to BLOB's, but this: https://rhai.rs/book/safety/max-stmt-depth.html

You must be using a debug build which has very low tolerance as default.  You can set this limit via `Engine::set_max_expr_depths`.

**Comment by schungx** [comment]
Closing this for now.  Feel free to reopen if you still have prob.
