### ISSUE TITLE
Closures for expressions

### ISSUE THREAD

**Issue by SeokminHong** [rhaiscript/rhai#677]
Hi 👋 

I tried to build a scriptable thing using Rhai. I want to restrict user input for expression only, so I used `Engine::eval_expression`. However, if the input has closures, it fails to parse.

I think it's because Rhai interprets closures as a declaring anonymous function, so it isn't regarded as an expression. Do I guess right? If it is, do you have plans to provide an option or a feature to allow closures in expressions?

**Comment by SeokminHong** [comment]
When I tried following expression:

```rust
println!(
    "{:?}",
    engine.compile_expression("[1, 2, 3, 4].map(|x| x + 1)")
);
```

It prints `Err(ParseError(BadInput(UnexpectedInput("|")), 1:18))`. I think it's because of following code:

https://github.com/rhaiscript/rhai/blob/252567f84d138257c7896e6d17ad74146a08c8de/src/parser.rs#L3838-L3850

I think it disables the anonymous function feature. Isn't it?

**Comment by schungx** [comment]
Looks like it is so. I'll see if I can fix this

**Comment by schungx** [comment]
This is will fixed in the next major version.  Do you need it urgently or can you wait?

**Comment by SeokminHong** [comment]
> 

I can. Thank you!

**Comment by schungx** [comment]
This feature is now standard.
