### ISSUE TITLE
`ExprTooDeep` error

### ISSUE THREAD

**Issue by SeokminHong** [rhaiscript/rhai#678]
Hi again.

I tried a simple Rhai code on Playground:

```rust
let values = [1, 2, 3, 4, 5];

fn template(a, b) {
    `${a}-${b.name}`
}

values
    .map(|v| `${template("simple", #{name: v})}`)
```

The above code returns `["simple-1", "simple-2", "simple-3", "simple-4", "simple-5"]`.

However, when I tried to run on my code, it returns compile error:

```rust
use rhai::Engine;

fn main() {
    let engine = Engine::new();
    let c = engine.compile(
        r#"
let values = [1, 2, 3, 4, 5];

fn template(a, b) {
    `${a}-${b.name}`
}

values.map(|v| `${template("simple", #{name: v})}`)
"#,
    );
    println!("{:?}", c);
}
```

```
Err(ParseError(ExprTooDeep, 8:38))
```

This is my environment:

- Rhai version: 1.11
- Rhai features: `serde`
- Rust version: 1.65.0 (stable)

Could you check this error?

**Comment by schungx** [comment]
check out: https://rhai.rs/book/safety/max-stmt-depth.html

I suppose you're running on `debug` build?

**Comment by SeokminHong** [comment]
Yes, I think that's the problem. Thank you!

However, why does the closure inside the string interpolation takes too many depths? When I tested, it took 19 depth, even though it looked very simple.
