### ISSUE TITLE
Consider `document-features`

### ISSUE THREAD

**Issue by Mathieu-Lala** [rhaiscript/rhai#683]
The documentation produced by [`document-features`](https://docs.rs/document-features) can be great to enhance the `rhai` feature flags documentation :book: !

**Comment by schungx** [comment]
Interesting... but I'd rather not pull in yet another crate simply to get feature documentation.

**Comment by Mathieu-Lala** [comment]
We can set `optional = true` and use it with a feature flags, so it won't affect downstream crates depending on `rhai`.

**Comment by schungx** [comment]
> We can set `optional = true` and use it with a feature flags, so it won't affect downstream crates depending on `rhai`.

Is it possible to set it just when generating docs?

**Comment by schungx** [comment]
Alright looks like it works.  I'll add it.  The generated docs look quite nice.

Thanks!
