### ISSUE TITLE
Methods in script defined modules are difficult or impossible to use

### ISSUE THREAD

**Issue by m-r-hunt** [rhaiscript/rhai#689]
Let's say we've created a module from Rhai script as per [this page](https://rhai.rs/book/rust/modules/ast.html). And this module contains some methods (using `this`) that we want to call from another script.

Now, as per [this page](https://rhai.rs/book/rust/modules/use.html) we have 3 options for how to use this module.

* Use Case 1 - global module - in this case, the methods work and are available, but we have to put any such module into the global namespace for all scripts using it, which is a bit rough
* Use Case 2 - Static Namespace - in this case, as far as I've been able to determine, the methods are totally unusable. They are not in the global namespace, so aren't found when doing a `.` method call. And function-call-syntax calls don't work because `this` will be unbound (and it won't accept an explicit `this` first argument, unlike native methods)
* Use Case 3 - Dynamically Loadable - if you do an unqualified import, the functions from the module don't get saved, so that's no help. With a qualified import, you have the same problem as case 2, can't use method call syntax or function call syntax to call the method.

This really limits the usefulness of methods inside script-defined modules. It seems to me that something needs to be done to improve this situation.

My suggestion would be for `.` method calls to search static and imported modules for methods with the appropriate name in addition to the global namespace.

**Comment by schungx** [comment]
> My suggestion would be for `.` method calls to search static and imported modules for methods with the appropriate name in addition to the global namespace.

It is a bit more complicated that this.  Assume the following:

`module.rhai`

```rust
fn my_method(x, y, z) {
    // this function uses `this`
    do_work(this, x + y + z)
}

fn my_simple_method(x, y, z) {
    // this function does not use `this`
    x * y * z
}
```

`main.rhai`

```rust
let x = obj.my_method(1, 2, 3);    // OK
let x = obj.my_simple_method(1, 2, 3);    // Still OK... but it shouldn't be
```

The bottomline is: there isn't a good way to distinguish _methods_ vs _functions_ when they are script-defined.  The only thing that makes a method a method is that it uses `this` inside somewhere (although it doesn't have to).

Currently, methods written in Rhai are sort of an after-thought...

To resolve your issue, we'd need to maybe introduce a new keyword:

```rust
method my_method(x, y, z) {
    // this function can only be called in method style
    do_work(this, x + y + z)
}

fn my_simple_method(x, y, z) {
    // this function cannot use `this`
    x * y * z
}
```

**Comment by m-r-hunt** [comment]
The problem you describe already exists for script defined methods within a single file.

E.g. I tried running this in the playground
```
fn do_work(a, b) {
    a + b
}

fn my_method(x, y, z) {
    // this function uses `this`
    do_work(this, x + y + z)
}

fn my_simple_method(x, y, z) {
    // this function does not use `this`
    x * y * z
}

let x = 0;

print(x.my_method(1, 2, 3));

print(x.my_simple_method(1, 2, 3));
```
And it's happy to call `my_simple_method` with method syntax despite no use of `this`. I guess it would be more of a problem if multiple modules could lead to confusing name collisions.

**Comment by schungx** [comment]
> And it's happy to call `my_simple_method` with method syntax despite no use of `this`. I guess it would be more of a problem if multiple modules could lead to confusing name collisions.

That's correct.  Although, within a single file, it is still mostly manageable.  In multiple layers of imported modules, it becomes very hard to manage very quickly, because you never know where a method is defined, and suddenly it calls something else when one of the modules in the chain changes.

`this` was added to allow a way for script-defined functions to mutate values outside (otherwise it is 100% pure).  It is mostly intended for calling a function via `Engine::call_fn` where a value is bound to the `this` pointer.  I am yet to find large-scale uses of methods with script-defined functions, because you always has the hassle of needing to double-check the data type of `this` to make sure that it is called on correct values.

**Comment by m-r-hunt** [comment]
I'm working on a project where users will write many small scripts (an hyperlink-style interactive fiction creation tool where you can attach a script any time a link is clicked or a new text passage is entered). I'm looking at user-written script modules to have shared functionality between these scripts. I was thinking that it would be nice to have user-defined methods included as a convenience for doing certain state updates more easily.

For now, sticking with modules and regular functions should be fine though.

**Comment by schungx** [comment]
Yeah, I'd say that the ehole concept of methods defined in script is less well-defined than it should.

A method necessarily means acting on a type that supports that method. That is at odds with dynamic typing.

**Comment by schungx** [comment]
One potential solution is to introduce new syntax:

```rust
fn my_method(x, y, z) where this: "MyCustomObject" {
    ....
}
```

where it only matches if `this` is bound to a value of a particular type.

**Comment by schungx** [comment]
@m-r-hunt   if you'd pull from this repo, the latest version now contains the ability to write methods as Rhai functions that are called only with `this` bound to a particular type.  That should be address the issue of defining methods in script.

The syntax is:

```rust
fn  MyType.foo(x, y) { ... }          // only when `this` is `MyType`

fn AnotherType.foo(x, y) { ... }          // only when `this` is `AnotherType`

fn bool.foo(x, y) { ... }          // only when `this` is boolean

fn string.foo(x, y) { ... }          // only when `this` is a string

fn int.foo(x, y) { ... }          // only when `this` is an integer
```

`MyType` is any identifier (or string) that matches exactly the output of the `type_of` function, with the exception that `int` and `float` are also recognized and mapped to the corresponding data types during parsing.
