### ISSUE TITLE
Data type incorrect when accessing a property of an array element when indexing by an index from an array

### ISSUE THREAD

**Issue by Feuermagier** [rhaiscript/rhai#696]
This code fails with `EXCEPTION: Data type incorrect: array (expecting i64) (line 7, position 6)`
```
let x = #{
    foo: 0
};

let a = [[x]];
let i = [0];
print(a[0][i[0]].foo);
```

It doesn't fail when directly using an index:
```
let x = #{
    foo: 0
};

let a = [[x]];
let i = [0];
print(a[0][0].foo);
```

or (strangely) when not accessing `foo`:
```
let x = #{
    foo: 0
};

let a = [[x]];
let i = [0];
print(a[0][i[0]]);
```

I'm not sure if this is a bug or if I just don't see the reason for the error but the behavior doesn't look right to me.

**Comment by schungx** [comment]
I think I found it.  Do you need a fix right away?  Or can you wait until the next version?

I can put out a `1.12.1` if you need it urgently.

**Comment by Feuermagier** [comment]
Thanks! I think pulling from master is fine for me.
