### ISSUE TITLE
More functions in `BasicMathPackage` like `min(x, y)`, `max(x, y)`, ...

### ISSUE THREAD

**Issue by LetsMelon** [rhaiscript/rhai#700]
It would be nice if the `BasicMathPackage` implements more basic functions, like some functions processing implements by default.

from processings [docs](https://processing.org/reference/#math):
 - [x] `abs()` Calculates the absolute value (magnitude) of a number
 - [x] `ceil()` Calculates the closest int value that is greater than or equal to the value of the parameter
 - [ ] `constrain()` Constrains a value to not exceed a maximum and minimum value
 - [x] `exp()` Returns Euler's number e (2.71828...) raised to the power of the value parameter
 - [x] `floor()` Calculates the closest int value that is less than or equal to the value of the parameter
 - [ ] `lerp()` Calculates a number between two numbers at a specific increment
 - [x] `log()` Calculates the natural logarithm (the base-e logarithm) of a number
 - [ ] `map()` Re-maps a number from one range to another
 - [ ] `max()` Determines the largest value in a sequence of numbers
 - [ ] `min()` Determines the smallest value in a sequence of numbers
 - [ ] `norm()` Normalizes a number from another range into a value between 0 and 1
 - [ ] `pow()` Facilitates exponential expressions
 - [x] `round()` Calculates the integer closest to the value parameter
 - [ ] `sq()` Squares a number (multiplies a number by itself)
 - [x] `sqrt()` Calculates the square root of a number

other functions from the docs: (but I'm not quit sure if they would be really necessary and maybe they should go into a separate package for vectors)
 - [ ] `dist()` Calculates the distance between two points
 - [ ] `mag()` Calculates the magnitude (or length) of a vector

(Sorry if I missed a already implemented function from the packages and I'm in love with this crate, so easy to use)

**Comment by LetsMelon** [comment]
I think these functions would better fit in the `BasicMathPackage` because of the simplicity of the functions and the comprehensive area of ​​application.

e.g.:
pixel manipulation from a float value with the range `0.0 - 1.0` to an `0.0 - 255.0` int range -> `map(1.0, 0.0, 1.0, 0.0, 255.0)` [1]

----

[1] maybe a better implementation of `map` can cast between float and integer so that you can do this: `map(1.0, 0.0, 1.0, 0, 255)`) an store the result in rust as `u8`

**Comment by schungx** [comment]
It probably won't be `Basic`...  if we put it in the standard library, we probably would need to create something like `MoreMathPackage` etc.

Actually I see many of your proposed functions already in `rhai-sci` so perhaps it is not a good idea to duplicate.

And the remaining ones are really not very standard and have specific uses in specific cases.

**Comment by LetsMelon** [comment]
But nevertheless a official and tested distribution of the missing (or more, or less, ...) in `rhai-sci` would be better than none.

**Comment by LetsMelon** [comment]
> But nevertheless a official and tested distribution of the missing (or more, or less, ...) in `rhai-sci` would be better than none.

And then maybe it would also be a great idea to mention `rhai-sci` in the docs page for [Numeric Functions](https://rhai.rs/book/language/num-fn.html).

**Comment by schungx** [comment]
There are more things to consider. For example, the `max` function takes two numbers.

Normally, in the standard library, numbers can interoperate, and there are `INT`, `FLOAT`, `Decimal`.

So we're looking at nine combinations and so nine versions of the function.  Seven if excluding float+decimal.

This falls into the gray area where we need to ponder whethrr to add max and min. Because they can easily be replaced by an `if` expression.

**Comment by schungx** [comment]
Alright, come to think of it, I agree that `max` and `min` probably should belong to the standard library, considering that operators like `>` and `<` are defined for numbers.

I'll add them.  Like all the other operators, floating-point can also inter-operate with integers for `max` and `min`.
