### ISSUE TITLE
Support for multidimensional homogeneous arrays

### ISSUE THREAD

**Issue by starovoid** [rhaiscript/rhai#701]
In my project, I needed to call a function from a script that takes an `Array`, which is then converted to `Vec<Vec<String>>` (or `Vec<Vec<ImmutableString>>`). 
To do this, I had to write quite a lot of code with significant overhead for type conversion. 
Now, I came up with the idea of allowing support for homogeneous multidimensional arrays in the native **rhai**. 
What is the best thing for me to do? Create a pull request directly to this repository, or create a separate crate representing a module with the appropriate data type or/and syntax?

My cumbersome code:

```rust
fn parse_keyboard(arr: &Array) -> Option<Vec<Vec<String>>> {
    let mut keyboard = Vec::with_capacity(arr.len());
    for r in arr.iter() {
        match r.clone().try_cast::<Array>() {
            Some(row) => match parse_row(&row) {
                Some(parsed) => keyboard.push(parsed),
                None => return None,
            },
            None => return None,
        }
    }
    Some(keyboard)
}

fn parse_row(row: &[Dynamic]) -> Option<Vec<String>> {
    let mut parsed_row = Vec::with_capacity(row.len());
    for label in row.into_iter() {
        match label.clone().try_cast::<ImmutableString>() {
            Some(text) => parsed_row.push(text.into_owned()),
            None => return None,
        }
    }
    Some(parsed_row)
}
```

**Comment by schungx** [comment]
How about:

```rust
for r in arr.iter() {
    if let Some(inner) = r.read_lock::<Array>() {
        for item in inner.iter() {
            if let Some(label) = item.read_lock::<ImmutableString>() {
               ...
            } else {
                return None;
            }
        }
    } else {
        return None;
    }
}
```

}

**Comment by starovoid** [comment]
Thanks, it does work. However, there is still a lot of code written.

In my dreams I see:
```rust
fn parse_keyboard(arr: MyArr<MyArr<ImmutableString>>) -> ...
```

**Comment by schungx** [comment]
You can probably write it concisely as an iterator...

```rust
arr.iter().filter_map(Dynamic::read_lock::<Array>).fold(
            Vec::new(),
            |mut list, inner| {
                list.extend(inner.iter().filter_map(|s| s.read_lock::<ImmutableString>()).map(process));
                list
            },
        )
```

Although this example only skips non-string values instead of immediately returning `None`, but you get the idea.

**Comment by starovoid** [comment]
Ok, apparently the problem is not so relevant. Thanks for the `read_lock`, I think the issue can be closed.
