### ISSUE TITLE
!in operator parser is too greedy, breaks existing scripts

### ISSUE THREAD

**Issue by dimfeld** [rhaiscript/rhai#703]
The parser for `!in` seems overly greedy. If you have a boolean variable starting with `in` such as `include`, and then you type `!include`, the parser throws an error.

This broke an existing script that I had which worked fine before 1.12. I just changed the code to do the same thing with different syntax so it's not a big deal, but it would be nice if the parser was less greedy in checking for this token.

## Example

```rhai
let include = false;
if !include { // Parser error
   print("Hello world!");
}
```

**Comment by schungx** [comment]
Thanks for picking this up. I'll fix it.

**Comment by schungx** [comment]
Would you need it urgently?  Or can you wait till the next version?

If there is an urgent need, I can put out a `1.12.1`.

**Comment by dimfeld** [comment]
No, this isn't urgent at all for me. I changed my script to not trip over this bug, so it's not blocking me from anything. Thanks for the quick response!
