### ISSUE TITLE
Both &str and String are called string

### ISSUE THREAD

**Issue by LinuxHeki** [rhaiscript/rhai#718]
Lets say I want to get result from some string manipulation function:
```
let script = "\"Hello World\""; // This returns "Hello World"
let engine = Engine::new_raw();
let result = match engine.eval::<&str>(script) {
    Ok(result) => result.to_string(),
    Err(error) => error.to_string(),
};
println!("{}", result);
```

This will return `Output type incorrect: string (expecting string)`. To fix this you just have to replace `&str` with `String`, you should figure that out with help of error message and not with trying.

**Comment by schungx** [comment]
Yes... Unfortunate that `&str` is also displayed as `string` by Rhai... Let me see if there is a way to get around this.

**Comment by schungx** [comment]
The fix will go live in the next version.  `&str` will now be rendered `&str` to avoid confusion.
