### ISSUE TITLE
How to pass subgraph as a parameter to response callback

### ISSUE THREAD

**Issue by kay8910** [rhaiscript/rhai#721]
I have tried using this closure, but it is giving module not found exception.
fn process_subgraph_response(subgraph) { return |response|{ 
  manipulate_headers::set_txn_id_in_response_header(response); 
  apollo_error_code_plugin::set_extension_in_response_context(response); 
  } 
}

**Comment by schungx** [comment]
I suggest you open an issue with the vSTMP repo: https://github.com/viridIT/vSMTP/releases

**Comment by schungx** [comment]
Looks like you are using apollo. I suggest you open an issue directly with them:

https://github.com/apollographql

**Comment by kay8910** [comment]
Thanks, let me do that
