### ISSUE TITLE
Can't sort array by float using closure

### ISSUE THREAD

**Issue by bellwether-softworks** [rhaiscript/rhai#722]
Consider the following illustration:

```rhai
let b = [-0.063565664, 0.053330485, -0.09696456];

b.sort(|a, b| a - b);

b
```

In the above, I would expect the value indices to change from [0, 1, 2] to [2, 0, 1].  Currently, the `b` array is unchanged after executing the sort.  Running `.sort()` without parameters gets the desired result, and using the closure works fine if I change from floating-point values to integers.

This behavior can be confirmed on the sandbox.

**Comment by schungx** [comment]
The return value must be an integer:

* Any integer > 0 if `element1 > element2`
* Zero if `element1 == element2`
* Any integer < 0 if `element1 < element2`

Returning a float is not recognized.

So you need to do:
```rust
|a, b| (a - b).sign()
```
