### ISSUE TITLE
method name location sometimes fails at runtime

### ISSUE THREAD

**Issue by garypen** [rhaiscript/rhai#723]
As per the discord discussion: https://discord.com/channels/767611025456889857/772104119996383243/1077799380834336798
our rhai engine will sometimes fail to "find" functions/methods at runtime.

The behaviour is not entirely deterministic, but it does seem to have increased frequency:
 - in our CI environment, where tests that work fine when run locally will semi-reliably fail in CI
 - for certain particular tests, named:
```
test tests::test_subgraph_cache_control ... ok
test tests::test_subgraph_cache_control_missing ... ok
test tests::test_subgraph_cache_control_public ... ok
```
From the discord discussion, @schungx suggested that this might be caused by a `ahash` collision.

**Comment by schungx** [comment]
What version are you using?

Please add the flag `testing_environ` to your tests.  This turns on hash checking in order to catch collisions.

**Comment by garypen** [comment]
This is rhai: `1.14.0`, rustc: `1.70.0`

Our configuration is:
```
rhai = { version = "1.14.0", features = ["sync", "serde", "internals"] }
```

I'll add the flag to our tests.
