### ISSUE TITLE
Is there a proper way to limit execution time and memory usage?

### ISSUE THREAD

**Issue by boehs** [rhaiscript/rhai#730]
I see rhai has a strong sandbox.

https://rhai.rs/book/safety/max-operations.html allows some rough runtime length restriction. Is there a way to definitively end execution after x time?

https://rhai.rs/book/safety/max-string-size.html and https://rhai.rs/book/safety/max-array-size.html allow some control over memory runaway (as noted, in effect the limit could be briefly 2x larger than intended because of adding strings) but couldn't these limits just be circumvented by creating many large strings close to the limit?

```rs
a = "a very large string... *almost* at the limit"
b = "a very large string... *almost* at the limit"
c = "a very large string... *almost* at the limit"
d = "a very large string... *almost* at the limit"
....
````

**Comment by schungx** [comment]
> but couldn't these limits just be circumvented by creating many large strings close to the limit?

Hhhmmm....  that is true.  No _single_ object can be above limits, but technically speaking there are no checks on on the scope.  

So technically speaking, you may go above the limit by creating a large number of variables...

This may be a potential DOS venue.  I'll look into that.

**Comment by schungx** [comment]
> Is there a way to definitively end execution after x time?

Nope, as not all architectures have timers.  You can experiment and set an appropriate operations limit though...

**Comment by schungx** [comment]
In the latest drop, there is a new limit, settable via `Engine::set_max_variables` to control how many variables are allowed in any `Scope`.  This should catch the attack described above.

**Comment by schungx** [comment]
Closing for now.  Feel free to reopen if you have any more questions.
