### ISSUE TITLE
How to export a function that uses a property of my struct but I dont want to export the whole struct?

### ISSUE THREAD

**Issue by jkvargas** [rhaiscript/rhai#735]
```
struct Plugin {
    engine: Engine,
    compiled_code: AST,
    work_dir: PathBuf,
}

impl Plugin {
    pub(crate) fn new_from_string(code: String, work_dir: PathBuf) -> Result<Self> {
        let mut engine = Engine::new_raw();
        engine.register_fn("mkdir", Plugin::mkdir);

        let compiled_code = engine.compile(code)?;

        Ok(Self {
            engine,
            compiled_code,
            work_dir,
        })
    }
    
    pub(crate) fn mkdir(&self, directory: ImmutableString) -> bool {
        let final_dir = self.work_dir.join(directory.as_str());
        let res = create_dir_all(final_dir);
        if res.is_ok() { false } else { true }
    }
}
```

how do I use the mkdir function in rhai script without having to instantiate Plugin?
that object creation will happen inside rust :)

**Comment by schungx** [comment]
First of all, `&self` is not supported by Rhai.  You'd need `&mut self` at the very least.

As to your question, it seems that you need to, somehow, pass in the working directory into the `Engine` such that it knows where the root is.  There are a few ways to do this, but in your case, as it is unlikely to change, it is simplest to store this kind of info into the Engine's `tag`.

https://rhai.rs/book/engine/options.html?highlight=set_default_tag#runtime-behavior

The tag is set by calling `Engine::set_default_tag`.  You can then access this `tag` from the `NativeCallContext` of the function.  If you have more than one piece of information, you can make this an object map.

Alternatively, if your root directly will be changed dynamically, then essentially you have two routes to access the same property: via the `Plugin` type as well as via a Rhai script.  this obviously calls for a _shared_ data value (e.g. `Rc<RefCell<...>>`) that you can capture into a closure for the `register_fn` call.

**Comment by jkvargas** [comment]
thanks so much for the info.
Also, what are the other options you mentioned.
Can you point out on the docs? 
Thanks!

**Comment by schungx** [comment]
> Also, what are the other options you mentioned.

What are the other options you require?
