### ISSUE TITLE
? operator / "return if value is ()"

### ISSUE THREAD

**Issue by Mg138** [rhaiscript/rhai#738]
Currently, as far as we can tell from the language reference, it's rather cumbersome to immediately return () when the value is ().

Is such an operator possible? Alternatively, checking if a value is () could be less awfully looking. Currently it seems that the best way is just to check the type. Or you could cast any non-unit value to boolean true, and unit to false.

There's many ways to go about this.

**Comment by schungx** [comment]
This can be implemented quite easily... However I am not sure if this would be a good idea...

This potentially opens up new code return paths that are very subtle and hard to catch. There is no type checker as in Rust to make sure users don't make typos.

**Comment by Mg138** [comment]
I see. Fair point.

There's also another way, that is to somehow introduce a scope / closure that looks like (borrowing syntax from Kotlin):
```kt
some_var?.let { this_wont_be_null ->
   ...
}
```

*Maybe* something like that would be better, since it introduces a clear hierarchy?

It doesn't necessarily have to be technically a closure or visually one, something like `if let` from rust would work as well but we're not sure how the syntax for that would even look.

---

Semirelated, we looked at the book again, apparently you should be able to say `if some_var != ()`?

When we tried that it complained about the corresponding == operator for `(Foo, ())` isn't implemented, despite the book saying it should be `true if not defined` if the two types are different.

**Comment by Mg138** [comment]
We can make a separate issue if that's not an intended behaviour of Rhai.

**Comment by schungx** [comment]
> When we tried that it complained about the corresponding == operator for `(Foo, ())` isn't implemented, despite the book saying it should be `true if not defined` if the two types are different.

This is strange, as it should return `false`...  I suppose `Foo` is a custom type?

**Comment by Mg138** [comment]
Yes, it's a custom type.

**Comment by Mg138** [comment]
Oh, we should've said != not ==, our bad 😓

**Comment by schungx** [comment]
Let me try that out to check... I suppose it should automatically return `true`...

**Comment by schungx** [comment]
@Mg138   you're correct.  `==` and `!=` etc. do not return `false` and `true` as expected for custom objects.  That's a bug.

Thanks for catching it.  The fix should be in the next release.

**Comment by Mg138** [comment]
We can wait, just tag us when it's ready so we can migrate old code.

**Comment by schungx** [comment]
@Mg138   you can pull from this master to try out the fix.

**Comment by Mg138** [comment]
It works! :100:

**Comment by schungx** [comment]
Thanks for catching this.

**Comment by schungx** [comment]
Closing this for now...  Feel free if there are any more issues.
