### ISSUE TITLE
No `min` function defined for (i32, i32) using Standard package

### ISSUE THREAD

**Issue by Mg138** [rhaiscript/rhai#739]
`ErrorInFunctionCall("handle_transaction", "", ErrorFunctionNotFound("min (i32, i32)", 30:38), none)`

**Comment by schungx** [comment]
The default for Rhai is `i64` instead of `i32`.  You're encouraged to stick to Rhai's standard integer type because it'll make scripts much faster.

If you want to set the standard integer type to `i32`, use the `only_i32` feature.

**Comment by Mg138** [comment]
We are using only_i32.

**Comment by schungx** [comment]
Yup, this is a bug.  It has been omitted.

Are you in a hurry for a fix?  Do you need a new release?  Or can you wait until the next major?

You can pull from this master to test out the fix.

**Comment by Mg138** [comment]
We can wait for the next major. We've temporarily patched it for ourselves anyway by adding the function on our own.

You're free to close this issue, or later when it's released :+1:
