### ISSUE TITLE
Method chaining by returning self

### ISSUE THREAD

**Issue by mmm1245** [rhaiscript/rhai#744]
I am trying to create a builder like this: 
`create_block("test:stone").client_type_cube("test:stone", "test:stone", "test:stone", "test:stone", "test:stone", "test:stone").register();`
but as client_type_cube doesn't return self, it doesn't work.
I tried returning `self`, which errors because that function no longer implements trait RegisterNativeFunction.
Next thing i tried was returning `Dynamic::from(self)`, but that fails because i cannot clone mutable reference.

**Comment by schungx** [comment]
I suppose you mean `&mut self`?

That's not supported as a return type. Rhai works primarily with cloned values to avoid talking about lifetimes.

You can, however, take `self` and return it though.

**Comment by mmm1245** [comment]
I am now wrapping it in Rc.
Thanks for help
