### ISSUE TITLE
[Minor] Consider renaming the `AST` types to `Ast` and `Ast*`

### ISSUE THREAD

**Issue by AregevDev** [rhaiscript/rhai#745]
Hi,
I started experimenting with rhai and it's really nice.

According to the API guidelines  (https://rust-lang.github.io/api-guidelines/naming.html) acronyms are considered as a single word. `AST`, `ASTFlags` and `ASTNode` should become `Ast`, `AstFlags` and `AstNode` respectively.

This is a breaking change however, and somewhat nitpicky. Do with it as you please...

**Comment by schungx** [comment]
Yes, this is historical and unfortunately breaking.

**Comment by AregevDev** [comment]
So nothing can be done about it... Bummer

**Comment by schungx** [comment]
Closing for now.  Feel free to reopen if you have any more questions.
