### ISSUE TITLE
`FileModuleResolver` is disabled for all wasm, not just wasm-unknown

### ISSUE THREAD

**Issue by philpax** [rhaiscript/rhai#746]
Hi there!

I'm using Rhai in a wasm32-wasi environment (which has file access) and was hoping to use the `FileModuleResolver`, but it appears that the public export is disabled for all WASM:

https://github.com/rhaiscript/rhai/blob/84fd228281b1ccc4b062c5caa98d8acb14db3d42/src/module/resolvers/mod.rs#L15-L16

I'd suggest changing this to checking for `target_family = wasm` and `target_os = unknown`.

**Comment by schungx** [comment]
Hhmmm....  `target_os = unknown` is probably not correct also, because not all known OS for WASM will have file support.

I wonder how `std::fs` does it for wasm targets... let me research a bit...

**Comment by schungx** [comment]
Do you know if `wasm32-wasi` exposes `target_os = wasi`?  If so, we can probably put a special flag on it.

**Comment by philpax** [comment]
Ah yeah, fair enough. Yes, I believe the `wasi` part refers to the OS (the information on this is a little conflicting).

https://doc.rust-lang.org/rustc/platform-support.html mentions only -unknown, -wasi and -emscripten; the latter two should support files. I think checking for -unknown should be sufficient - I think that's what I've seen in other parts of the ecosystem.

**Comment by schungx** [comment]
The fix has landed in this repo.  You can pull from here to test it out.

If you need it urgently, I can release a point release.  Otherwise, it'll go live in the next release.

Thanks!

**Comment by philpax** [comment]
Thanks! No rush, I was just experimenting. It seems like you've pushed to your local repo instead of this one, though? (https://github.com/schungx/rhai/commit/12a536c2a42e34784b1299a0ec66ee72c9130747)

**Comment by schungx** [comment]
Ah yes.  I'll port that through.  Sorry!

**Comment by schungx** [comment]
It has now landed in this repo.

**Comment by schungx** [comment]
@philpax  did you get a chance to test this out?

**Comment by philpax** [comment]
Hi, sorry, I haven't had a chance to try it out yet - will let you know if I do!

**Comment by schungx** [comment]
Closing for now.  Feel free to reopen if you have any more questions.
