### ISSUE TITLE
(Question) How to execute multiple scripts?

### ISSUE THREAD

**Issue by djtech-dev** [rhaiscript/rhai#754]
Hi everybody.

I have a Rust object that implements several several Rhai-exposed functions, Sync and Send.

I want to execute multiple Rhai scripts that use the same functions from the same object (if needed, using an Arc is possible in this context).

I thought about:
- Running multiple Rhai engines in different threads (easiest to implement but heavy on the memory, expecially if I have dozens of scripts [minimum] and more)
- Running only one Engine and different Closures that have the functions in common and their local variables private

I wanted to ask how would you implement the second method, if it is possible; if it isn't possible, what is the best way to resolve this problem.

Thanks in advance.

**Comment by schungx** [comment]
Not very sure what exactly you're trying to achieve.  Can you post a snippet?

**Comment by schungx** [comment]
Closing for now.  Feel free to reopen if you have any more questions.
