### ISSUE TITLE
Compilation failure in 1.16 due to serde feature

### ISSUE THREAD

**Issue by thalesfragoso** [rhaiscript/rhai#760]
#759 Added a `Serialize/Deserialize` implementation for `ScriptFnMetadata` gated on the `serde` feature.
However, one of its members is a `FnAccess` type that only implements `Serialize/Deserialize` when the `metadata` feature is enabled.

Thus, the crate fails to compile if the `serde` feature is enabled while `metadata` is disabled. That wasn't the case in `1.15.1`.

**Comment by schungx** [comment]
Yup, this seems to be a bug which wasn't caught by CI.

I'll fix it and put out a patch release.
