### ISSUE TITLE
There seems to be a bug when exporting variables

### ISSUE THREAD

**Issue by ejaa3** [rhaiscript/rhai#762]
I created this issue as soon as I discovered it, so I haven't made the bug reproducible correctly (I tried to check it with rhai-tools, but the [AUR version](https://aur.archlinux.org/packages/rhai-tools) is 1.15 which does not have the bug).

I have a [map.rhai] file that imports the file [token.rhai](https://github.com/ejaa3/aquarelle/blob/main/aquarelle/code/token.rhai) as `token`. When I "run" it, I get the error:

~~~
48: "semanticTokenColors": ${token::semantic_colors}
                             ^ Variable not found: token::semantic_colors
~~~

Basically I'm creating a text file using Rhai as a preprocessor, and such error should not appear ([variable exists](https://github.com/ejaa3/aquarelle/blob/main/aquarelle/code/token.rhai#L200)). If I delete line 48 of [map.rhai], I don't get the error, but the result is incorrect: it appears that `${workbench::colors}` has been swapped with `${token::colors}`.

The bug seems to have been introduced in commit 74119105776d17903e41566275ea08a72583343b and still remains. When I go back to the previous commit (f86609ed7cca142624a81f2987c8287615518b50) everything works fine.

[map.rhai]: https://github.com/ejaa3/aquarelle/blob/main/aquarelle/code/map.rhai

**Comment by schungx** [comment]
> it appears that `${workbench::colors}` has been swapped with `${token::colors}`.

Is there a reason why you suspect this?

**Comment by schungx** [comment]
@ejaa3   Thanks for catching this.  Can you confirm that the fix works?  It has landed.  Thanks!

**Comment by ejaa3** [comment]
Yes, it works normally again. Thank you.

**Comment by schungx** [comment]
Great! I'll release a new version later today.

**Comment by schungx** [comment]
Version 1.16.2 released with the fix.
