### ISSUE TITLE
`Engine::parse_json` significantly slower than `serde_json::from_str`

### ISSUE THREAD

**Issue by zac-wilson-asecca** [rhaiscript/rhai#765]
I'm using rhai as part of a database extension and it's working well enough, but I've noticed some odd performance behaviour.

As part of what the database extension does it runs a few functions written in rhai and stored in the database on about 150,000 simple JSON objects (each function call is passed two objects and returns a boolean). The objects are flat, composed of anywhere from 5 to 25 integer, string and boolean fields. My rust code converts each json object to a rhai `Dynamic` to then call the functions with.

rhai's documentation describes `Engine::parse_json` as a lightweight alternative to using serde_json, which I guess I read as more performant (I'm not sure what else lightweight would mean, lower memory or binary size maybe). It even makes the point to call serde_json heavy so it really gives the impression that `Engine::parse_json` is the proper way to do it.

The issue is that in my testing just changing `serde_json::from_str::<rhai::Dynamic>(&json)?` to `rhai::Dynamic::from_map(engine.parse_json(&json, true)?)`makes my code go from taking 3.5 seconds to run, to taking 12.5 seconds. Given that my code is doing quite a lot of other work besides just coverting these json objects, that changing this one line manages to nearly quadrouple the run time suggests `Engine::parse_json` is anything but lightweight.

Am I doing something wrong? What was the basis for deciding to call `Engine::parse_json` lightweight? What was meant to be communicated?

**Comment by schungx** [comment]
> rhai's documentation describes `Engine::parse_json` as a lightweight alternative to using serde_json, which I guess I read as more performant (I'm not sure what else lightweight would mean, lower memory or binary size maybe). It even makes the point to call serde_json heavy so it really gives the impression that `Engine::parse_json` is the proper way to do it.

This is probably a misunderstanding.  "lightweight" means the ability to avoid pulling in `serde` which is quite heavy in code.  If you can use `serde`, by all means use it... it'll be much faster than Rhai in parsing JSON.

**Comment by zac-wilson-asecca** [comment]
Thanks for the clarification, I'll use serde for my uscase. Not sure if anything could be done in the docs to communcate this better, but at least anyone who makes the same misunderstanding I did may be able to find the answer in the form of this thread. Thanks for the quick reply and for your work building rhai, it's been really easy to integrate into my project.
