### ISSUE TITLE
v1.15 -> v1.16 breaking change: VarDefInfo field visibility

### ISSUE THREAD

**Issue by jrobsonchase** [rhaiscript/rhai#771]
The 1.15 -> 1.16 minor version bump broke the field visibility of the `VarDefInfo` struct. This should only happen on a major version bump (1.x -> 2.x) and should ideally include deprecation warnings and a migration path in the later 1.x minor versions.

For example, both the `pub name` field and the `pub fn name()` method should be available:

```rust
pub struct VarDefInfo<'a> {
    /// Name of the variable to be defined.
    #[deprecated(since = "1.16.0", note = "VarDefInfo fields will be private in the next major release. Use the methods instead.")]
    pub name: &'a str,
...
}

impl<'a> VarDefInfo<'a> {
    /// Name of the variable to be defined.
    #[inline(always)]
    #[must_use]
    pub const fn name(&self) -> &str {
        self.name
    }
...
}
```

**Comment by schungx** [comment]
Good catch.  I'll put out `1.16.3` with the fix.

**Comment by schungx** [comment]
Good catch.  I'll put out `1.16.3` with the fix.
