### ISSUE TITLE
Array support in scope

### ISSUE THREAD

**Issue by rikvdkleij** [rhaiscript/rhai#782]
Adding a `Vec<String>` or array to a scope doesn't seems to be recognized as a Rhai array during evaluation of a script.

How can a Rust `Vec` be added to the scope as an Rhai array?

**Comment by schungx** [comment]
You can convert it first into an `Array` by making it a `Dynamic`.

```rust
let v : Dynamic = value.into();
```

**Comment by rikvdkleij** [comment]
Thanks for your quick reply.

Ok, that was not clear from the documenation:
https://rhai.rs/book/language/arrays.html#arrays
```
The Rust type of a Rhai array is rhai::Array which is an alias to Vec<Dynamic>.
```

Unfortunately, it still not works:
```
                let codes: Vec<String> = ....;
                let foo: Dynamic = codes.into();
                scope.push_constant("bar", foo);

```
Script contains:
```
bar.contains("x")
```

Error:
```
ErrorFunctionNotFound", error_message: "Function not found: contains (array, &str | ImmutableString | String)
```

**Comment by schungx** [comment]
Hhhmmm... It properly recognizes the type as array. So the data is correct.

Just the function is not found, which is strange.

**Comment by rikvdkleij** [comment]
> Can you try: "x" in bar

Gives the same error.

**Comment by rikvdkleij** [comment]
O wait, `type_of` no gives `array` for `bar`

**Comment by schungx** [comment]
> O wait, `type_of()` now gives `array` for `bar`.
> 
> That differs with my previous attempts.

Yes, that's the point. The data type is correct.

Just the function is not found.

You are not using `new_raw` by any chance?

**Comment by rikvdkleij** [comment]
> You are not using new_raw by any chance?

Yes, an engine is created with `Engine::new_raw()`

**Comment by schungx** [comment]
> Yes, an engine is created with `Engine::new_raw()` because of safety reasons and side-effects as printing should not be possible.

Actually, raw engines do not have anything to do with security and safety.  You can always disable printing etc. by calling `on_print` and `on_debug` and put in stubs.  You can also disable module resolution by setting it to an empty resolver.  All these you can do on a standard Engine.

Raw engines are for environments with limited memory, so they don't load the entire standard library, and you need to pick-and-choose the libraries you need.

**Comment by rikvdkleij** [comment]
> Actually, raw engines do not have anything to do with security and safety. You can always disable printing etc. by calling on_print and on_debug and put in stubs. You can also disable module resolution by setting it to an empty resolver. All these you can do on a standard Engine.

Okay, but safety starts with disabling everything and only enable what you need :smile:
