### ISSUE TITLE
Can't sort array by string (using closure)

### ISSUE THREAD

**Issue by jpshackelford** [rhaiscript/rhai#793]
```
let a = ["alpha", "gamma", "beta"];
a.sort(|a,b| a<b);
for s in a {
    print(s);
}

a
```
Returned:
```
Waiting for Web Worker to finish loading...
Running script at 2023-12-13T05:29:22.549Z

[PRINT] alpha
[PRINT] gamma
[PRINT] beta

Script returned: "["alpha", "gamma", "beta"]"
Finished at 2023-12-13T05:29:22.554Z
```

The use of a closure is needed because my array is actually of made of dictionaries and I need to be able to sort by various attributes.

BTW I also tried with an array of DateTime objects that were passed from Rust into Rhai and code such as the following also does not work.
```
a.sort(|a,b| a - b);
```

**Comment by schungx** [comment]
The `sort` function returns an integer:

* Any positive integer if `element1 > element2`
* 0 if `element1 == element2`
* Any negative integer if `element1 < element2`

**Comment by jpshackelford** [comment]
Thanks, @schungx. Is there any string comparison function available from Rhai so that we don't have to implement that from scratch?

**Comment by jpshackelford** [comment]
Thanks for that, @schungx.

Is there a more idiomatic or elegant way of writing the following?

```
let a = ["alpha", "gamma", "beta"];

a.sort(|a, b| {
    if a > b {
        return 1;
    } else if a < b {
        return -1;
    } else {
        return 0;
    }
});

for s in a {
    print(s);
}

a
```

**Comment by schungx** [comment]
```rust
a.sort(|a, b| if a > b { 1 } else if a < b { -1 } else { 0 });
```

if `a` and `b` are numbers, you can do `a - b`.

**Comment by jpshackelford** [comment]
Seeing now that I could have looked here https://github.com/rhaiscript/rhai/blob/169af8eccbe7dab7125edecb6fa62afe199ccffd/src/packages/array_basic.rs#L1539

Thanks again for the quick reply!

**Comment by schungx** [comment]
Or here: https://rhai.rs/book/ref/arrays.html#built-in-functions
