### ISSUE TITLE
Object `to_json` produces invalid JSON when the `metadata` feature is not enabled

### ISSUE THREAD

**Issue by jeromegn** [rhaiscript/rhai#794]
With the `metadata` feature, `to_json` uses serde which correctly handles a nested array in an object. However, without `metadata`, it writes each element of the array as its string representation which is invalid JSON.

Example (runnable in the playground):

```
fn run(a) {
    let obj = #{ foo: [#{hello: "world"}], a: a };
    print(obj.to_json());
}
run(10);
```

```
Waiting for Web Worker to finish loading...
Running script at 2023-12-13T14:22:08.922Z

[PRINT] {"a":10,"foo":[#{"hello": "world"}]}

Script returned: ""
Finished at 2023-12-13T14:22:08.928Z
```

The expected line printed is: `{"a":10,"foo":[{"hello": "world"}]}`. That's what's output when using the `metadata` feature.

It makes sense to me that it wouldn't exactly work the same way, but I figure this is a bug because the docs does say that an array is supported as an object's field's value.

**Comment by schungx** [comment]
The difference is an extra `#` character for object hashes. This should not happen and is probably a bug.

**Comment by schungx** [comment]
Confirmed that this is a bug. Thanks for catching this.
