### ISSUE TITLE
Panic: Entered unreachable code when using Dynamic::into_shared()

### ISSUE THREAD

**Issue by MolotovCherry** [rhaiscript/rhai#832]
Using the following code, I am able to cause an unreachable code panic

I don't know if I'm just perhaps missing something here, or doing something I'm not supposed to, but I am indeed able to get this to panic at runtime if I attempt to write to the variable
```rs
let map: Dynamic = Map::new().into();
let map = map.into_shared();

#[allow(deprecated)]
engine.on_var(move |name, _, _| match name {
    "V" => Ok(Some(map.clone())),
    _ => Ok(None),
});
```
Rhai code:
```rs
// not ok
V.a = "";
// ok
V = #{"a": ""};

// funnily enough, this is also ok
V.foo();
fn foo() {
    this.a = "";
}
```
Panic
```
Message:  internal error: entered unreachable code: `get_indexed_mut` cannot handle shared values
Location: <snip>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rhai-1.17.1\src\eval\chaining.rs:320
```

**Comment by schungx** [comment]
Yes, this should be a bug. Thanks for catching.

Luckily I put in a panic to catch the cases I never think would happen.

**Comment by schungx** [comment]
I think I fixed it.

It is in the latest drop, so you can try it out.

Do you need it urgently?  Can you wait till the next major release?

**Comment by MolotovCherry** [comment]
> I think I fixed it.
> 
> It is in the latest drop, so you can try it out.
> 
> Do you need it urgently? Can you wait till the next major release?

Thank you for the quick fix! I think I can hold out until next release~

**Comment by schungx** [comment]
You can point to this repo to test out the fix.

**Comment by MolotovCherry** [comment]
Confirmed, it's working properly!
