### ISSUE TITLE
Error including wasm-bindgen feature in a workspace crate.

### ISSUE THREAD

**Issue by ryankopf** [rhaiscript/rhai#839]
I am experiencing some difficult bugs while trying to include a wasm-specific project that uses RHAI with wasm-specific features, in a workspace that has other non-wasm projects. The context is game development. I have a workspace with a game_core (gameplay logic, core models, etc), game_server, and game_wasm. Games can be run by both the game_server and game_wasm, so both of them depend on RHAI. I'm encountering issues getting Rust-Analyzer and Cargo to respect my .cargo/Config.toml files.

I've broken it down to a much easier reproduce situation.

This is happening on Windows, but I think the same would happen on other OS's.

```
mkdir workspace
cd workspace
cargo init --lib
cargo new test1
cargo new test2
```

Edit the root cargo.toml file:
```
[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "test1",
    "test2",
]
```

Edit test1's Cargo.toml file:
```
[dependencies]
rhai = { version = "1.17.1", features = ["wasm-bindgen"] }
```

Edit test2's Cargo.toml file:
```
[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
```

Run:
`
cargo run -p test1
`

And get:
compile_error!("`wasm-bindgen` cannot be used for non-WASM target");

To solve it, you're supposed to be able to add test1/.cargo/config.toml 
```
[build]
target = "wasm32-unknown-unknown"
```

However this does not work, and you still get the compilation error. Move the .cargo/config.toml file up to the workspace level, and it works.

BUT the issue is then you get conflicts with other crates.

And suddenly you're getting `cannot find type 'Event' in module 'sys'` errors, because tokio depends on mio which uses conditional flags to include OS-specific features. Even including a new test2/.cargo/config.toml file with a local target, such as this does not work:
```
[build]
target = "x86_64-pc-windows-msvc"
```

I'm not sure if this is a Cargo issue, rust-analyzer issue, a RHAI issue, or a MIO issue yet.

**Comment by ryankopf** [comment]
I managed to get around the issue temporarily by specifying conditional dependencies in my Cargo.toml file:
```
[target.'cfg(target_arch = "wasm32")'.dependencies]
rhai = { version = "1.17.1", features = ["wasm-bindgen"] }
```
However this only works because I am actually using rhai from yet a different crate, otherwise Rust-Analyzer would complain that "rhai" doesn't exist.

**Comment by schungx** [comment]
Not very sure about this... I think it might be a hiccup with Rust Analyzer...

**Comment by ryankopf** [comment]
I think you're right. I think it may not be supported by Rust Analyzer. https://github.com/rust-lang/rust-analyzer/issues/16765

**Comment by ryankopf** [comment]
I'll close this issue as it is not RHAI specific.
