### ISSUE TITLE
Registered enum types can't be used with assert_eq in Rhai 

### ISSUE THREAD

**Issue by Hodkinson** [rhaiscript/rhai#843]
I registered an enum as described here: https://rhai.rs/book/patterns/enums.html

It works as described, I can use the enum (and pass it as an argument), so it seems the type is registered:

`assert!(MyEnum::Foo == MyEnum::Foo)`

however I cannot check for equality using assert_eq!:

`assert_eq!(MyEnum::Foo, MyEnum::Foo);`

ERROR: Runtime error: unknown types in assertion: left was example::MyEnum, right was example::MyEnum (line 22, position 9)

**Comment by schungx** [comment]
Well, you know that but Rhai doesn't. Unless you define the `==` operator for that enum type, Rhai can only assume that one opaque object is not the same as another...

**Comment by Hodkinson** [comment]
I did that in the macro:

```
#[rhai_fn(global, name = "==", pure)]
pub fn eq(my_enum: &mut $typ, my_enum2: $typ) -> bool {
    my_enum == &my_enum2
}

#[rhai_fn(global, name = "!=", pure)]
pub fn neq(my_enum: &mut $typ, my_enum2: $typ) -> bool {
    my_enum != &my_enum2
}
```

**Comment by Hodkinson** [comment]
I also tried defining the comparison operators directly on the enum type itself but I had the same error. Although the == comparison works when they are defined, using within `assert_eq` fails.

**Comment by schungx** [comment]
May I ask whether you derived `Clone` for your type?

**Comment by schungx** [comment]
Can you post your exact `aasert_eq` call?

**Comment by Hodkinson** [comment]
My bad - I had forgotten that I had defined the assert_eq call myself, I had thought this was within rhai. I patched the assert_eq call to handle this extra type and now it works as expected. Thank you for the quick response. 🙏🏻
