### ISSUE TITLE
to_float not implemented for float

### ISSUE THREAD

**Issue by voelklmichael** [rhaiscript/rhai#844]
Please implement  "to_float" for float.
Ideally, implement "to_int" also for "int", and "to_decimal" for "decimal".
(cf. [https://rhai.rs/book/ref/convert.html?highlight=to_float#convert-between-integer-and-floating-point])

This was discussed on discord "#general", 20. February, 2024.

**Comment by schungx** [comment]
Yes, these will all be added in the next release.  Do you need it urgently?

**Comment by voelklmichael** [comment]
No, I do not need it urgently.
That was just meant as a friendly reminder/documentation (which I can link to).
Thank you for the quick feedback.

**Comment by schungx** [comment]
You can try out the latest drop which has it.

**Comment by voelklmichael** [comment]
Ok, thank you.
Works.
