### ISSUE TITLE
Customizing "let", "fn" syntax

### ISSUE THREAD

**Issue by VinnyVicious** [rhaiscript/rhai#860]
With Rhai, is it possible to rename the keyword `fn` to something like `def`? What about the `let` keyword? Would it be possible to remove it all together and have no keyword for variable definition? How flexible is the parsing of Rhai?

**Comment by VinnyVicious** [comment]
Removing `let` though would not allow variables to be declared, though. I just want it to be `foo = 5` instead of `let foo = 5`.

**Comment by schungx** [comment]
> Removing let though would not allow variables to be declared, though. I just want it to be foo = 5 instead of let foo = 5. Or maybe $foo = 5

As I mentioned, it is not possible to alter Rhai's _syntax_, meaning that you can't do these.

For `$foo` you may try a custom syntax...  but it really is not recommended for you to alter Rhai's syntax to accommodate another language.  Perhaps you should fork Rhai and directly modify its syntax to suit yours...

**Comment by VinnyVicious** [comment]
Thank you for the clarification, that does make sense.
