### ISSUE TITLE
on_var not called for variables in closures

### ISSUE THREAD

**Issue by justinpombrio** [rhaiscript/rhai#862]
The `on_var` callback seems to not be invoked for variables that appear in closures.

**Rhai version:** 1.18.0

**Input**

```rs
use rhai::{Dynamic, Engine};

fn main() {
    let mut engine = Engine::new();
    let shared_state = 173; // In reality, would be an Rc<RefCell<_>>

    #[allow(deprecated)]
    engine.on_var(move |name, _, _| {
        if name == "state" {
            Ok(Some(Dynamic::from(shared_state)))
        } else {
            Ok(None)                                     
        }
    });

    engine.run("state").unwrap(); // variable found
    engine.run("fn f() { state }; f()").unwrap(); // variable found
    engine.run("|| state").unwrap(); // variable not found
}
```

**Expected:** the `on_var` callback to be invoked in all three cases.

**Actual:** the `on_var` callback is not invoked for the closure, resulting in a "variable not found" error.

**Comments:** This makes `on_var` ineffective for our use case. Our goal is to expose a single global "runtime" for use _everywhere_. User written scripts should be able to access methods like `runtime.do_thing()` anywhere in any script. Here's what we've tried overall:

- Putting `runtime` as a `Rc<RefCell<Runtime>>` in a `Scope`. This makes `runtime` inaccessible inside Rhai `fn`s, though, as documented.
- Putting `runtime` as a `Rc<RefCell<Runtime>>` inserted via `Engine.on_var()`. This makes `runtime` inaccessible inside Rhai closures (this issue).

The final thing we'll try (if this issue isn't fixable) is to bind every method on `Runtime` as a function in Rhai. But wrap them all in a module, so that they're not all spilled into the global namespace (there may be hundreds of them all told).

**Comment by schungx** [comment]
That should not be.  I suspect a bug.  Let me try that out.

**Comment by schungx** [comment]
This is a relatively simple fix.  Do you need this fix urgently?  If so, I can release `1.18.1`... otherwise you can pull from this repo until `1.19.0` comes out...

**Comment by justinpombrio** [comment]
> Do you need this fix urgently?

Nope! We got our test case working with a [Rhai module and FuncRegistration instead](https://github.com/justinpombrio/synless/blob/master/examples/rhai/script_loop.rs).  We might (or might not) eventually switch to on_var instead, but not at all urgent.

Thanks for the quick response!

**Comment by schungx** [comment]
Thanks.  The fix has landed here.  You can pull from this repo to try it out.

**Comment by justinpombrio** [comment]
Confirmed fixed!

**Comment by schungx** [comment]
Closing this for now.  Feel free to reopen if there are further problems.
