### ISSUE TITLE
The `sync` feature flag is not compatible with `no_std`

### ISSUE THREAD

**Issue by roeeshoshani** [rhaiscript/rhai#867]
when i enable both the `sync` and the `no_std` feature flags, rhai won't compile due to using `std::sync::RwLock`, which is not provided by the `no-std-compat` crate due to not using the `compat_sync` feature flag of that crate.

this can simply be solved by enabling the `compat_sync` feature flag of the `no-std-compat` crate.

**Comment by schungx** [comment]
Ah, thanks for this. Will you make a PR? Or I can do it.
