### ISSUE TITLE
min(f64, f64)  function not found

### ISSUE THREAD

**Issue by xkentr** [rhaiscript/rhai#877]
I ran into trouble with a simple script that computes the min of 2 numbers. The highly simplified version of the issue fails on the playground as well.

```
let a = 0.1;
let b = 0.2;
let c = min(a, b);
```
This fails with the error:
```
Waiting for Web Worker to finish loading...
Running script at 2024-05-20T20:59:02.545Z


EXCEPTION: Function not found: min (f64, f64) (line 3, position 9)
Finished at 2024-05-20T20:59:02.550Z
```
The same thing does not happen with integer values.
The code in [logic.rs](https://github.com/rhaiscript/rhai/blob/main/src/packages/logic.rs#L49) seems to suggest that f64 comparisons are only created when f32_float is enabled?

**Comment by schungx** [comment]
Hhhmm... I thought I added back the missing function... Probably not.

I'll check it out.

**Comment by schungx** [comment]
Yes, it turns out it is an omission by mistake.  The version where both operands are floats is missing.

I'll add them back.

**Comment by schungx** [comment]
The missing functions should exist in the new version.  Closing this for now.
