### ISSUE TITLE
Add `position` to `EvalAltResult::SystemError`

### ISSUE THREAD

**Issue by sgpthomas** [rhaiscript/rhai#883]
For error reporting, it would be nice to have `Position` for SystemErrors. I'm imagining a case where some rust function, that is called from a Rhai context, produces some error. I want to be able to locate the Rhai position that caused this error so that I can report it nicely. Is this something that would be possible?

**Comment by schungx** [comment]
It would be possible, but then it would be a breaking change...

Maybe you can use another error variant?

**Comment by schungx** [comment]
Closing this for now.  Feel free to reopen if there are further issues.
