### ISSUE TITLE
on_debug callback not presenting source

### ISSUE THREAD

**Issue by markeel** [rhaiscript/rhai#884]
I have started integrating rhai into my application and all is going well, but I wanted to catch debug statements, but the second parameter should be the source I specified after compiling the AST with "set_source()"

I've checked and a call to the AST after with ".source()" returns what I set, but the on_debug() call does not include the source parameter.  It is always None.

This feels like a bug, but it's possible I'm not setting something up properly.  The "Rhai Book" says the only thing necessary is to call set_source(), and because ".source()" is returning the expected value, I think I've done that.

Here is the registering of the on_debug statement

```
        engine.on_debug(|msg, src, pos| {
            eprintln!("{src:?}:{pos}:{msg}");
        });
```

Here is where I create it.

```
	...
       match self.rhai.engine.compile(script) {
            Ok(mut ast) => {
                let ast_src = src.as_ref().unwrap();
                let ast_id = format!("{}:{}", ast_src.source, ast_src.source_position);
                ast.set_source(ast_id.as_str());
                println!("get_ast source: {:?}", ast.source());
                let shared = rhai::Shared::new(ast);
                println!("get shared source: {:?}", shared.source());
	...
```
                 

Here is where I invoke it.

```
	...
        let ast = &func.unwrap().ast;
        println!("source of ast: {:?}", ast.source());
        let name = &func.unwrap().name;

        match self.rhai.engine.call_fn_with_options::<rhai::Dynamic>(options, &mut scope, ast, name, args) {
        ...

```

Here is the rhai script I am running:
```
            fn call_me(p) 
                debug("called call_me");
                return `${p.value}_id`
            }
```

What I get when I run it (it gets run twice in my test suite):

```
get_ast source: Some("test:4")
get shared source: Some("test:4")
source of ast: Some("test:4")
None:line 3, position 5:"called call_me"
source of ast: Some("test:4")
None:line 3, position 5:"called call_me"
```

**Comment by schungx** [comment]
Hhmmm... May be an oversight.

The souce is primarily used when loading separate modules for an easy way to track where functions come from.

It probably should be set also when running an AST. I'll take a look.

**Comment by schungx** [comment]
Found something strange.  The test here:

https://github.com/rhaiscript/rhai/blob/main/tests/print.rs#L38

should test against setting source in the AST and getting it back in `debug` statements.

**Comment by schungx** [comment]
You can check out the new drop https://github.com/rhaiscript/rhai/pull/885

This should fix the issue.

**Comment by markeel** [comment]
Awesome, I'll check it out.

**Comment by schungx** [comment]
Closing this for now.  Feel free to reopen if there are further issues.
