### ISSUE TITLE
`#[rhai_type]` for custom type is not working in plugin module

### ISSUE THREAD

**Issue by AzurIce** [rhaiscript/rhai#909]
Hi! I have a CustomType like this:

```rust
#[derive(Clone, CustomType)]
#[rhai_type(extra = Self::build_extra)]
struct Server {
    inner: crate::server::Server,
}

impl Server {
    pub fn running(&mut self) -> bool {
        self.inner.running()
    }

    pub fn start(&mut self) -> Result<(), String> {
        self.inner.start()
    }

    pub fn stop(&mut self) -> Result<(), String> {
        self.inner.stop()
    }

    // ...

    fn build_extra(builder: &mut TypeBuilder<Self>) {
        println!("!!!!!!!!!!build_extra");
        builder
            .with_fn("start", Self::start)
            .with_fn("stop", Self::stop)
            /* ... */;
    }
}
```

with `engine.build_type::<Server>()`, I can successfully call `server.xxx()` in rhai.

However, when I wrapped it into a plugin module:

```rust
use rhai::plugin::*;

#[rhai::export_module]
mod server_api {
    pub type Server = super::Server;
}
```

and register it using:

```rust
engine.register_global_module(exported_module!(server_api).into());
```

It says `Function not found` when I call `server.xxx()` in rhai.

And I found that `build_extra` is not being called(`#[rhai_type]` seems not working for the CustomType in plugin module).

Now I have to re-implement all method like this if I want to turn it into a plugin module:

```rust
#[rhai::export_module]
mod server_api {
    pub type Server = super::Server;

    pub fn running(server: &mut Server) -> bool {
        server.running()
    }

    pub fn start(server: &mut Server) -> Result<(), String> {
        server.start()
    }

    // ...
}
```

I also tried `#[rhai_type(name = "xxx")]` and run `print(type_of(server))` in rhai, the name is also not changed under plugin module's case.

Is this a bug?

**Comment by schungx** [comment]
Not a bug. The CustomType API is separate from the plugin module API. They do not overlap each other.

Of course you can use both but you'll have to register both. They don't conflict (if conflict the newer overrides the old).

**Comment by AzurIce** [comment]
Oh, I see. Thank you very much!

**Comment by schungx** [comment]
Usually you either use CustomType or plugin module, not both, as they work similarly to each other.
