### ISSUE TITLE
Print function doesn't work when adding packages manually

### ISSUE THREAD

**Issue by madser123** [rhaiscript/rhai#914]
When reading your docs around [built-in packages](https://rhai.rs/book/rust/packages/builtin.html?highlight=packages#built-in-packages) it states that you can create a "raw" engine and add the packages needed manually.

When doing this, even though i am adding the `BasicStringPackage` which should add the `print` functionality, `print` does not work. This also goes if adding the whole `CorePackage`.

When using print no error pops up, and no output comes out.

I've tried both adding the package(s) with `Engine::register_into_engine` and also creating a shared module and adding them with the `Engine::register_global_module`.

However, using the `Engine::new()` works as intended, and after looking at the code, i see why. The `print` and `debug` closures used are added directly to the engine in the function:
https://github.com/rhaiscript/rhai/blob/af3f00e23352f7967d0ce1a987a4340f29dbace8/src/engine.rs#L301-L314

I'm unsure if this the "intended" behaviour, and i'm just misunderstanding something. When the docs say that the `BasicStringPackage` adds "basic string functions (e.g. print, debug, len) that are not built in" it, at least to me, seems like they would just work.

Is this intended? And if it is, how can i get the `print` and `debug` functions to work as with the `Engine::new` function (The `Engine.print` and `Engine.debug` field, containing the closures, are marked with `pub(crate)` so i can't change them directly like the function does)?

**Comment by madser123** [comment]
After writing the issue i found the `Engine::on_print` function, which solved the problem.

However, i still want to point out that the docs regarding the packages still are a bit confusing for newcomers to the crate. If a warning or alike could be added to state that the `BasicStringPackage` adds the functions to the engine, but doesn't add the hook to stdout, it would be nice for newcomers like myself.

The issue can just be closed, if you disagree.

**Comment by schungx** [comment]
That's correct. The raw engine also does not specify the print/debug hooks. I probably need to be more clear.

**Comment by schungx** [comment]
It does say it here:

![{CA8CC4D0-C81A-4346-B14D-5632CFA9FDEE}](https://github.com/user-attachments/assets/5fd9b414-4cfe-4f8d-a98e-f8992beaefc5)

**Comment by madser123** [comment]
I see. Sorry - Thought i was pretty thorough.. Good to know :+1:

**Comment by schungx** [comment]
I'll close this for now. Feel free to reopen.
