### ISSUE TITLE
Internal panic in the engine

### ISSUE THREAD

**Issue by irevoire** [rhaiscript/rhai#916]
Hello rhai team,

We've introduced the possibility to edit document by (rhai) function in Meilisearch a few months ago and a user reported an internal panic in rhai.
I didn’t have the time to try to reproduce the issue on my side yet, but I thought it could be nice for you to get the error with the line number in case it’s trivial to fix:
```
2024-09-25T07:11:29.563769Z ERROR meilisearch: info=panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.19.0/src/engine.rs:347:58: called `Option::unwrap()` on a `None` value
```

And here’s the original issue with the function if that helps: https://github.com/meilisearch/meilisearch/issues/4956

Thanks for the awesome lib 🎉

**Comment by schungx** [comment]
This seems to happen during a strings cache contention.  I can see that, under `sync`, there is possibility that the strings cache is still locked by another process while somebody wants to write to it.

**Comment by schungx** [comment]
Can you check the latest drop to see if it happens again?  I just pushed a fix.

**Comment by irevoire** [comment]
Hey, after a lot of tests from ourselves and our users we didn’t reproduce this bug or anything similar, thanks for the patch!

Do you think you could make a new patch release this week so we’re not relying on the git repo + a rev?

**Comment by longzou** [comment]
I encountered the same proble. 
It points to this function:


    pub fn get_interned_string(
        &self,
        string: impl AsRef<str> + Into<ImmutableString>,
    ) -> ImmutableString {
        match self.interned_strings {
            Some(ref interner) => locked_write(interner).unwrap().get(string),
            None => string.into(),
        }
    }


the locked_write(interner) returns None.

**Comment by schungx** [comment]
Please kindly check out the latest drop to see if it solves your problem.

I'm planning to make a new release soonish if everything is stable.

**Comment by schungx** [comment]
@irevoire   hope this is now resolved?

**Comment by irevoire** [comment]
Hey, we've not heard of this issue again.
I cannot say for sure it's 100% solved since it's not our most used feature. But it's definitely _probably_ solved ahah

**Comment by schungx** [comment]
Great! So closing this for now.
