### ISSUE TITLE
How to use global variable in rhai  function declared in rust

### ISSUE THREAD

**Issue by rawhuul** [rhaiscript/rhai#922]
Hi, there I want to call a function `foo` which will update the scope variable named `bar` but it must be implemented in Rust.

```rust
fn foo(scope: &mut Scope, path: &str) {
    scope.set_or_push("bar", path);
}
```

But upon calling the function as:
```rust
foo("abcd")
```

it throws error:
```bash
Error: ErrorFunctionNotFound("foo (&str | ImmutableString | String)", 2:9)
```

Can I pass the scope as argument (which is not an ideal choice), is there any workaround to that?

**Comment by schungx** [comment]
You cannot.   You cannot modify the scope within a Rust function.

Rhai depends on you not being able to modify the scope for some of its optimizations.

**Comment by rawhuul** [comment]
Cool. Thanks!!
