### ISSUE TITLE
Support to represent `NaN`

### ISSUE THREAD

**Issue by rawhuul** [rhaiscript/rhai#930]
Hi there! I noticed that the book doesn’t include any syntax or method for representing `NaN`. Are there plans to add that?

**Comment by schungx** [comment]
`NaN` is a valid value for floats...  there just isn't a literal symbol for it.  You can probably define one.  It is just a constant.

**Comment by rawhuul** [comment]
> NaN is a valid value for floats... there just isn't a literal symbol for it. You can probably define one. It is just a constant.

Yeah this will work.

> Why do you need it anyway? Can you do with methods such as is_nan?

I am making DSL to work with DataFrames, where `NULL` values are often represented and interpreted as `NaN`.

**Comment by schungx** [comment]
> I am making DSL to work with DataFrames, where `NULL` values are often represented and interpreted as `NaN`.

I would suggest thinking twice about it.  `NaN` is actually not a _single_ number.  It is actually a range of bit patterns.

**Comment by rawhuul** [comment]
> I would suggest thinking twice about it. NaN is actually not a single number. It is actually a range of bit patterns.

I second you on that but its used often in data science field.
