### ISSUE TITLE
Scope `get_value_mut()` fails with `String`

### ISSUE THREAD

**Issue by DougAnderson444** [rhaiscript/rhai#933]
https://github.com/rhaiscript/rhai/blob/801c2ad7d96a9955913bbe5e39f6649b6531a889/src/types/scope.rs#L561

Hello,

I'm not sure if it's intended, but `scope.get_value_mut::<String>(my_var)` fails to return a `&mut String`.

Pretty sure it's because Dynamic `downcast_mut` doesn't cover the String case.

**Comment by schungx** [comment]
Can you try with `get_value_mut::<ImmutableString>(my_var)`?

Rhai does not use Rust `String`s, but `ImmutableString`s.

**Comment by DougAnderson444** [comment]
I did try with `ImmutableString` which works well, the only thing is I needed a `&mut String` so I was left trying to convert `ImmutableString` to regular string.

I ended up going a different route instead of taking a mutable reference directly from Rhai, so this is no longer an issue for me.

Thanks for the clarification!
