### ISSUE TITLE
Object array attribute sorting

### ISSUE THREAD

**Issue by amtineo** [rhaiscript/rhai#937]
I am new to writing rhai scripts and rust... I am using rhai to enhance a behavior in an apollo router setup. My rhai script filters the graphql response data from the underlying subgraphs...

The behavior that I'm noticing is that rhai is sorting the attributes in each object within my response array by its name and I would like to know if there's a possibility to not sort the object attributes so that the graphql attribute request and response are the same in order.

I could reproduce the behavior in the rhai playground:

```
let x = [
    #{
        "name": "John",
        "sex": "male",
        "age": 20,
    },
    #{
        "name": "Jane",
        "age": 21,
        "sex": "female"
    },
];

print (x);
print (x.filter(|n| return n.age == 20));
```

the output:

```
[PRINT] [#{"age": 20, "name": "John", "sex": "male"}, #{"age": 21, "name": "Jane", "sex": "female"}]
[PRINT] [#{"age": 20, "name": "John", "sex": "male"}]
```

as you can see, the "name, age, sex" attributes were sorted. Is this the desired behavior for rhai?

**Comment by schungx** [comment]
Yes, Rhai's object map type uses `BTreeMap` which sorts its keys.

There is a call to enable using `IndexMap` which preserves order but it is not yet implemented

**Comment by schungx** [comment]
However, an object map does not guarantee any ordering of keys. Therefore it is free to arrange keys in any way it wants, since ordering is not significant.  Why do you want to keep the keys order?

**Comment by amtineo** [comment]
Thanks for the explanation. At the moment, it doesn't matter to me, but I did want to have consistency between what is requested and what the response is (order-wise). I'll keep on the lookout if the feature to use and `IndexMap` is implemented.
