### ISSUE TITLE
All relative links in the rhai book are broken

### ISSUE THREAD

**Issue by therealprof** [rhaiscript/rhai#939]
All relative links in the rhai book available at https://rhai.rs/book/ point to non-existing locations.

As evident right from the home page of the book where the image (pointing to `/images/logo/rhai-banner-transparent-colour.svg`) doesn't show but also from other internal links on all pages (at least all that I clicked on) point to nowhere (e.g. `/engine/debugging/debugger.html`).

I'm pretty sure the problem is a missing `/book` in the URI path, so instead of `/engine/debugging/debugger.html`, the correct path would should `/book/engine/debugging/debugger.html`. Not sure how and when that got lost, though, probably the tooling changed.

**Comment by schungx** [comment]
Thanks for bringing this up. I probably forgot the setting.

**Comment by schungx** [comment]
It is fixed. Please check it.

**Comment by therealprof** [comment]
Happy to confirm it's fixed now.
