### ISSUE TITLE
raw string adds newline before `"`

### ISSUE THREAD

**Issue by benatkin** [rhaiscript/rhai#943]
A raw string adds a newline before a `"` after #941 

Fix incoming.

**Comment by schungx** [comment]
This is strange, because there is a unit test... obviously it doesn't test the right conditions...

**Comment by benatkin** [comment]
any string that has a line that ends in `"`

**Comment by benatkin** [comment]
Got a PR with a test case and a hopeful fix: https://github.com/rhaiscript/rhai/pull/944
